#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"
REPO_NAME=hazelcast-desktop

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-clean] [-?]"
   echo ""
   echo "   Builds the jet_demo jar files that can readily be submitted to Jet. It downloads"
   echo "   all the necessary files to build the jar files. It places jar files in the"
   echo "   following directory:"
   echo ""
   echo "      $APP_DIR/lib"
   echo ""
   echo "   -clean Cleans up the build files after the build completes."
   echo ""
   echo "Default: ./$EXECUTABLE"
   echo ""
   exit
fi

# SED backup prefix
if [[ ${OS_NAME} == DARWIN* ]]; then
   # Mac - space required
   __SED_BACKUP=" 0"
else
   __SED_BACKUP="0"
fi

pushd $APP_DIR > /dev/null
# Change the addon version number in the desktop pom.xml
sed -i${__SED_BACKUP} 's/<jet.version>.*<\/jet.version>/<jet.version>'$HAZELCAST_VERSION'<\/jet.version>/' pom.xml
popd > /dev/null

if [ ! -d "$APP_DIR/books" ]; then
   mkdir "$APP_DIR/books"
fi

echo "Downloading books..."

BOOKS_BASE_URL=https://raw.githubusercontent.com/hazelcast/hazelcast-jet/master/examples/wordcount/src/main/resources/books
BOOKS="a-tale-of-two-cities.txt madame-bovary.txt adventures-of-sherlock-holmes.txt odyssey.txt anderson-fairy-tales.txt peter-pan.txt around-the-world-in-eighty-days.txt pride-and-prejudice.txt dorian-gray.txt relativity-special-and-general-theory.txt edgar-allan-poe-works-1.txt shakespeare-complete-works.txt frankenstein.txt through-the-looking-glass.txt grimm-brothers.txt time-machine.txt huckleberry-finn.txt tom-sawyer.txt land-of-oz.txt war-of-the-worlds.txt"

let COUNT=0
for BOOK in $BOOKS; do
   if [ ! -f "$APP_DIR/books/$BOOK" ]; then
      let COUNT=COUNT+1
      curl -sS -o "$APP_DIR/books/$BOOK" $BOOKS_BASE_URL/$BOOK
   fi
done

if [ $COUNT -eq 0 ]; then
   echo "Books already downloaded."
else
   echo "Books downloaded."
fi

# Build jet_demo jar files
pushd $APP_DIR > /dev/null
mvn -DskipTests clean package
popd > /dev/null

#
# Display build information
#
echo ""
echo "Workspace: $PADOGRID_WORKSPACE"
echo ""
echo "Built jet_demo jar files that are ready to be submitted to Jet in the following directory:"
echo ""
echo "   $APP_DIR/lib"
echo ""
echo "To submit jar files to Jet run the 'jet.sh' executable. For example,"
echo ""
echo "   cd $APP_DIR/lib"
if [ "$HAZELCAST_MAJOR_VERSION_NUMBER" -ge 4 ]; then
   JET_EXECUTABLE="jet"
else
   JET_EXECUTABLE="jet.sh"
fi
echo "   $JET_EXECUTABLE submit WordCountJob.jar"
echo "   $JET_EXECUTABLE -a localhost:5701 submit WordCountJob.jar"
echo ""
echo "If the job outputs can be monitored by running 'show_log'. For example,"
echo ""
echo "   show_log"
echo "   show_log -num 2"
echo "   show_log -cluster myjet -num 2"
echo ""
