#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-cluster -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Generate a member script from a cluster to run in the Hazelcast distribution

SYNOPSIS
   $EXECUTABLE [-cluster cluster_name]

DESCRIPTION
   Generates a member script that runs the 'start.sh' executable included in the
   Hazelcast distribution. The script is generated in the cluster directory.

OPTIONS
   -cluster cluster_name
             Cluster name.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -cluster $CLUSTER

FILES
   $CLUSTER_DIR/generated
             The directory in which the script is generated.

EOF
fi
   exit
fi

if [ "$(isClusterExist $CLUSTER)" == "false" ]; then
   echo >&2 "----------------------------------------------------------------"
   echo >&2 "WORKSPACE: $PADOGRID_WORKSPACE"
   echo >&2 "  Cluster: $CLUSTER"
   echo >&2 "    ERROR: This cluster has not been created. Please run the create_cluster command to"
   echo >&2 "           to create the cluster before running this command. Command aborted."
   echo >&2 "----------------------------------------------------------------"
   exit 1
fi

start_member -cluster $CLUSTER -create-script

popd > /dev/null 2>&1
