#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Create the Prometheus datasource in Grafana

SYNOPSIS
   /$EXECUTABLE [-datasource datasource_name] [-?]

DESCRIPTION
   Creates the Prometheus datasource in Grafana.

OPTIONS
   -datasource datasource_name
             Datasource name. Default: $DEFAULT_DATASOURCE

DEFAULT
   ./$EXECUTABLE -datasource $DEFAULT_DATASOURCE

EOF
exit
fi

if [ "$DATASOURCE" == "" ]; then
   DATASOURCE=$DEFAULT_DATASOURCE
fi

curl -sS -X POST $GRAFANA_URL_REST/api/datasources -H "Content-Type: application/json" -d '{"name": "'"$DATASOURCE"'", "type": "prometheus", "url": "http://'"$PROMETHEUS_URL"'", "access": "proxy", "basicAuth": false, "jsonData": { "httpMethod": "GET", "keepCookies": [] } }' | jq .
