#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Delete the specfied Grafana folder

SYNOPSIS
   ./$EXECUTABLE [-folder folder_name] [-?]

DESCRIPTION
   Deletes the specfied Grafana folder

OPTIONS
   -folder folder_name
             Folder name. Default: $DEFAULT_FOLDER

DEFAULT
   ./$EXECUTABLE -folder $DEFAULT_FOLDER

EOF
exit
fi

if [ "$FOLDER" == "" ]; then
   FOLDERS=$DEFAULT_FOLDER
fi

__UID=`./get_folder_uid -folder $FOLDER`
if [ "$__UID" == "" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Folder not found [$FOLDER]. Command aborted."
   exit 1
fi

curl -sS -X DELETE $GRAFANA_URL_REST/api/folders/$__UID | jq .
