#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Convert Grafana dashboard files

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Converts all the Grafana dashboard files found in the following default export directory:
      $EXPORT_DASHBOARD_DIR

   and places them in the following default template directory:
      $EXPORT_TEMPLATE_DIR

   To export dashboards, run the 'export_folder' command.

   To import the templates, place them in the following directory and run the 'import_folder' command:
      $DASHBOARDS_DIR

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

if [ ! -d $EXPORT_DASHBOARD_DIR ]; then
   echo ""
   echo "ERROR: Folders have not been exported. Run 'export_folder' to export folders first"
   echo "       before executing this command. Command aborted."
   echo ""
   exit 1
fi

if [ ! -d $EXPORT_TEMPLATE_DIR ]; then
   mkdir $EXPORT_TEMPLATE_DIR
fi

pushd $EXPORT_DASHBOARD_DIR > /dev/null 2>&1
for EXPORT_FOLDER_DIR in *; do
   FOLDER_NAME=$(basename "$EXPORT_FOLDER_DIR")
   
   # Create the folder dir in the template dir
   if [ -d $EXPORT_TEMPLATE_DIR/$FOLDER_NAME ]; then
      rm -rf $EXPORT_TEMPLATE_DIR/$FOLDER_NAME
   fi
   mkdir $EXPORT_TEMPLATE_DIR/$FOLDER_NAME

   # Convert the exported files to templates and place them 
   # in the template dir.
   if [ ! -z "$(ls -A $FOLDER_NAME)" ]; then
      pushd $FOLDER_NAME > /dev/null 2>&1
      for file in *; do
        `cat "$file" | jq ".dashboard.annotations.list[].datasource=\"\\${DATASOURCE}\" 
                     | .dashboard.panels[].datasource=\"\\${DATASOURCE}\" 
                     | .dashboard.panels[].targets[].datasource=\"\\${DATASOURCE}\" 
                     | del(.meta) 
                     | .folderId=\"\\${FOLDER_ID}\" | .overWrite=false
                     | del(.dashboard.version, .dashboard.uid, .dashboard.id) 
                     " > "$EXPORT_TEMPLATE_DIR/$FOLDER_NAME/$file" `
      done
      popd > /dev/null 2>&1
   fi
   if [ -z "$(ls -A $FOLDER_NAME)" ]; then
      echo "Template folder created: $FOLDER_NAME - empty"
   else
      echo "Template folder created: $FOLDER_NAME"
   fi
done
popd > /dev/null 2>&1

echo "Template folders generated in the following directory:"
echo "   $EXPORT_TEMPLATE_DIR"
echo ""

