#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2022 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Display the UID of the specified Grafana folder

SYNOPSIS
   ./$EXECUTABLE [-folder folder_name] [-?]

DESCRIPTION
   Displays the UID of the specified Grafana folder.

OPTIONS
   -folder folder_name
             Folder name. Default: $DEFAULT_FOLDER

DEFAULT
   ./$EXECUTABLE -folder $DEFAULT_FOLDER

EOF
exit
fi

if [ "$FOLDER" == "" ]; then
   FOLDER=$DEFAULT_FOLDER
fi

TMP_FILE=$TMP_DIR/folders.json
./get_folders > $TMP_FILE

# Cygwin path conversion
if [[ ${OS_NAME} == CYGWIN* ]]; then
   TMP_FILE="$(cygpath -wp "$TMP_FILE")"
fi

ARRAY_LEN=`jq '.|length' $TMP_FILE`
let LAST_INDEX=ARRAY_LEN-1
for i in $(seq 0 $LAST_INDEX); do
   TITLE=`jq '.['$i'].title' $TMP_FILE`
   TITLE=`trimDoubleQuotes $TITLE`
   if [ "$TITLE" == "$FOLDER" ]; then
      __UID=`jq '.['$i'].uid' $TMP_FILE`
      break;
   fi 
done;
echo `trimDoubleQuotes $__UID`
