#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# Get all folders from the dashbarod dir
pushd $DASHBOARDS_DIR > /dev/null 2>&1
__FOLDERS=`ls`
FOLDERS=""
for i in $__FOLDERS; do
   FOLDERS="$FOLDERS $i"
done
popd > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - List Grafana folders in this app's directory

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Lists all of the folders that are available in the 'etc/dashboard' directory.
   The listed folders can be imported into Grafana using the 'import_folder' command.

   This command is equivalent to the 'ls' command as follows:

   ls $APP_DIR/etc/dashboard

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

echo "Folders on local file system. Run 'import_folder' to import them into Grafana." 
for i in $FOLDERS; do
   echo "   $i"
done
echo ""
