#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Sync PadoGrid provided dashboards with Grafana

SYNOPSIS
   ./$EXECUTABLE [-readonly] [-label prometheus_label] [-?]

   -label prometheus_label
             The name of the Prometheus label to apply the cluster list filter. This
             label is typically introduced by Prometheus. For example, you can assign a
             list of target endpoints under the '$DEFAULT_LABEL' label as shown in the EXAMPLES
             section below. For Kubernetes, the 'namespace' label may be more approriate
             since all the members of a Hazelcast cluster start in the same namespace.
             Default: $DEFAULT_LABEL

DESCRIPTION
   This command replaces the PadoGrid provided folders in the 'etc/dashboards'
   directory with the respective Grafana folders. It executes the following
   in sequence.

   1. Export PadoGrid provided folders from Grafana to the 'export' directory.
   2. Create templates from the exported dashboards.
   3. Prepare the templates with Grafana variables.
   4. Delete all the PadoGrid provided folders from Grafana.
   5. Re-import the synced templates to Grafana.

OPTIONS
   -readonly
           If specified, then the dashboards are for read only. Default: editable

DEFAULT
   ./$EXECUTABLE

SEE ALSO
   padogrid_import_folders(1), padogrid_export_folders(1)

EOF
exit
fi

# Export all and create templates
for FOLDER in $PADOGRID_FOLDERS; do
   ./export_folder -folder $FOLDER
done
./export_to_template
for FOLDER in $PADOGRID_FOLDERS; do
   ./copy_template_to_etc -folder $FOLDER
done

# Update PadoGrid folders
if [ "$READONLY_SPECIFIED" == "true" ]; then
   ./update_cluster_templating_padogrid -label $LABEL -readonly
else
   ./update_cluster_templating_padogrid -label $LABEL
fi

# Delete PadoGrid folders in Grafana
for FOLDER in $PADOGRID_FOLDERS; do
   echo "Deleting $FOLDER..."
   ./delete_folder -folder $FOLDER
done

# Re-import PadoGrid folders in Grafana
for FOLDER in $PADOGRID_FOLDERS; do
   echo "Importing $FOLDER..."
   ./import_folder -folder $FOLDER
done
