#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2024 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Sync PadoGrid provided dashboards with Grafana

SYNOPSIS
   ./$EXECUTABLE [-editable] [-label $ALLOWED_LABELS_HELP] [-?]

   -label $ALLOWED_LABELS_HELP
             The name of the Prometheus label to apply the cluster list filter. This
             label is typically introduced by Prometheus. For example, you can assign a
             list of target endpoints under the '$DEFAULT_LABEL' label as shown in the EXAMPLES
             section below. For Kubernetes, the 'namespace' label may be more approriate
             since all the members of a cluster start in the same namespace.
             Default: $DEFAULT_LABEL

DESCRIPTION
   Use this command if you have modified the dashboards in the browser and
   wish to apply the changes to the dashboards in the file system.

   This command replaces the PadoGrid provided folders in the 'etc/dashboards'
   directory with the respective Grafana folders. It performs the following
   in sequence.

   1. Export PadoGrid provided folders from Grafana to the 'export' directory.
   2. Create templates from the exported dashboards.
   3. Prepare the templates with Grafana variables.
   4. Delete all the PadoGrid provided folders from Grafana.
   5. Re-import the synced templates to Grafana.

OPTIONS
   -editable
           If specified, then the dashboards are editable. Default: read-only

DEFAULT
   ./$EXECUTABLE

SEE ALSO
   padogrid_import_folders(1), padogrid_export_folders(1)

EOF
exit
fi

if [[ "$ALLOWED_LABELS_HELP" != *"$LABEL"* ]]; then
   echo -e >&2 "${CError}ERROR:${CNone} Invalid label [$LABEL]. Allowed labels are $ALLOWED_LABELS_HELP. Command aborted."
   exit 1
fi

# Export all and create templates
for FOLDER in $PADOGRID_FOLDERS; do
   ./export_folder -folder $FOLDER
done
./export_to_template
for FOLDER in $PADOGRID_FOLDERS; do
   ./copy_template_to_etc -folder $FOLDER
done

# Update PadoGrid folders
if [ "$EDITABLE" == "true" ]; then
   ./padogrid_update_cluster_templating -label $LABEL -editable
else
   ./padogrid_update_cluster_templating -label $LABEL
fi

# Delete PadoGrid folders in Grafana
for FOLDER in $PADOGRID_FOLDERS; do
   echo "Deleting $FOLDER..."
   ./delete_folder -folder $FOLDER
done

# Re-import PadoGrid folders in Grafana
for FOLDER in $PADOGRID_FOLDERS; do
   echo "Importing $FOLDER..."
   ./import_folder -folder $FOLDER
done
