#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Export PadoGrid provided dashboards from Grafana

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   This command exports the PadoGrid provided folders from Grafana and
   creates the respective templates in the 'etc/dashboards' directory.

DEFAULT
   ./$EXECUTABLE

SEE ALSO
   padogrid_import_folders(1), padogrid_sync_folders(1)

EOF
exit
fi

# Export all and create templates
for FOLDER in $PADOGRID_FOLDERS; do
   ./export_folder -folder $FOLDER
done
./export_to_template
for FOLDER in $PADOGRID_FOLDERS; do
   ./copy_template_to_etc -folder $FOLDER
done
