#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Export PadoGrid dashboards, create templates, update variables, and re-import to Grafana

SYNOPSIS
   ./$EXECUTABLE [-readonly] [-label prometheus_label] [-clusters cluster_list] [-?]

   -label prometheus_label
             The name of the Prometheus label to apply the cluster list filter. This
             label is typically introduced by Prometheus. For example, you can assign a
             list of target endpoints under the '$DEFAULT_LABEL' label as shown in the EXAMPLES
             section below. For Kubernetes, the 'namespace' label may be more approriate
             since all the members of a Hazelcast cluster start in the same namespace.
             Default: $DEFAULT_LABEL

   -clusters cluster_list
             A comma-separated list of cluster names. If Prometheus is locally launched, then
             the cluster names must match the 'job_name' values in the Prometheus configuration
             file. Default: $DEFAULT_CLUSTERS

DESCRIPTION
   Exports PadoGrid dashboards, create templates, update variables, and re-import to Grafana.

OPTIONS
   -readonly
           If specified, then the dashboards are for read only. Default: editable

DEFAULT
   ./$EXECUTABLE

SEE ALSO
   export_folder(1), copy_template_to_etc(1), update_cluster_templating_padogrid(1),
   delete_folder(1), import_folder(1)

EOF
exit
fi

# Export all and create templates
./export_folder -folder Hazelcast
./export_folder -folder HazelcastDual
./export_folder -folder HazelcastAll
./export_to_template
./copy_template_to_etc -folder Hazelcast
./copy_template_to_etc -folder HazelcastDual
./copy_template_to_etc -folder HazelcastAll

# Update PadoGrid folders
if [ "$READONLY_SPECIFIED" == "true" ]; then
   ./update_cluster_templating_padogrid -label $LABEL -clusters $CLUSTERS -readonly
else
   ./update_cluster_templating_padogrid -label $LABEL -clusters $CLUSTERS
fi

# Delete PadoGrid folders in Grafana
echo "Deleting Hazelcast..."
./delete_folder -folder Hazelcast
echo "Deleting HazelcastDual..."
./delete_folder -folder HazelcastDual
echo "Deleting HazelcastAll..."
./delete_folder -folder HazelcastAll

# Re-import PadoGrid folders in Grafana
./import_folder -folder Hazelcast
./import_folder -folder HazelcastDual
./import_folder -folder HazelcastAll
