#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Display Prometheus status

SYNOPSIS
   ./$EXECUTABLE [-all] [-?]

DESCRIPTION
   Displays Prometheus status.

OPTIONS
   -all
             Displays PIDs of all Prometheus instances"

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

# Exit if config file does not exist
if [ ! -f "$PROMETHEUS_CONFIG_FILE" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Prometheus configuration file not found. Command aborted."
   echo >&2 "       $PROMETHEUS_CONFIG_FILE"
   exit 1
fi

if [ "$ALL" == "true" ]; then
   RWE_PATHS=$(getAllPrometheusRwePaths)
   if [ "$RWE_PATHS" == "" ]; then
      echo "Prometheus instances not found."
   else
      count=0
      echo ""
      for i in $RWE_PATHS; do
         if [ $count -eq 0 ]; then
            echo "        PID: $i"
            count=1
         else
            echo "   RWE Path: $i"
            echo -e "     Status: ${CGo}Running${CNone}"
            echo ""
            count=0
         fi
      done
   fi
else
   echo -e "      URL: ${CUrl}$PROMETHEUS_URL${CNone}"
   PID=$(getPrometheusPid "$PROMETHEUS_CONFIG_FILE")
   if [ "$PID" != "" ]; then
      echo "      PID: $PID"
      echo "      LOG: $PROMETHEUS_LOG_FILE"
      echo -e "   Status: ${CGo}Running${CNone}"
   else
      echo "      LOG: $PROMETHEUS_LOG_FILE"
      echo -e "   Status: ${CRed}Down${CNone}"
   fi
fi
