#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2022 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Displays Grafana status

SYNOPSIS
   ./$EXECUTABLE [-all] [-?]

DESCRIPTION
   Displays Grafana status.

OPTIONS
   -all
             Displays PIDs of all Prometheus instances

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

if [ "$ALL" == "true" ]; then
   PIDs="$(getAllGrafanaPids)"
   if [ "$PIDs" != "" ]; then
      echo "All Grafana instances."
      echo "   PIDs: $PIDs"
   else
      echo "Grafana instances not found."
   fi
else
   PID=$(getGrafanaPid "$GRAFANA_CONFIG_FILE")
   if [ "$PID" != "" ]; then
      echo "Grafana running."
      echo "   PID: $PID"
   else
      echo "Grafana not running."
   fi
   echo "   LOG: $LOG_DIR/grafana.log"
fi
