#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   ./$EXECUTABLE - Start Grafana

SYNOPSIS
   ./$EXECUTABLE [-?]

DESCRIPTION
   Starts Grafana with the following configuration and log files.

      $GRAFANA_CONFIG_FILE"
      $GRAFANA_LOG_FILE"

   Grafana is started in the following working directory.

      $RUN_DIR"

   Grafana's home path, '-homepath', is

      $GRAFANA_HOME

NOTES
   Grafana downloaded using 'install_padogrid' on Alpine Linux may not work due to
   the glibc dependency. In that case, you can install the Grafana package using the
   'apk add' command as follows.

       sudo apk add grafana

DEFAULT
   ./$EXECUTABLE

EOF
exit
fi

# Exit if Grafana is already running
PID=$(getGrafanaPid "$GRAFANA_CONFIG_FILE")
if [ "$PID" != "" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Grafana already running: [PID=$PID]. Command aborted."
   exit 1
fi

# Launch Grafana in $RUN_DIR
RUN_DIR="$APP_DIR/run/grafana"
if [ ! -d "$RUN_DIR" ]; then
   mkdir -p "$RUN_DIR"
fi
pushd $RUN_DIR > /dev/null 2>&1
PID=""
if [ "$GRAFANA_HOME" != "" ]; then
   $GRAFANA_HOME/bin/grafana-server $GRAFANA_OPTS -homepath $GRAFANA_HOME web > $GRAFANA_LOG_FILE 2>&1 &
   PID=$(getGrafanaPid "$GRAFANA_CONFIG_FILE")
fi
if [ "$PID" == "" ]; then
   if [ "$(which grafana 2> /dev/null)" != "" ]; then
      grafana server $GRAFANA_OPTS -homepath $GRAFANA_HOME web > $GRAFANA_LOG_FILE 2>&1 &
      PID=$!
   else
      popd > /dev/null 2>&1
      echo -e >&2 "${CError}ERROR:${CNone} Grafana not installed. Command aborted."
      exit 1
   fi
fi
popd > /dev/null 2>&1

# Delay a bit to see if Grafana starts
sleep 2
ADDRESS_IN_USE="$([ "$(grep 'bind: address already in use' $GRAFANA_LOG_FILE)" != "" ] && echo "true" || echo "false")"
if [ "$ADDRESS_IN_USE" == "true" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Address already in use. See log for details. Command aborted."
   echo "   LOG: $GRAFANA_LOG_FILE"
   exit 1
fi
PID=$(getGrafanaPid "$GRAFANA_CONFIG_FILE")
if [ "$PID" == "" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Grafana not started. See log file for details. Command aborted."
   echo "   LOG: $GRAFANA_LOG_FILE"
   exit 1
fi

echo "Grafana started."
echo "   PID: $PID"
echo "   LOG: $LOG_DIR/grafana.log"
