#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-folder <folder-name>] [-all] [-?]"
   echo ""
   echo "   Exports the specified folder's dashboards to the following directory: "
   echo "      $EXPORT_DASHBOARD_DIR"
   echo ""
   echo "     <folder-name>      Folder name."
   echo "     -all               Export all folders."
   echo ""
   echo "Default: ./$EXECUTABLE -folder $DEFAULT_FOLDER"
   echo ""
   exit
fi

if [ "$FOLDER" != "" ]; then
   FOLDERS=$FOLDER
elif [ "$ALL" != "true" ]; then
   FOLDERS=$DEFAULT_FOLDER
else
   # All folders in Grafana
   TMP_FILE=$TMP_DIR/folders.json
   ./get_folders > $TMP_FILE
   # Cygwin path conversion
   if [[ ${OS_NAME} == CYGWIN* ]]; then
      TMP_FILE="$(cygpath -wp "$TMP_FILE")"
   fi
   ARRAY_LEN=`jq '.|length' $TMP_FILE`
   let LAST_INDEX=ARRAY_LEN-1
   for i in $(seq 0 $LAST_INDEX); do
      __TITLE=`jq '.['$i'].title' $TMP_FILE`
      __TITLE=`trimDoubleQuotes $__TITLE`
      FOLDERS="$FOLDERS $__TITLE"
   done
fi

if [ "$FOLDERS" == "" ]; then
   echo "Folders not found in Grafana. Command aboarded."
   exit 1
fi
   
TMP_FILE=$TMP_DIR/dashboards.json
for FOLDER in $FOLDERS; do
   # Get all dashboards belonging to each folder
   ./get_dashboards -folder $FOLDER > $TMP_FILE

   # Create the dashboard directory
   EXPORT_FOLDER_DIR=$EXPORT_DASHBOARD_DIR/$FOLDER
   if [ ! -d $EXPORT_FOLDER_DIR ]; then
      mkdir -p $EXPORT_FOLDER_DIR
   fi

   # Export each dashboard in the folder
   # Cygwin path conversion
   if [[ ${OS_NAME} == CYGWIN* ]]; then
      TMP_FILE="$(cygpath -wp "$TMP_FILE")"
   fi
   ARRAY_LEN=`jq '.|length' $TMP_FILE`
   let LAST_INDEX=ARRAY_LEN-1
   for i in $(seq 0 $LAST_INDEX); do
      __UID=`jq '.['$i'].uid' $TMP_FILE`
      __UID=`trimDoubleQuotes "$__UID"`
      __TITLE=`jq '.['$i'].title' $TMP_FILE`
      __TITLE=`trimDoubleQuotes "$__TITLE"`
      curl -sS $GRAFANA_URL/api/dashboards/uid/$__UID | jq > "$EXPORT_FOLDER_DIR/${__TITLE}.json" 
   done;
   echo "Exported: $EXPORT_FOLDER_DIR"
done
