#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-?]"
   echo ""
   echo "  Displays all folders found in Grafana."
   echo ""
   echo "Default: ./$EXECUTABLE"
   echo ""
   exit
fi

curl -sS $GRAFANA_URL/api/folders | jq
