#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-folder <folder-name>] [-?]"
   echo ""
   echo "   Displays the specified folder information."
   echo ""
   echo "Default: ./$EXECUTABLE -folder $DEFAULT_FOLDER"
   echo ""
   exit
fi

if [ "$FOLDER" == "" ]; then
   FOLDER=$DEFAULT_FOLDER
fi

__UID=`./get_folder_uid -folder $FOLDER`

curl -sS $GRAFANA_URL/api/folders/$__UID | jq
