#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-folder <folder-name>] [-?]"
   echo ""
   echo "   Displays all dashboards found in the specfied Grafana folder."
   echo ""
   echo "Default: ./$EXECUTABLE -folder $DEFAULT_FOLDER"
   echo ""
   exit
fi

if [ "$FOLDER" == "" ]; then
   FOLDERS=$DEFAULT_FOLDER
fi

__ID=`./get_folder_id -folder $FOLDER`
if [ "$__ID" == "" ]; then
   echo "ERROR: Folder not found [$FOLDER]. Command aborted."
   exit 1
fi

curl -sS "$GRAFANA_URL/api/search?folderIds=$__ID" |jq
