#!/usr/bin/env bash 

# A place holder for auto-completion.
# Use the cd_rwe function instead. See .utilenv.sh

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   $EXECUTABLE -?
fi
