#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-workspace -all -path -java -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Change PadoGrid and/or Java versions

SYNOPSIS
   $EXECUTABLE [-workspace workspace_name] [-all] [-path padogrid_home_path] [-java java_home_path] [-?]

DESCRIPTION
   Changes PadoGrid and/or Java versions of the current workspace or the entire RWE. If no options are 
   specified then it changes the current workspace's version.

   The changes are made in the 'setenv.sh' files found in the RWE and workspace directories. Note that 
   you cannot change the product path using this command. To change the product path, set PRODUCT_HOME
   in the 'setenv.sh' files found in the workspace and RWE directories.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
         RWE: $PADOGRID_WORKSPACES_HOME/setenv.sh
   Workspace: $PADOGRID_WORKSPACE/setenv.sh
EOF
fi
cat <<EOF

OPTIONS
   -workspace workspace_name
             Workspace name.

   -all
             If specified then applies the specified version to all workspaces in the current RWE.
             If '-workspace' is specified then this option is ignored and has no effect.

   -path padogrid_home_path 
             PadoGrid home directory path.

   -java java_home_path
             JAVA_HOME path.
       
SEE ALSO
   create_rwe(1), create_workspace(1)

EOF
   exit
fi

if [ "$PATH_ARG" == "" ] && [ "$JAVA_HOME_ARG" == "" ]; then
   echo >&2 "ERROR: Must specify '-path' and/or '-java'. '$EXECUTABLE -?' to see usage. Command aborted."
   exit 1
fi

if [ "$PATH_ARG" != "" ]; then
   if [ ! -d "$PATH_ARG" ]; then
      echo >&2 "ERROR: Invalid path specified [$PATH_ARG]."
      echo >&2 "       Command aborted."
      exit 1
   fi
   PADOGRID_HOME_PATH="$(cd "$(dirname "$PATH_ARG")"; pwd)/$(basename "$PATH_ARG")"
fi

if [ "$WORKSPACE_ARG" != "" ]; then
   WORKSPACE_DIR="$PADOGRID_WORKSPACES_HOME/$WORKSPACE_ARG"
else
   WORKSPACE_DIR="$PADOGRID_WORKSPACE"
fi
if [ ! -d "$WORKSPACE_DIR" ]; then
   echo >&2 "ERROR: Specified workspace does not exist [$WORKSPACE_ARG]. Command aborted."
   exit 1
fi

if [ "$JAVA_HOME_ARG" != "" ]; then
   if [ ! -d "$JAVA_HOME_ARG" ]; then
      echo >&2 "ERROR: Specified Java home path does not exist [$JAVA_HOME_ARG]. Command aborted."
      exit 1
   fi
   JAVA_HOME_PATH="$(cd "$(dirname "$JAVA_HOME_ARG")"; pwd)/$(basename "$JAVA_HOME_ARG")"
fi

if [ -d "$PADOGRID_HOME_PATH" ]; then
   if [ ! -f "$PADOGRID_HOME_PATH/bin_sh/create_rwe" ]; then
      echo >&2 "ERROR: Invalid PadoGrid home path [$PATH_ARG]."
      echo >&2 "       Specified path does not contain PadoGrid files. Command aborted."
      exit 1
   fi
fi
if [ -d "$JAVA_HOME_PATH" ]; then
   if [ ! -f "$JAVA_HOME_PATH/bin/java" ]; then
      echo >&2 "ERROR: Invalid Java home path [$JAVA_HOME_ARG]."
      echo >&2 "       Specified path does not contain Java files. Command aborted."
      exit 1
   fi
fi

if [ "$ALL" == "true" ]; then
   for i in $(list_workspaces); do
     if [ "$PADOGRID_HOME_PATH" != "" ]; then
         sed -i${__SED_BACKUP} -e 's|export PADOGRID_HOME=.*$|export PADOGRID_HOME='\"${PADOGRID_HOME_PATH}\"'|' \
             $PADOGRID_WORKSPACES_HOME/$i/setenv.sh
      fi
      if [ "$JAVA_HOME_PATH" != "" ]; then
         sed -i${__SED_BACKUP} -e 's|export JAVA_HOME=.*$|export JAVA_HOME='\"${JAVA_HOME_PATH}\"'|' \
             $PADOGRID_WORKSPACES_HOME/$i/setenv.sh
      fi
      if [ -f $PADOGRID_WORKSPACES_HOME/$i/setenv.sh0 ]; then
         rm $PADOGRID_WORKSPACES_HOME/$i/setenv.sh0
      fi
      echo "Modified: $PADOGRID_WORKSPACES_HOME/$i/setenv.sh"
   done

   # rwe
   if [ "$PADOGRID_HOME_PATH" != "" ]; then
      sed -i${__SED_BACKUP} -e 's|export PADOGRID_HOME=.*$|export PADOGRID_HOME='\"${PADOGRID_HOME_PATH}\"'|' \
          $PADOGRID_WORKSPACES_HOME/setenv.sh
   fi
   if [ "$JAVA_HOME_PATH" != "" ]; then
      sed -i${__SED_BACKUP} -e 's|export JAVA_HOME=.*$|export JAVA_HOME='\"${JAVA_HOME_PATH}\"'|' \
          $PADOGRID_WORKSPACES_HOME/setenv.sh
   fi
   if [ -f $PADOGRID_WORKSPACES_HOME/setenv.sh0 ]; then
      rm $PADOGRID_WORKSPACES_HOME/setenv.sh0
   fi
   echo "Modified: $PADOGRID_WORKSPACES_HOME/setenv.sh"
else
  if [ "$PADOGRID_HOME_PATH" != "" ]; then
     sed -i${__SED_BACKUP} -e 's|export PADOGRID_HOME=.*$|export PADOGRID_HOME='\"${PADOGRID_HOME_PATH}\"'|' \
         $WORKSPACE_DIR/setenv.sh
  fi
  if [ "$JAVA_HOME_PATH" != "" ]; then
     sed -i${__SED_BACKUP} -e 's|export JAVA_HOME=.*$|export JAVA_HOME='\"${JAVA_HOME_PATH}\"'|' \
         $WORKSPACE_DIR/setenv.sh
  fi
  if [ -f $WORKSPACE_DIR/setenv.sh0 ]; then
     rm $WORKSPACE_DIR/setenv.sh0
  fi
  echo "Modified: $WORKSPACE_DIR/setenv.sh"
fi
