#!/usr/bin/env bash 

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - List all the apps in the current padogrid workspace

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Lists all the apps in the current workspace.

DEFAULT
   $EXECUTABLE

SEE ALSO
EOF
   printSeeAlsoList "*app*" $EXECUTABLE
   exit
fi

if [ "$PADOGRID_WORKSPACES_HOME" == "" ]; then
   >&2 echo "ERROR: Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
   >&2 echo "       Command aborted."
   exit 1
fi
if [ ! -d "$PADOGRID_WORKSPACES_HOME" ]; then
   >&2 echo "ERROR: Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
   >&2 echo "       Command aborted."
   exit 1
fi

if [ "$PADOGRID_WORKSPACE" == "" ]; then
   >&2 echo "ERROR: Workspace undefined. Please first create a workspace."
   >&2 echo "       Command aborted."
   exit 1
fi
if [ ! -d "$PADOGRID_WORKSPACE" ]; then
   >&2 echo "ERROR: Invalid workspace. Directory does not exist."
   >&2 echo "       $PADOGRID_WORKSPACE"
   >&2 echo "       Command aborted."
   exit 1
fi

ls $PADOGRID_WORKSPACE/apps
