#!/usr/bin/env bash 

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - List all the workspaces in the current padogrid workspaces environment

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Lists all the workspaces in the current workspace environemt. 

DEFAULT
   $EXECUTABLE

SEE ALSO
EOF
   printSeeAlsoList "*workspace*" $EXECUTABLE
   exit
fi

if [ "$PADOGRID_WORKSPACES_HOME" == "" ]; then
   echo "ERROR: Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
   echo "       Command aborted."
   exit 1
fi
if [ ! -d "$PADOGRID_WORKSPACES_HOME" ]; then
   echo "ERROR: Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
   echo "       Command aborted."
   exit 1
fi

WORKSPACES=`ls $PADOGRID_WORKSPACES_HOME`
removeTokens "$WORKSPACES" "initenv.sh setenv.sh"
