#!/usr/bin/env bash 

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-rwe -workspace -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - List all the Docker clusters in the specified workspace

SYNOPSIS
   $EXECUTABLE [-rwe rwe_name] [-workspace workspace_name] [-?]

DESCRIPTION
   Lists all the Docker clusters in the specified workspace.

OPTIONS
   -rwe rwe_name
             RWE name. If not specified, then the current RWE is used. If specified, then 
             the '-workspace' option must be specified also.

   -workspace workspace_name
             Workspace name. If not specified, then it displays docker clusters in the current workspace.

DEFAULT
   $EXECUTABLE

SEE ALSO
EOF
   printSeeAlsoList "*docker*" $EXECUTABLE
   exit
fi

if [ "$PADOGRID_WORKSPACES_HOME" == "" ]; then
   >&2 echo "ERROR: Workspaces not initialized. Please first run 'create_rwe' to initialize workspaces."
   >&2 echo "       Command aborted."
   exit 1
fi
if [ ! -d "$PADOGRID_WORKSPACES_HOME" ]; then
   >&2 echo "ERROR: Invalid workspaces. Please run 'create_rwe' to initialize workspaces."
   >&2 echo "       Command aborted."
   exit 1
fi

RWE_NAME=$(basename "$PADOGRID_WORKSPACES_HOME")
if [ "$RWE_ARG" != "" ]; then
   if [ "$WORKSPACE_ARG" == "" ]; then
      if [ "$RWE_ARG" != "$RWE_NAME" ]; then
         echo >&2 "ERROR: Specified RWE is not the current RWE. Use '-workspace' to specify the workspace."
         echo >&2 "       Command aborted."
         exit 1
      fi
   fi
fi

# rwe path
if [ "$RWE_ARG" == "" ]; then
   __RWE_PATH="$PADOGRID_WORKSPACES_HOME"
else
   RWE_PARENT_DIR="$(dirname "$PADOGRID_WORKSPACES_HOME")"
   __RWE_PATH="$RWE_PARENT_DIR/$RWE_ARG"
   RWE_NAME=$RWE_ARG
   if [ ! -d "$__RWE_PATH" ]; then
      echo >&2 "ERROR: Specified RWE does not exist [$RWE_ARG]. Command aborted."
      exit 1
   elif [ "$(isValidRwe $RWE_ARG)" == "false" ]; then
      echo >&2 "ERROR: Specified RWE is not valid [$RWE_ARG]. Command aborted."
      exit 1
   fi
fi
# workspace path
if [ "$WORKSPACE_ARG" == "" ]; then
   WORKSPACE_NAME=$(basename $PADOGRID_WORKSPACE)
else
   WORKSPACE_NAME="$WORKSPACE_ARG"
fi
__WORKSPACE_PATH="$__RWE_PATH/$WORKSPACE_NAME"

if [ "$__WORKSPACE_PATH" == "" ]; then
   >&2 echo "ERROR: Workspace undefined. Please first create a workspace."
   >&2 echo "       Command aborted."
   exit 1
fi
if [ ! -d "$__WORKSPACE_PATH" ]; then
   >&2 echo "ERROR: Invalid workspace. Directory does not exist."
   >&2 echo "       $__WORKSPACE_PATH"
   >&2 echo "       Command aborted."
   exit 1
fi

if [ -d "$__WORKSPACE_PATH/docker" ]; then
   ls $__WORKSPACE_PATH/docker
fi
