#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $PADOGRID_HOME/$PRODUCT/bin_sh/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-all -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Display the present (current) padogrid workspace information 

SYNOPSIS
   $EXECUTABLE [-all] [-?]

DESCRIPTION
   Displays the name of the present (current) working workspace. If the '-all' option
   is present then it displays current environment details.

OPTIONS
   -all
             If specified then it displays the current environment details.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "*workspace*" $EXECUTABLE
   exit
fi

if [ "$PADOGRID_WORKSPACE" != "" ]; then
   WORKSPACE="`basename $PADOGRID_WORKSPACE`"
else
   WORKSPACE=""
fi

if [ "$WORKSPACE" == "" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Workspace undefined. The current workspace is undefined. Command aborted."
   exit 1
fi

if [ "$ALL" = "true" ]; then
   echo "       Current Workspace: $WORKSPACE"
   echo "      PADOGRID_WORKSPACE: $PADOGRID_WORKSPACE"
   echo "PADOGRID_WORKSPACES_HOME: $PADOGRID_WORKSPACES_HOME"
   echo "           PADOGRID_HOME: $PADOGRID_HOME"
else
   echo "$WORKSPACE"
fi
