#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $PADOGRID_HOME/$PRODUCT/bin_sh/.addonenv.sh 

EXECUTABLE="`basename $0`"

__options()
{
   echo "-pod -all -long -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Display the pod status in the current workspace

SYNOPSIS
   $EXECUTABLE [-pod pod_name] [-all] [-long] [-?]

DESCRIPTION
   Displays pod status.

OPTIONS
   -pod pod_name
             Pod name

   -long
             Display detailed information.

   -all
             Display all pods.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -pod $POD

FILES
   $PADOGRID_WORKSPACE/pods
             The current workspace pods directory.

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "*pod*" $EXECUTABLE
   exit
fi

POD_TYPE=`getPodProperty "pod.type" "local"`
OS_ENV=`getOsEnv`

# Source in the pod setenv.sh file
HOST_PRIVATE_IP=""
if [ "$OS_ENV" == "gg" ]; then
   __SETENV_FILE="/vagrant/bin_sh/setenv.sh"
else
   __SETENV_FILE="$PODS_DIR/$POD/bin_sh/setenv.sh"
fi
if [ -f "$__SETENV_FILE" ]; then
   . "$__SETENV_FILE"
fi

# Display short status of a pod.
function displayPodShort()
{
   POD_DIR=$PODS_DIR/$POD
   POD_TYPE=`getPodProperty "pod.type" "local"`
   NODE_PRIMARY_COUNT=1
   NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
   NODE_NAME_PREFIX=`getPodProperty "node.name.prefix"`
   NODE_COUNT=`getPodProperty "node.count"`
   POD_RUNNING=`isPodRunning $POD`

   echo ""
   echo "   WORKSPACE: $PADOGRID_WORKSPACE"
   echo "         POD: $POD"
   echo "    POD_TYPE: $POD_TYPE"
   if [ "$POD" != "local" ]; then
      POD_CLUSTERS=""
      for CLUSTER in $(list_clusters); do
         CLUSTER_DIR="$PADOGRID_WORKSPACE/clusters/$CLUSTER"
         CLUSTER_POD_NAME=$(getClusterProperty "pod.name")
         #CLUSTER_POD_TYPE=$(getClusterProperty "pod.type")
         if [ "$CLUSTER_POD_NAME" == "$POD" ]; then
            POD_CLUSTERS="$CLUSTER $POD_CLUSTERS"
         fi
      done
      POD_CLUSTERS="$(echo "$POD_CLUSTERS" | sort -u)"
      echo "POD_CLUSTERS: $POD_CLUSTERS "
   fi
   if [[ $OS_ENV == *g ]] && [ "$POD" != "local" ]; then
      echo "POD State: Unknown"
   elif [ "$POD_RUNNING" == "true" ]; then
      echo -e "   POD State: ${CLightGreen}Running${CNone}"
   else
      echo -e "   POD State: ${CLightRed}Down${CNone}"
   fi
   echo ""
}

function displayPodLong()
{
   POD_DIR=$PODS_DIR/$POD
   POD_TYPE=`getPodProperty "pod.type" "local"`
   NODE_PRIMARY_COUNT=1
   NODE_NAME_PRIMARY=`getPodProperty "node.name.primary"`
   NODE_NAME_PREFIX=`getPodProperty "node.name.prefix"`
   NODE_COUNT=`getPodProperty "node.count"`
   POD_RUNNING=`isPodRunning $POD`

   echo ""
   echo "         WORKSPACE: $PADOGRID_WORKSPACE"
   echo "               POD: $POD"
   echo "          POD_TYPE: $POD_TYPE"
   if [ "$POD" != "local" ]; then
      POD_CLUSTERS=""
      for CLUSTER in $(list_clusters); do
         CLUSTER_DIR="$PADOGRID_WORKSPACE/clusters/$CLUSTER"
         CLUSTER_POD_NAME=$(getClusterProperty "pod.name")
         #CLUSTER_POD_TYPE=$(getClusterProperty "pod.type")
         if [ "$CLUSTER_POD_NAME" == "$POD" ]; then
            POD_CLUSTERS="$CLUSTER $POD_CLUSTERS"
         fi
      done
      POD_CLUSTERS="$(echo "$POD_CLUSTERS" | sort -u)"
      echo "      POD_CLUSTERS: $POD_CLUSTERS"
   fi
   if [[ $OS_ENV == *g ]] && [ "$POD" != "local" ]; then
      echo "         POD State: Unknown"
   elif [ "$POD_RUNNING" == "true" ]; then
      echo -e "         POD State: ${CLightGreen}Running${CNone}"
   else
      echo -e "         POD State: ${CLightRed}Down${CNone}"
   fi

   if [ "$POD" != "local" ]; then
      echo "   HOST_PRIVATE_IP: $HOST_PRIVATE_IP"
      echo " NODE_NAME_PRIMARY: $NODE_NAME_PRIMARY"
      echo "  NODE_NAME_PREFIX: $NODE_NAME_PREFIX"
      echo "NODE_PRIMARY_COUNT: $NODE_PRIMARY_COUNT"
      echo "   Data NODE_COUNT: $NODE_COUNT"
      echo "           POD_DIR: $POD_DIR"
   fi
   echo ""
}

if [ "$ALL" == "true" ]; then

   # Display all pods

   PODS=`getPods`

   if [ "$PODS" == "" ]; then
      echo "No pods found. To create one, execute the 'create_pod' command."
      exit 0
   fi

   echo "----------------------------------------------------------------"
   echo "Pods: $PODS"
   echo "----------------------------------------------------------------"
   echo ""
   if [ "$LONG" == "true" ]; then
      # Long display -all
      for POD in ${PODS}; do
         displayPodLong
      done
   else
      # Short display -all
      for POD in ${PODS}; do
         displayPodShort
      done
   fi
   echo "----------------------------------------------------------------"
   echo "Pods: $PODS"
   echo "----------------------------------------------------------------"

else

   # Display single cluster status
   if [ ! -d $POD_DIR ] && [ "${POD}" != "local" ]; then
      echo >&2 "ERROR: The specified pod does not exist: [$POD]. Command aborted."
      exit 1
   fi

   if [ "$LONG" == "true" ]; then
      # Long display (single)
      displayPodLong
   else
      # Short display (single)
      displayPodShort
   fi
fi
