#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020,2021 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-port -all -full -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Display Jupyter Notebook server status

SYNOPSIS
   $EXECUTABLE [-port [port_number]] [-all | -full] [-?]

NOTES
   Jupyter commands are experimental and subject to change in future releases.

DESCRIPTION
   Displays Jupyter Notebook server status or log file(s) in the current RWE.
   If no options are specified, then it displays the server statuses. The '-full'
   and '-all' options are not allowed together. If port_number is not specified,
   then it defaults to 8888.

OPTIONS
   -port [port_number]
             Displays the log file of the specified port number that is opened by
             the corresponding server in the current RWE.  By default, it follows the
             tail part of the log, equivalent to 'tail -f'. To view the full log,
             specify the '-full' option, which is equivalent to 'less'.

             If port_number is not specified, then defaults to '8888'.

   -all
             Displays all active log files under the current RWE.

   -full
             If specified then displays the entire log file using 'less'; otherwise, displays
             the Jupyter Notebook server status.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "*jupyter* *vscode*" $EXECUTABLE
   exit
fi

if [ "$(which jupyter)" == "" ]; then
   echo >&2 -e "${CError}ERROR:${CNone} jupyter executable not found. Command aborted."
   exit 1
fi
if [ "$ALL" == "true" ] && [ "$FULL" == "true" ]; then 
   echo >&2 -e "${CLightRed}ERROR:${CNone} '-all' and '-full' cannot be specified together. Command aborted ."
   exit 1
fi

if [ "$PORT_SPECIFIED" == "true" ] || [ "$ALL" == "true" ] || [ "$FULL" == "true" ]; then
   if [ "$PORT_ARG" == "" ]; then
      PORT_NUMBER="8888"
   else
      PORT_NUMBER=$PORT_ARG
   fi
   RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
   JUPYTER_LOG_FILE=$HOME/.padogrid/workspaces/$RWE_NAME/jupyterlab-$PORT_NUMBER.log

   echo ""
   if [ "$ALL" == "true" ]; then
      echo -e "Showing log: ${CHighlight}All active server log files${CNone}"
   else
      echo -e "Showing log: ${CHighlight}$JUPYTER_LOG_FILE${CNone}"
   fi
   echo ""

   if [ "$ALL" == "true" ]; then
      LOG_FILES=""
      PORTS=$(getActiveJupyterPorts)
      for i in $PORTS; do
         LOG_FILES="$LOG_FILES $HOME/.padogrid/workspaces/$RWE_NAME/jupyterlab-$i.log"
      done
      tail -f $LOG_FILES
   elif [ "$FULL" == "true" ]; then
      less $JUPYTER_LOG_FILE
   else
      tail -f $JUPYTER_LOG_FILE
   fi
else
   TMP_FILE=/tmp/$EXECUTABLE.jupyter-list.txt
   jupyter lab list > $TMP_FILE
   echo ""
   cat $TMP_FILE 
   if [ $(cat $TMP_FILE | wc -l) -gt 1 ]; then
      echo ""
      echo "PadoGrid workspace dashboard(s):"
      while IFS= read -r line; do
         url=$(echo $line | grep http)
         if [ "$url" != "" ]; then
            header=$(echo $url | sed 's/::.*//')
            http=$(echo $header | sed 's/?token.*$//')
            if [[ "$header" == *"token"* ]]; then
               token=$(echo $header | sed 's/^.*token=//')
            else
               token=""
            fi
            workspaces=$(echo $url | sed 's/.*workspaces/workspaces/')
            url="${http}lab/$workspaces"
            if [ "$token" != "" ]; then
               url="$url/?token=$token"
            fi
            echo -e "- ${CUrl}$url${CNone}"
         fi
      done < $TMP_FILE
      unset IFS
      rm $TMP_FILE
      echo ""
   fi
fi
