#!/usr/bin/env bash 

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-workspace -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Display the specified padogrid workspace information

SYNOPSIS
   $EXECUTABLE [-workspace] [-?]

DESCRIPTION
   Displays the specified workspace information.

   Note that the product displayed is the default product configured for the workspace
   and does not necessarily represent the how the components in the workspace are
   configured. For example, the workspace may contain a cluster configured with the
   default product and yet another cluster with another product.

OPTIONS
   -workspace workspace_name
             Workspace name. If not specified, then it displays the current
             workspace information.

DEFAULT
   $EXECUTABLE

SEE ALSO
EOF
   printSeeAlsoList "*workspace*" $EXECUTABLE
   exit
fi

if [ "$WORKSPACE_ARG" == "" ]; then
   WORKSPACE_DIR=$PADOGRID_WORKSPACE
else
   WORKSPACE_DIR=$PADOGRID_WORKSPACES_HOME/$WORKSPACE_ARG
fi
if [ "$WORKSPACE_DIR" == "" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Workspace undefined. The current workspace is undefined. Command aborted."
   exit 1
fi

WORKSPACE=$(basename  "$WORKSPACE_DIR")
WORKSPACE_INFO=$(getWorkspaceInfoList $WORKSPACE)
RWE_NAME=$(basename "$PADOGRID_WORKSPACES_HOME")
SWITCH_WORKSPACE_COMMAND="switch_rwe $RWE_NAME $WORKSPACE"

if [ "$GROUP" == "" ]; then
   GROUP=$(getCurrentClusterGroup)
fi

echo ""
echo "Workspace:"
echo "   $WORKSPACE [$WORKSPACE_INFO]"
echo ""
echo "RWE Directory:"
echo "   $PADOGRID_WORKSPACES_HOME"
echo ""
echo "Workspace Directory:"
echo "   $WORKSPACE_DIR"
echo ""
echo "Workspace Type: "
if [ "$VM_ENABLED" == "true" ]; then
echo "   VM"
else
echo "   local"
fi
NODES="apps clusters docker groups k8s pods"
for NODE in $NODES; do
   ITEMS=$(getClusters "$NODE" $WORKSPACE_ARG)
   if [ "$ITEMS" != "" ]; then
      echo ""
      echo "$NODE"
      if [ "$NODE" == "clusters" ]; then
         showTree "$ITEMS" "$CLUSTER"
      elif [ "$NODE" == "groups" ]; then
         showTree "$ITEMS" "$GROUP"
      elif [ "$NODE" == "pods" ]; then
         showTree "$ITEMS" "$POD"
      else
         showTree "$ITEMS"
      fi
   fi
done
echo ""
echo "Switch Command:"
echo "   $SWITCH_WORKSPACE_COMMAND"
echo ""
