#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $PADOGRID_HOME/$PRODUCT/bin_sh/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-workspace -quiet -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$WORKSPACE_ARG" != "" ]; then
   WORKSPACE=$WORKSPACE_ARG
elif [ "$PADOGRID_WORKSPACE" != "" ]; then
   WORKSPACE="`basename $PADOGRID_WORKSPACE`"
else
   WORKSPACE=""
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Start all the clusters in the specified workspace

WARNING
   This command assumes that the clusters have properly been configured to prevent port conflicts.

SYNOPSIS
   $EXECUTABLE [-workspace workspace_name] [-quiet] [-?]

DESCRIPTION
   Starts all the clusters in the specified workspace by invoking 'start_cluster -all' for each cluster.

OPTIONS
   -workspace workspace_name
             Workspace name. If not specified, then starts the current workspace.

   -quiet
             Quiet mode. Supresses the interactive prompt.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -workspace $WORKSPACE

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "*workspace*" $EXECUTABLE
   exit
fi

if [ "$PADOGRID_WORKSPACE" == "" ]; then
   CURRENT_WORKSPACE=""
else
   CURRENT_WORKSPACE="`basename $PADOGRID_WORKSPACE`"
fi

if [ "$WORKSPACE" == "" ] && [ "$CURRENT_WORKSPACE" == "" ]; then
   echo -e >&2 "${CError}ERROR:${CNone} Workspace undefined. The current workspace is undefined. Command aborted."
   exit 1
fi

if [ "$QUIET" == "false" ]; then
   echo "Workspace: $WORKSPACE"
   echo "   This command starts all clusters in the workspace. Local clusters configured with the same"
   echo "   port numbers may not start properly. Make sure the clusters have been properly configured"
   echo "   to prevent port conflicts. To suppress this prompt, specify '-quiet'."
   echo "Do you want to continue?"
   echo "(Enter 'continue' + Enter to continue to start all clusters, other keys to abort.)"
   read INPUT
   if [ "$INPUT" != "continue" ]; then
      echo "Command aborted."
      exit
   fi
fi

CURRENT_DIR="`pwd`"
CURRENT_CLUSTER=$CLUSTER

__WORKSPACES=( $WORKSPACE )

let NUM_WORKSPACES=${#__WORKSPACES[@]};
for ((__i = 0; __i < $NUM_WORKSPACES; __i++)); do
   __WORKSPACE="${__WORKSPACES[$__i]}"
   if [ $NUM_WORKSPACES -eq 1 ]; then
      if [ "$__WORKSPACE" != "$CURRENT_WORKSPACE" ]; then
         switch_workspace $__WORKSPACE
      fi
   else
      switch_workspace $__WORKSPACE
   fi
   echo ""
   echo -e "${CLightGreen}Starting workspace $__WORKSPACE...${CNone}"
   for j in $PADOGRID_WORKSPACES_HOME/$__WORKSPACE/clusters/*; do
      CLUSTER="`basename $j`"
      echo ""
      echo -e "${CLightGreen}Starting cluster $CLUSTER...${CNone}"
      start_cluster -all -cluster $CLUSTER
   done
done
if [ "$WORKSPACE" != "$CURRENT_WORKSPACE" ]; then
   switch_workspace $CURRENT_WORKSPACE
   switch_cluster $CLUSTER
   cd $CURRENT_DIR
fi
