#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2024 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $PADOGRID_HOME/$PRODUCT/bin_sh/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-config -log -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

# The following line is required by help_padogrid. Do NOT remove!
# $EXECUTABLE - Start MQTT virtual clusters

# Set MQTT addon class path. This is to handle 'none' product.
if [[ "$CLASSPATH" != *"$PADOGRID_HOME/mosquitto/plugins"* ]]; then
   CLASSPATH="$PADOGRID_HOME/mosquitto/plugins/*:$PADOGRID_HOME/mosquitto/lib/*:$CLASSPATH"
fi

# Log files are kept in the user home directory
LOG_DIR=~/.padogrid/log
if [ ! -d "$LOG_DIR/paho" ]; then
   mkdir -p "$LOG_DIR/paho"
fi

LOG_CONFIG_FILE="$PADOGRID_HOME/mosquitto/etc/template-log4j2.properties"
PAHO_LOG_CONFIG_FILE="$PADOGRID_HOME/mosquitto/etc/paho-logging-$EXECUTABLE.properties"

if [ "$LOG_SPECIFIED" == "true" ] && [ "$LOG" != "" ]; then
   LOG_FILE=$LOG
else
   LOG_FILE=$LOG_DIR/$EXECUTABLE.log
fi

if [[ ${OS_NAME} == CYGWIN* ]]; then
   LOG_DIR="$(cygpath -wp "$LOG_DIR")"
   LOG_CONFIG_FILE="$(cygpath -wp "$LOG_CONFIG_FILE")"
   LOG_FILE="$(cygpath -wp "$LOG_FILE")"
   PAHO_LOG_CONFIG_FILE="$(cygpath -wp "$PAHO_LOG_CONFIG_FILE")"
   CLASSPATH="$(cygpath -wp "$CLASSPATH")"
fi
# Required by LOG4J_CONFIG_FILE
export LOG_FILE

# Application executable name. Useful for displaying usage.
JAVA_OPTS="$JAVA_OPTS -Dexecutable.name=$EXECUTABLE"

# Paho logging
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.config.file=$PAHO_LOG_CONFIG_FILE"

# Log properties for log4j2.
JAVA_OPTS="$JAVA_OPTS -Dlog4j.configurationFile=file:$LOG_CONFIG_FILE"
#JAVA_OPTS="$JAVA_OPTS -Dlog4j2.debug=true"

# To suppress warning jdk11: "FileLock may stop working in future versions of Java #507"
if [[ "$JAVA_VERSION" != "1.8"* ]]; then
   JAVA_OPTS="$JAVA_OPTS --add-opens=java.base/sun.nio.ch=ALL-UNNAMED"
fi

if [ "$HELP" != "true" ]; then
   echo "LOG_FILE: $LOG_FILE"
fi
"$JAVA" $JAVA_OPTS padogrid.mqtt.client.console.VirtualClusters "$@"

if [ "$HELP" == "true" ]; then
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "vc_*" $EXECUTABLE
fi
