#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2024 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $PADOGRID_HOME/$PRODUCT/bin_sh/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-cluster -vm -all -bg -simulate -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Execute the specified command in the specified VMs except this VM
                 by default in padogrid environment

SYNOPSIS
   $EXECUTABLE [-cluster cluster_name] [-vm comma_separated_hosts] [-all] [-bg] [-simulate] "commands" [-?]

   Executes the specified commands in all the workspace VMs defined by the VM_HOSTS
   environment variable in the workspace 'setenv.sh' file. To execute only in the
   cluster VMs, specify the cluster with the '-cluster' option. To execute in a select
   list of VMs, specify the VM list with the '-vm' option.

   The specified commands will not be executed on this VM (the VM from which '$EXECUTABLE'
   is executed). To include this VM, specify the '-all' option.

   Note that this command and all other commands that begin with the "vm_" preprefix are
   available only on VM workspaces.

   The '-vm' option overrides both the '-cluster' option and VM_HOSTS. The '-cluster' option
   overrides VM_HOSTS. 

OPTIONS
   -cluster cluster_name
             Cluster name.

   -vm comma_separated_hosts
             A comma separated list of VM hosts or addresses. If the list contains spaces
             then enclosed it in quotes.

   -all
             Execute the command on all VMs including this VM. If not specified
             then the command will not execute on this VM.

   -bg
             Requests ssh to go to background just before command execution. This option is
             analogous to '-f' in ssh. Specify this option to run the remote command in the
             background. Note that '&' is not required.

   -simulate
             Print the remote commands but do not execute.

   "commands"
             Remote commands separated by ';' or '&&'. Commands should be in double quotes.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -cluster $CLUSTER "commands"

FILES
   $PADOGRID_WORKSPACE/setenv.sh
             The current workspace configuration file.

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "vm_*" $EXECUTABLE
   exit
fi

# Available only on VM workspaces
if [ "$VM_ENABLED" != "true" ]; then
   echo "----------------------------------------------------------------"
   echo "WORKSPACE: $PADOGRID_WORKSPACE"
   echo "    ERROR: The workspace is not a VM workspace. Command aborted."
   echo "----------------------------------------------------------------"
   exit 1 
fi

# If the -vm option is specified then it overrides all other options
if [ "$VM_SPECIFIED" == "true" ]; then
   if [ "$VM_HOSTS_ARG" != "" ] && [ "${VM_HOSTS_ARG:0:1}" != "-" ]; then
      VM_HOSTS=$VM_HOSTS_ARG
   else
      echo "----------------------------------------------------------------"
      echo "WORKSPACE: $PADOGRID_WORKSPACE"
      echo >&2 "ERROR: Invalid value for -vm [$VM_HOSTS_ARG]. Command aborted."
      echo "----------------------------------------------------------------"
      exit 1
   fi
else
   # The -cluster option overrides VM_HOSTS
   if [ "$CLUSTER_SPECIFIED" == "true" ]; then
      if [ "`isClusterExist "$CLUSTER"`" == "false" ]; then 
         echo "----------------------------------------------------------------"
         echo "WORKSPACE: $PADOGRID_WORKSPACE"
         echo >&2 "ERROR: Cluster does not exist [$CLUSTER]. Command aborted."
         echo "----------------------------------------------------------------"
         exit 1
      fi
   fi
   VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
   if [ "$VM_ENABLED" == "false" ]; then
      echo "----------------------------------------------------------------"
      echo "WORKSPACE: $PADOGRID_WORKSPACE"
      echo >&2 "ERROR: Not a VM cluster [$CLUSTER]. To enable VMs, set the 'vm.enabled' property"
      echo >&2 "       in the 'etc/cluster.properties' file."
      echo "----------------------------------------------------------------"
      exit 1
   fi
   VM_HOSTS=`getClusterProperty "vm.hosts"`
   if [ "$VM_HOSTS" == "" ]; then
      if [ "$VM_HOSTS" == "" ]; then
         echo "----------------------------------------------------------------"
         echo "WORKSPACE: $PADOGRID_WORKSPACE"
         echo >&2 "    ERROR: The 'vm.hosts' property is not set in the 'etc/cluster.properties' file."
         echo >&2 "           file. Command aborted."
         echo "----------------------------------------------------------------"
         exit 1
      fi
   fi
fi

#
# Reconstruct command
#
COMMAND_OPTS=""
COMMAND=""
PREV_VAL=""
for i in $*; do
   if [[ "$i" == "${CLUSTER}" ]]; then
       if [ -z $CLUSTER_SPECIFIED ]; then
          COMMAND="$COMMAND $i"
       fi
   elif [[ "$i" != "-cluster" ]]  && [[ "$i" != "-vm" ]]  && [[ "$i" != "-all" ]] && [[ "$i" != "-bg" ]] && [[ "$i" != "-simulate" ]]; then
      if [ "$PREV_VAL" != "-vm" ]; then
         COMMAND="$COMMAND $i"
      fi
   else
      COMMAND_OPTS="$COMMAND_OPTS $i"
   fi
   PREV_VAL=$i
done

VM_USER=`getVmUser`

KEY_FILE=`getClusterProperty "vm.privateKeyFile"`
if [ "$KEY_FILE" == "" ]; then
   # Set the first private key file found in the workspace directory if exists
   __VM_PRIVATE_KEY_FILE_FOUND="false"
   if [ "$VM_PRIVATE_KEY_FILE" == "" ]; then
      if [ -f $PADOGRID_WORKSPACE/*.pem ]; then
         for i in $PADOGRID_WORKSPACE/*.pem; do
            VM_PRIVATE_KEY_FILE=$i
            __VM_PRIVATE_KEY_FILE_FOUND="true"
            break
         done
      elif [ -f $PADOGRID_WORKSPACE/*.key ]; then
         for i in $PADOGRID_WORKSPACE/*.key; do
            VM_PRIVATE_KEY_FILE=$i
            __VM_PRIVATE_KEY_FILE_FOUND="true"
            break
         done
      fi
   fi
   # Replace '~' with the VM home path
   KEY_FILE=$(echo $VM_PRIVATE_KEY_FILE | sed "s|\~|$HOME|")
fi
if [ "$KEY_FILE" == "" ]; then 
   KEY_FILE="$VM_PRIVATE_KEY_FILE"
fi
VM_KEY=""
if [ "$KEY_FILE" != "" ]; then 
   if [ ! -f "$KEY_FILE" ]; then
      echo -e >&2 "${CError}ERROR:${CNone} Specified private key does not exist [$KEY_FILE]."
      echo >&2 "       Command aborted."
      exit 1
   fi
   VM_KEY="-i $KEY_FILE"
fi

if [ "$(isVmPrivateHostReachable "$VM_USER" "$VM_KEY")" == "true" ]; then
   # If private hosts are reachable then execute from here.
   # Replace , with space
   __VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
else
   # If private hosts are not reachable then copy to the first public host and then
   # use that public host as a proxy to execute this command.
   VM_PUBLIC_HOSTS=`getClusterProperty "vm.public.hosts"`
   if [ "$VM_PUBLIC_HOSTS" == "" ]; then
      echo -e >&2 "${CLightRed}ERROR:${CNone} Unable to connect to VM hosts. Please set 'vm.public.hosts' in 'etc/cluster.properties."
      echo >&2 "       Command aborted."
      exit 1
   fi
   #RWE_NAME=$(basename $PADOGRID_WORKSPACES_HOME)
   #WORKSPACE=$(basename $PADOGRID_WORKSPACE)
   RWE_NAME=$(basename $VM_PADOGRID_WORKSPACES_HOME)
   WORKSPACE=$(basename $VM_PADOGRID_WORKSPACE)
   VM_HOST=$(echo "$VM_PUBLIC_HOSTS" | sed "s/,.*//g")

   # Execute on public vm
  if [ "$SIMULATE" == "true" ]; then
      echo ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $COMMAND_OPTS \"$COMMAND\""
      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $COMMAND_OPTS \"$COMMAND\""
  else
      ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "switch_rwe $RWE_NAME/$WORKSPACE && $COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -all $COMMAND_OPTS \"$COMMAND\""
  fi
   exit
fi

THIS_VM_HOSTNAME=`hostname`
if [ "$BG_SPECIFIED" == "true" ]; then
   SSH_OPTIONS="-f"
else
   SSH_OPTIONS=""
fi
for VM_HOST in $__VM_HOSTS; do
     HOST_NAME=`ssh -n $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "hostname"`
     if [ "$ALL" != "true" ] && [ "$HOST_NAME" == "$THIS_VM_HOSTNAME" ]; then
        continue
     fi

     echo "---------- $VM_HOST ----------"
     if [ "$SIMULATE" == "true" ]; then
        echo ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND"
     else
        ssh -n $SSH_OPTIONS $VM_KEY $VM_USER@$VM_HOST -o LogLevel=error -o stricthostkeychecking=no -o connecttimeout=$SSH_CONNECT_TIMEOUT "$COMMAND"
     fi
     echo ""
done
if [ "$SIMULATE" == "true" ]; then
   echo "Simulation complete."
fi
