#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh > /dev/null

EXECUTABLE="`basename $0`"
SECRET_FILE=overlay-base/cm-adapter-serving-certs.yaml

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
    $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Build a Hazelcast Jet OpenShift environment.

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Builds a Hazelcast Jet OpenShift environment and creates the OpenShift project, $APP_NAME. The default
   settings are configured based on the PadoGrid cluster environment. 

   You can change the number of members, the load balancer port, and node port gap by setting the following
   environment variables in the 'setenv.sh' file. Seee 'setenv.sh' for details.

      MEMBER_COUNT=$MEMBER_COUNT
      START_SERVICE_PORT=$START_SERVICE_PORT
      NODE_PORT_GAP=$NODE_PORT_GAP

SEE ALSO
   setenv.sh, start_jet

EOF
exit
fi

#
# Copy templates
#
cp -r $APP_DIR/templates/jet $APP_DIR/

#
# rbac.yaml
#
sed -e "s/\${NAMESPACE}/$PROJECT_NAME/" \
    $APP_DIR/templates/jet/rbac.yaml > $APP_DIR/jet/rbac.yaml

#
# ConfigMaps
#
sed -e "s/\${CLUSTER_NAME}/$PROJECT_NAME/" \
    -e "s/\${NAMESPACE}/$PROJECT_NAME/" \
    -e "s/\${SERVICE_NAME}/$SERVICE_NAME/" \
    $APP_DIR/templates/jet/hazelcast-jet-config.yaml > $APP_DIR/jet/hazelcast-jet-config.yaml
sed -e "s/\${CLUSTER_NAME}/$PROJECT_NAME/" \
    -e "s/\${NAMESPACE}/$PROJECT_NAME/" \
    -e "s/\${MANAGEMENT_CENTER_SERVICE_NAME}/$MANAGEMENT_CENTER_SERVICE_NAME/" \
    $APP_DIR/templates/jet/mancenter-configmap.yaml > $APP_DIR/jet/mancenter-configmap.yaml

#
# hazelcast-jet.xml
#

# There is a bug in OpenShift that fails to read the value of HAZELCAST_JET_REPLICAS.
# Replace it with the actual value.
sed -e "s/replicas: \${HAZELCAST_JET_REPLICAS}/replicas: $MEMBER_COUNT/" \
    $APP_DIR/templates/jet/hazelcast-jet-enterprise-rhel.yaml > $APP_DIR/jet/hazelcast-jet-enterprise-rhel.yaml
sed -e "s/replicas: \${HAZELCAST_JET_REPLICAS}/replicas: $MEMBER_COUNT/" \
    $APP_DIR/templates/jet/hazelcast-jet-enterprise.yaml > $APP_DIR/jet/hazelcast-jet-enterprise.yaml
sed -e "s/replicas: \${HAZELCAST_JET_REPLICAS}/replicas: $MEMBER_COUNT/" \
    $APP_DIR/templates/jet/hazelcast-jet.yaml > $APP_DIR/jet/hazelcast-jet.yaml

#
# Services
#

# service-lb.yaml
NODE_PORT=$START_SERVICE_PORT
sed "s/nodePort:.*$/nodePort: $NODE_PORT/" $APP_DIR/templates/jet/service-lb.yaml > $APP_DIR/jet/service-lb.yaml

# service-pods.yaml
rm $APP_DIR/jet/service-lb-pods.yaml
let LAST_MEMBER_NUM=MEMBER_COUNT-1
for i in $(seq 0 $LAST_MEMBER_NUM); do
   let NODE_PORT=NODE_PORT+1
   if [ $i -gt 0 ]; then
      echo "" >> $APP_DIR/jet/service-lb-pods.yaml
      echo "---" >> $APP_DIR/jet/service-lb-pods.yaml
      echo "" >> $APP_DIR/jet/service-lb-pods.yaml
   fi
   sed -e "s/nodePort:.*$/nodePort: $NODE_PORT/g" -e "s/\-0/\-$i/g" $APP_DIR/templates/jet/service-lb-pods.yaml >> $APP_DIR/jet/service-lb-pods.yaml
done

# service-nodeport.yaml
let NODE_PORT=START_SERVICE_PORT+NODE_PORT_GAP
sed "s/nodePort:.*$/nodePort: $NODE_PORT/" $APP_DIR/templates/jet/service-nodeport.yaml > $APP_DIR/jet/service-nodeport.yaml

# service-pods-nodeports.yaml
if [ -f $APP_DIR/jet/service-nodeport-pods.yaml ]; then
   rm $APP_DIR/jet/service-nodeport-pods.yaml
fi
let LAST_MEMBER_NUM=MEMBER_COUNT-1
for i in $(seq 0 $LAST_MEMBER_NUM); do
   let NODE_PORT=NODE_PORT+1
   if [ $i -gt 0 ]; then
      echo "" >> $APP_DIR/jet/service-nodeport-pods.yaml
      echo "---" >> $APP_DIR/jet/service-nodeport-pods.yaml
      echo "" >> $APP_DIR/jet/service-nodeport-pods.yaml
   fi
   sed -e "s/nodePort:.*$/nodePort: $NODE_PORT/g" -e "s/\-0/\-$i/g" $APP_DIR/templates/jet/service-nodeport-pods.yaml >> $APP_DIR/jet/service-nodeport-pods.yaml
done


oc new-project $APP_NAME
