#!/bin/bash 
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh > /dev/null

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-cluster <cluster-name>] [-?]"
   echo ""
   echo "   Configures the Vagrant environment. This script should be called once"
   echo "   after Vagrant is up."
   echo ""
   echo "Default: ./$EXECUTABLE -cluster $CLUSTER"
   echo ""
   exit
fi

POD_TYPE=`getPodProperty "pod.type"`
if [ "$POD_TYPE" != "vagrant" ]; then
   echo "ERROR: Invalid pod type. The pod type must be vagrant. [pod=$POD, type=$POD_TYPE]"
   echo "       Command aborted."
   exit 1
fi

# Build a complete list of node host names
NODE_NAME_PRIMARY=`getPodProperty "node.name.primary" $NODE_NAME_PRIMARY`
NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
NODE_COUNT=`getPodProperty "node.count" $NODE_COUNT`

HOSTS="${NODE_NAME_PRIMARY}"
HOSTS_LOCAL="${NODE_NAME_PRIMARY}.local"
for i in $(seq 1 $NODE_COUNT); do
   if [ $i -lt 10 ]; then
      NODE=${NODE_NAME_PREFIX}-0$i
   else
      NODE=${NODE_NAME_PREFIX}-$i
   fi
   NODE_LOCAL=${NODE}.local
   HOSTS_LOCAL="$HOSTS_LOCAL $NODE_LOCAL" 
   HOSTS="$HOSTS $NODE" 
done


# Concat the public keys to authorized_keys
pushd $POD_DIR/tmp/ssh > /dev/null 2>&1
if [ -f ../authorized_keys ]; then
  rm ../authorized_keys
fi
for i in *; do
   `cat $i >> ../authorized_keys`
done
popd > /dev/null 2>&1

# Deploy the authorized_keys to all nodes.
pushd $POD_DIR > /dev/null 2>&1
for NODE in $HOSTS; do
   vagrant ssh $NODE -c "cp /vagrant/tmp/authorized_keys /home/vagrant/.ssh/"
   # system dir
   #vagrant ssh $NODE -c "sudo ssh-keyscan -t rsa $HOSTS_LOCAL > /etc/ssh/ssh_known_hosts"
   # user's home
   #vagrant ssh $NODE -c "ssh-keyscan -t rsa $HOSTS_LOCAL > /home/vagrant/.ssh/known_hosts"
done
popd > /dev/null 2>&1
