#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-datasource <datasource-name>] [-?]"
   echo ""
   echo "   Creates the Prometheus datasource in Grafana."
   echo "     <datasource-name>  Datasource name."
   echo ""
   echo "Default: ./$EXECUTABLE -datasource $DEFAULT_DATASOURCE"
   echo ""
   exit
fi

if [ "$DATASOURCE" == "" ]; then
   DATASOURCE=$DEFAULT_DATASOURCE
fi

curl -sS -X POST $GRAFANA_URL/api/datasources -H "Content-Type: application/json" -d '{"name": "'"$DATASOURCE"'", "type": "prometheus", "url": "http://'"$PROMETHEUS_URL"'", "access": "proxy", "basicAuth": false, "jsonData": { "httpMethod": "GET", "keepCookies": [] } }' | jq .
