#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# Get all folders from the dashbarod dir
pushd $DASHBOARDS_DIR > /dev/null 2>&1
__FOLDERS=`ls`
FOLDERS=""
for i in $__FOLDERS; do
   FOLDERS="$FOLDERS $i"
done
popd > /dev/null 2>&1

if [ "$HELP" == "true" ]; then
   echo "Usage:"
   echo "   ./$EXECUTABLE [-?]"
   echo ""
   echo "   Lists all of the folders that are available in the 'etc/dashboard' directory." 
   echo "   The listed folders can be imported into Grafana using the 'import_folder' command."
   echo "   This command is equivalent to the 'ls' command as follows:"
   echo "      ls $APP_DIR/etc/dashboard"
   echo ""
   echo "Default: ./$EXECUTABLE"
   echo ""
   exit
fi

echo "Folders on local file system. Run 'import_folder' to import them into Grafana." 
for i in $FOLDERS; do
   echo "   $i"
done
echo ""
