#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"
ALIAS_EXECUTABLE=$(echo $EXECUTABLE | sed 's/worker/member/')

$ALIAS_EXECUTABLE "$@"

if [ "$HELP" == "true" ]; then
   EXEC_LIST="$EXECUTABLE(1)\n$ALIAS_EXECUTABLE(1)"  
   EXEC_LIST=$(echo -e $EXEC_LIST | sort -)
   EXEC_LIST=$(echo $EXEC_LIST | sed 's/ /, /g')
cat <<EOF
ALIASES
   $EXEC_LIST

EOF
fi
exit

# For padogrid -? only
cat <<EOF
NAME
   $EXECUTABLE - Add a new member to the specified cluster in the current padogrid workspace
EOF
