#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-cluster -short -long -all -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Display the status of the specified cluster in the current workspace

SYNOPSIS
   $EXECUTABLE [-cluster cluster_name] [-short | -long] [-all] [-?]

DESCRIPTION
   Displays cluster status.

OPTIONS
   -cluster cluster_name
             Cluster name.

   -short
             Displays running status only.

   -long
             Displays detailed information.

   -all
             Displays all clusters

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -cluster $CLUSTER

FILES
   $CLUSTER_DIR/etc/cluster.properties
             The current cluster configuration file.

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "*cluster*" $EXECUTABLE
   exit
fi

#
# Run the target cluster command if the product is different.
#
if [ "$PRODUCT_CLUSTER_SPECIFIED" == "false" ]; then
   THIS_PRODUCT="$(basename $(dirname $SCRIPT_DIR))"
   if [ "$THIS_PRODUCT" != "$PRODUCT" ]; then
      $PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -product-cluster $CLUSTER "$@"
      exit
   fi
fi

RWE_NAME=$(basename "$PADOGRID_WORKSPACES_HOME")
WORKSPACE_NAME=$(basename "$PADOGRID_WORKSPACE")
SWITCH_CLUSTER_COMMAND="switch_rwe $RWE_NAME $WORKSPACE_NAME; switch_cluster $CLUSTER"

# Displays short status of a VM cluster.
# @required VM_MASTER_HOSTS A space separated list of VM master hosts (addresses)
# @required VM_HOSTS         A space separated list of VM worker hosts (addresses)
function displayVmClusterShort()
{
   # If pod cluster, then source in the pod env vars to set the VM specific variables
   OS_ENV=`getOsEnv $NODE`
   if [ "$OS_ENV" == "gh" ] && [ "$POD" != "local" ]; then
      if [ -f "$PODS_DIR/$POD/.nodeenv.sh" ]; then
	 . "$PODS_DIR/$POD/.nodeenv.sh"
      fi
   fi

   # Masters
   MASTER_COUNT=0
   RUNNING_MASTER_COUNT=0
   for VM_HOST in ${VM_MASTER_HOSTS}; do
      let MASTER_COUNT=MASTER_COUNT+1
      MASTER=`getVmMasterName $VM_HOST`
      pid=`getVmMasterPid $VM_HOST $MASTER $WORKSPACE $RWE`
      if [ "$pid" != "" ]; then
          let RUNNING_MASTER_COUNT=RUNNING_MASTER_COUNT+1
      fi
   done

   # Workers
   WORKER_COUNT=0
   RUNNING_WORKER_COUNT=0
   for VM_HOST in ${VM_HOSTS}; do
      let WORKER_COUNT=WORKER_COUNT+1
      WORKER=`getVmMemberName $VM_HOST`
      pid=`getVmMemberPid $VM_HOST $WORKER $WORKSPACE $RWE`
      if [ "$pid" != "" ]; then
          let RUNNING_WORKER_COUNT=RUNNING_WORKER_COUNT+1
      fi
   done
   
   echo "         CLUSTER: $CLUSTER"
   if [ "$SHORT" == "false" ]; then
   echo "     CLUSTER_DIR: $PADOGRID_WORKSPACE/clusters/$CLUSTER"
   echo "         PRODUCT: $PRODUCT"
   echo "    CLUSTER_TYPE: $CLUSTER_TYPE"
   echo "      Deployment: VM"
   fi
   if [ $RUNNING_MASTER_COUNT -eq $MASTER_COUNT ]; then
   echo -e " Masters Running: ${CLightGreen}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   else
   echo -e " Masters Running: ${CLightRed}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   fi
   if [ $RUNNING_WORKER_COUNT -eq $WORKER_COUNT ]; then
   echo -e " Workers Running: ${CLightGreen}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   else
   echo -e " Workers Running: ${CLightRed}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   fi
   if [ "$SHORT" == "false" ]; then
   echo "         Version: $SPARK_VERSION"
   echo "  Switch Cluster: $SWITCH_CLUSTER_COMMAND"
   fi
   echo ""
} # displayVmClusterShort

# Displays long status of a VM cluster.
function displayVmClusterLong()
{
   SPARK_CONFIG_FILE=$ETC_DIR/cache.xml
   MASTER_START_PORT=`getClusterProperty "master.tcp.startPort" $DEFAULT_MASTER_START_PORT`
   WORKER_START_PORT=`getClusterProperty "tcp.startPort" $DEFAULT_WORKER_START_PORT`
   WORKER_WEBUI_START_PORT=`getClusterProperty "http.startPort" $DEFAULT_WORKER_WEBUI_START_PORT`
   JMX_MANAGER_WEBUI_START_PORT=`getClusterProperty "master.jmx.manager.http.startPort" $DEFAULT_JMX_MANAGER_WEBUI_START_PORT`
   JMX_MANAGER_START_PORT=`getClusterProperty "master.jmx.manager.startPort" $DEFAULT_JMX_MANAGER_START_PORT`
   DEBUG_ENABLED=`getClusterProperty "debug.enabled" $DEFAULT_DEBUG_ENABLED`
   DEBUG_START_PORT=`getClusterProperty "debug.startPort" $DEFAULT_DEBUG_START_PORT`
   JMX_ENABLED=`getClusterProperty "jmx.enabled" $DEFAULT_JMX_ENABLED`
   JMX_START_PORT=`getClusterProperty "jmx.startPort" $DEFAULT_JMX_START_PORT`
   PROMETHEUS_ENABLED=`getClusterProperty "prometheus.enabled" $DEFAULT_PROMETHEUS_ENABLED`
   PROMETHEUS_START_PORT=`getClusterProperty "prometheus.startPort" $DEFAULT_PROMETHEUS_START_PORT`

   if [ "$DEBUG_ENABLED" != "true" ]; then
      DEBUG_PORT="Disabled"
   fi
   if [ "$JMX_ENABLED" != "true" ]; then
      JMX_PORT="Disabled"
      JMX_URL="Disabled"
   fi
   if [ "$PROMETHEUS_ENABLED" != "true" ]; then
      PROMETHEUS_PORT="Disabled"
   fi
 
   # If pod cluster, then source in the pod env vars to set the VM specific variables
   OS_ENV=`getOsEnv $NODE`
   if [ "$OS_ENV" == "gh" ] && [ "$POD" != "local" ]; then
      if [ -f "$PODS_DIR/$POD/.nodeenv.sh" ]; then
	 . "$PODS_DIR/$POD/.nodeenv.sh"
      fi
   fi

   RUN_DIR=$CLUSTERS_DIR/$CLUSTER/run
   pushd $RUN_DIR > /dev/null 2>&1
   MEMBER_PREFIX=`getMemberPrefix`
   pushd $RUN_DIR > /dev/null 2>&1

   echo "----------------------------------------------------------------"
   if [ $CLUSTER == $DEFAULT_CLUSTER ]; then
      echo "         CLUSTER: $CLUSTER (default)"
   else
      echo "         CLUSTER: $CLUSTER"
   fi
   echo "     CLUSTER_DIR: $PADOGRID_WORKSPACE/clusters/$CLUSTER"
   echo "         PRODUCT: $PRODUCT"
   echo "      Deployment: VM"
   echo ""

   # Masters

   MASTER_COUNT=0
   RUNNING_MASTER_COUNT=0
   DOWN_MASTER_COUNT=0
   for VM_HOST in ${VM_MASTER_HOSTS}; do
      MASTER=`getVmMasterName $VM_HOST`
      let MASTER_COUNT=MASTER_COUNT+1
      MASTER_DIR=$RUN_DIR/$MASTER

      # Increment port numbers for host OS
      MASTER_HOSTNAME_FOR_CLIENTS=`getClusterProperty "vm.${VM_HOST}.hostnameForClients" "$VM_HOST"`
      MASTER_PORT=$MASTER_START_PORT
      if [ "$DEBUG_ENABLED" == "true" ]; then
         DEBUG_PORT=$DEBUG_START_PORT
      fi
      if [ "$JMX_ENABLED" == "true" ]; then
         JMX_PORT=$JMX_START_PORT
         JMX_URL="service:jmx:rmi:///jndi/rmi://${MASTER_HOSTNAME_FOR_CLIENTS}:$JMX_PORT/jmxrmi"
      fi
      if [ "$PROMETHEUS_ENABLED" == "true" ]; then
         PROMETHEUS_PORT=$PROMETHEUS_START_PORT
      fi

      WEBUI_URL="http://${MASTER_HOSTNAME_FOR_CLIENTS}:$MASTER_WEBUI_PORT"

      LOG_FILE=$LOG_DIR/${MASTER}.log
      
      if [ $MASTER_COUNT -lt 10 ]; then
         NUM="0"$MASTER_COUNT
      else
         NUM=$MASTER_COUNT
      fi
      echo "$NUM        Master: $MASTER"

      pid=`getVmMasterPid $VM_HOST $MASTER $WORKSPACE $RWE`
      if [ -z $pid ]; then
         let DOWN_MASTER_COUNT=DOWN_MASTER_COUNT+1
         echo -e "          STATE: ${CLightRed}Down${CNone}"
         echo "             PID: N/A"
      else
         let RUNNING_MASTER_COUNT=RUNNING_MASTER_COUNT+1
         echo -e "          STATE: ${CLightGreen}Running${CNone}"
         echo "             PID: $pid"
      fi

      echo "    MASTER_PORT: $MASTER_PORT"
#      echo "      DEBUG_PORT: $DEBUG_PORT"
#      echo " PROMETHEUS_PORT: $PROMETHEUS_PORT"
      echo -e "       WEBUI_URL: $CUrl$WEBUI_URL$CNone"
      echo "         JMX_URL: $JMX_URL"
      echo "     Working Dir: $MASTER_DIR"
      echo "        LOG_FILE: $LOG_FILE"
      echo ""
   done

   # Workers

   WORKER_COUNT=0
   RUNNING_WORKER_COUNT=0
   DOWN_WORKER_COUNT=0
   for VM_HOST in ${VM_HOSTS}; do
      WORKER=`getVmMemberName $VM_HOST`
      let WORKER_COUNT=WORKER_COUNT+1
      WORKER_DIR=$RUN_DIR/$WORKER

      # Increment port numbers for host OS
      WORKER_PORT=$WORKER_START_PORT
      WORKER_WEBUI_PORT=$WORKER_WEBUI_START_PORT
      HOSTNAME_FOR_CLIENTS=`getClusterProperty "vm.${VM_HOST}.hostnameForClients" "$VM_HOST"`
      WORKER_WEBUI_URL="http://${HOSTNAME_FOR_CLIENTS}:${WORKER_WEBUI_PORT}"
      if [ "$DEBUG_ENABLED" == "true" ]; then
         DEBUG_PORT=$DEBUG_START_PORT
      fi
      if [ "$JMX_ENABLED" == "true" ]; then
         JMX_PORT=$JMX_START_PORT
         JMX_URL="service:jmx:rmi:///jndi/rmi://${VM_HOST}:$JMX_PORT/jmxrmi"
      fi
      if [ "$PROMETHEUS_ENABLED" == "true" ]; then
         PROMETHEUS_PORT=$PROMETHEUS_START_PORT
      fi

      LOG_FILE=$LOG_DIR/${WORKER}.log
      
      if [ $WORKER_COUNT -lt 10 ]; then
         NUM="0"$WORKER_COUNT
      else
         NUM=$WORKER_COUNT
      fi
      echo "$NUM        Worker: $WORKER"

      pid=`getVmMemberPid $VM_HOST $WORKER $WORKSPACE $RWE`
      if [ -z $pid ]; then
         let DOWN_WORKER_COUNT=DOWN_WORKER_COUNT+1
         echo -e "           STATE: ${CLightRed}Down${CNone}"
         echo "             PID: N/A"
      else
         let RUNNING_WORKER_COUNT=RUNNING_WORKER_COUNT+1
         echo -e "           STATE: ${CLightGreen}Running${CNone}"
         echo "             PID: $pid"
      fi

      echo "     WORKER_PORT: $WORKER_PORT"
      echo "WORKER_WEBUI_URL: $WORKER_WEBUI_URL"
      echo "      DEBUG_PORT: $DEBUG_PORT"
      echo " PROMETHEUS_PORT: $PROMETHEUS_PORT"
      echo "         JMX_URL: $JMX_URL"
      echo "     Working Dir: $WORKER_DIR"
      echo "        LOG_FILE: $LOG_FILE"
      echo ""
   done

   echo "         CLUSTER: $CLUSTER"
   if [ $RUNNING_MASTER_COUNT -eq $MASTER_COUNT ]; then
   echo -e " Masters Running: ${CLightGreen}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   else
   echo -e " Masters Running: ${CLightRed}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   fi
   if [ $RUNNING_WORKER_COUNT -eq $WORKER_COUNT ]; then
   echo -e " Workers Running: ${CLightGreen}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   else
   echo -e " Workers Running: ${CLightRed}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   fi
   echo "         Version: $SPARK_VERSION"
   echo "  Switch Cluster: $SWITCH_CLUSTER_COMMAND"
} # displayVmClusterLong

# Displays short status of a local/pod cluster.
function displayClusterShort()
{
   __HOSTNAME=`hostname`
   OS_ENV=`getOsEnv $__HOSTNAME`
   NODE=`getOsNodeName`
   POD_TYPE=`getClusterProperty "pod.type" $POD_TYPE`
   __NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
   RUN_DIR=$CLUSTERS_DIR/$CLUSTER/run
   NODE_NAME_PRIMARY=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
   NODE_NAME_PREFIX=$NODE_NAME_PRIMARY
   MASTER_PREFIX=`getMasterPrefix`
   MASTER_COUNT=`getMasterCount`
   NODE_NAME_PREFIX=$__NODE_NAME_PREFIX
   MEMBER_PREFIX=`getMemberPrefix`
   WORKER_COUNT=`getMemberCount`

   RUNNING_MASTER_COUNT=-1
   RUNNING_WORKER_COUNT=-1
   if ( [ "$POD_TYPE" == "local" ] && [ "$POD" == "local" ] )  ||
      ( [ "$OS_ENV" == "hh" ] && [ "$POD" == "local" ] )  ||
      ( [ "$OS_ENV" == "gg" ] && [ "$OS_POD" == "$POD" ] );  then
      pushd $RUN_DIR > /dev/null 2>&1
      RUNNING_MASTER_COUNT=0
      RUNNING_WORKER_COUNT=0
      if [ "$OS_ENV" == "gg" ] && [ "$POD" != "local" ]; then
         REMOTE_SPECIFIED=false
      else
         REMOTE_SPECIFIED=true
      fi
      # Masters
      for i in ${MASTER_PREFIX}*; do
         if [ -d "$i" ]; then
            MASTER=$i
            MASTER_NUM=${MASTER##$MASTER_PREFIX}
            if [ "$OS_ENV" == "hh" ]; then
               NODE_LOCAL=`getOsNodeName`
            else
               NODE_NAME_PRIMARY=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
               NODE_LOCAL="${NODE_NAME_PRIMARY}.local"
            fi
            pid=`getMasterPid $MASTER $WORKSPACE $RWE`
            if [ "$pid" != "" ]; then
                let RUNNING_MASTER_COUNT=RUNNING_MASTER_COUNT+1
            fi
         fi
      done
      # Workers
      for i in ${MEMBER_PREFIX}*; do
         if [ -d "$i" ]; then
            WORKER=$i
            WORKER_NUM=${WORKER##$MEMBER_PREFIX}
            if [ "$OS_ENV" == "hh" ]; then
               NODE_LOCAL=`getOsNodeName`
            else
               NODE=${NODE_NAME_PREFIX}-$WORKER_NUM
               NODE_LOCAL=`getOsNodeName $NODE`
            fi
            pid=`getMemberPid $WORKER $WORKSPACE $RWE`
            if [ "$pid" != "" ]; then
                let RUNNING_WORKER_COUNT=RUNNING_WORKER_COUNT+1
            fi
         fi
      done
      popd > /dev/null 2>&1
   fi

   echo "         CLUSTER: $CLUSTER"
   if [ "$SHORT" == "false" ]; then
   echo "     CLUSTER_DIR: $PADOGRID_WORKSPACE/clusters/$CLUSTER"
   echo "         PRODUCT: $PRODUCT"
   echo "    CLUSTER_TYPE: $CLUSTER_TYPE"
   echo "             POD: $POD"
   echo "        POD_TYPE: $POD_TYPE"
   fi
   if [ $RUNNING_MASTER_COUNT -lt 0 ]; then
   echo -e " Masters Running: ${CYellow}Unknown${CNone}"
   elif [ $RUNNING_MASTER_COUNT -eq $MASTER_COUNT ]; then
   echo -e " Masters Running: ${CLightGreen}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   else
   echo -e " Masters Running: ${CLightRed}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   fi
   if [ $RUNNING_WORKER_COUNT -lt 0 ]; then
   echo -e " Workers Running: ${CYellow}Unknown${CNone}"
   elif [ $RUNNING_WORKER_COUNT -eq $WORKER_COUNT ]; then
   echo -e " Workers Running: ${CLightGreen}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   else
   echo -e " Workers Running: ${CLightRed}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   fi
   if [ "$SHORT" == "false" ]; then
   echo "         Version: $SPARK_VERSION"
   echo "  Switch Cluster: $SWITCH_CLUSTER_COMMAND"
   fi
} # dispalyClusterShort

# Displays long status of a local/pod cluster.
function displayClusterLong()
{
   SPARK_CONFIG_FILE=$ETC_DIR/cache.xml
   POD_TYPE=`getClusterProperty "pod.type" $POD_TYPE`
   __NODE_NAME_PREFIX=`getPodProperty "node.name.prefix" $NODE_NAME_PREFIX`
   NODE_NAME_PRIMARY=`getPodProperty "node.name.primary" $NODE_NAME_PRIMARY`
   NODE_NAME_PREFIX=$NODE_NAME_PRIMARY
   MASTER_PREFIX=`getMasterPrefix`
   NODE_NAME_PREFIX=$__NODE_NAME_PREFIX
   NODE=`getOsNodeName`
   MASTER_START_PORT=`getClusterProperty "master.tcp.startPort" $DEFAULT_MASTER_START_PORT`
   MASTER_WEBUI_START_PORT=`getClusterProperty "master.webui.startPort" $DEFAULT_MASTER_START_PORT`
   MASTER_WEBUI_PORT=$MASTER_WEBUI_START_PORT
   WORKER_START_PORT=`getClusterProperty "tcp.startPort" $DEFAULT_WORKER_START_PORT`
   WORKER_WEBUI_START_PORT=`getClusterProperty "webui.startPort" $DEFAULT_WORKER_WEBUI_START_PORT`
   DEBUG_ENABLED=`getClusterProperty "debug.enabled" $DEFAULT_DEBUG_ENABLED`
   DEBUG_START_PORT=`getClusterProperty "debug.startPort" $DEFAULT_DEBUG_START_PORT`
   JMX_ENABLED=`getClusterProperty "jmx.enabled" $DEFAULT_JMX_ENABLED`
   JMX_START_PORT=`getClusterProperty "jmx.startPort" $DEFAULT_JMX_START_PORT`
   PROMETHEUS_ENABLED=`getClusterProperty "prometheus.enabled" $DEFAULT_PROMETHEUS_ENABLED`
   PROMETHEUS_START_PORT=`getClusterProperty "prometheus.startPort" $DEFAULT_PROMETHEUS_START_PORT`
   HOST_NAME=`hostname`
   HOSTNAME_FOR_CLIENTS=`getClusterProperty "cluster.hostnameForClients" $HOST_NAME`

   if [ "$DEBUG_ENABLED" != "true" ]; then
      DEBUG_PORT="Disabled"
   fi
   if [ "$JMX_ENABLED" != "true" ]; then
      JMX_PORT="Disabled"
      JMX_URL="Disabled"
   fi
   if [ "$PROMETHEUS_ENABLED" != "true" ]; then
      PROMETHEUS_PORT="Disabled"
   fi
 
   OS_ENV=`getOsEnv $NODE`
   RUN_DIR=$CLUSTERS_DIR/$CLUSTER/run
   #pushd $RUN_DIR > /dev/null 2>&1
#   MASTER_PREFIX=`getMasterPrefix`
   MEMBER_PREFIX=`getMemberPrefix`
#   pushd $RUN_DIR > /dev/null 2>&1

   echo "----------------------------------------------------------------"
   if [ $CLUSTER == $DEFAULT_CLUSTER ]; then
      echo "         CLUSTER: $CLUSTER (default)"
   else
      echo "         CLUSTER: $CLUSTER"
   fi
   echo "     CLUSTER_DIR: $PADOGRID_WORKSPACE/clusters/$CLUSTER"
   echo "         PRODUCT: $PRODUCT"
   echo "    CLUSTER_TYPE: $CLUSTER_TYPE"
   echo "             POD: $POD"
   echo "        POD_TYPE: $POD_TYPE"
   echo ""

   #
   # Masters
   #
   MASTER_COUNT=0
   RUNNING_MASTER_COUNT=0
   DOWN_MASTER_COUNT=0
   pushd $RUN_DIR > /dev/null 2>&1
   for i in ${MASTER_PREFIX}*; do
      if [ -d "$i" ]; then
         let MASTER_COUNT=MASTER_COUNT+1
         pushd $i > /dev/null 2>&1
         MASTER=$i
         MASTER_NUM=${MASTER##$MASTER_PREFIX}
         MASTER_NUM_NO_LEADING_ZERO=$((10#$MASTER_NUM))
         MASTER_DIR=$RUN_DIR/$MASTER
         if [ "$OS_ENV" == "hh" ]; then
            NODE=`getOsNodeName`
         else
            NODE_NAME_PRIMARY=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
            NODE="${NODE_NAME_PRIMARY}.local"
         fi

         
         if ( [ "$OS_ENV" == "hg" ] || [ "$OS_ENV" == "gh" ] ) ||
            ( [ "$OS_ENV" == "gg" ] );  then

            # Same port number for guest OS
            MASTER_PORT=$MASTER_START_PORT
            if [ "$DEBUG_ENABLED" == "true" ]; then
               DEBUG_PORT=$DEBUG_START_PORT
            fi
            if [ "$JMX_ENABLED" == "true" ]; then
               JMX_PORT=$JMX_START_PORT
               JMX_URL="service:jmx:rmi:///jndi/rmi://${NODE}:$JMX_PORT/jmxrmi"
            fi
            if [ "$PROMETHEUS_ENABLED" == "true" ]; then
               PROMETHEUS_PORT=$PROMETHEUS_START_PORT
            fi

         else

            # Increment port numbers for host OS
            let MASTER_PORT=MASTER_START_PORT+MASTER_NUM_NO_LEADING_ZERO-1
            if [ "$DEBUG_ENABLED" == "true" ]; then
               let DEBUG_PORT=DEBUG_START_PORT+MASTER_NUM_NO_LEADING_ZERO-1
            fi
            if [ "$JMX_ENABLED" == "true" ]; then
               let JMX_PORT=JMX_START_PORT+MASTER_NUM_NO_LEADING_ZERO-1
               JMX_URL="service:jmx:rmi:///jndi/rmi://${NODE}:$JMX_PORT/jmxrmi"
            fi
            if [ "$PROMETHEUS_ENABLED" == "true" ]; then
               let PROMETHEUS_PORT=PROMETHEUS_START_PORT+MASTER_NUM_NO_LEADING_ZERO-1
            fi

         fi

#         if [ "$POD" == "local" ]; then
            MASTER_HOSTNAME_FOR_CLIENTS=`getClusterProperty "cluster.hostnameForClients" "$NODE"`
#         else
#            PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
#            NODE_NAME_PREFIX=$PRIMARY_NODE_NAME
#            NODE_LOCAL="${PRIMARY_NODE_NAME}.local"
#            MASTER_HOSTNAME_FOR_CLIENTS=$NODE_LOCAL
#         fi

         WEBUI_URL="http://$MASTER_HOSTNAME_FOR_CLIENTS:$MASTER_WEBUI_PORT"

         LOG_FILE=$LOG_DIR/${MASTER}.log
         echo "$MASTER_NUM        Master: $MASTER"
         if ( [ "$POD_TYPE" == "local" ] && [ "$POD" == "local" ] )  ||
            ( [ "$OS_ENV" == "hh" ] && [ "$POD" == "local" ] )  ||
            ( [ "$OS_ENV" == "gg" ] && [ "$OS_POD" == "$POD" ] );  then
            NODE_LOCAL=$NODE
            if [ "$OS_ENV" == "gg" ] && [ "$POD" != "local" ]; then
               REMOTE_SPECIFIED=false
            else
               REMOTE_SPECIFIED=true
            fi
            pid=`getMasterPid $MASTER $WORKSPACE $RWE`
            if [ -z $pid ]; then
               let DOWN_MASTER_COUNT=DOWN_MASTER_COUNT+1
               echo -e "           STATE: ${CLightRed}Down${CNone}"
               echo "              PID: N/A"
            else
               let RUNNING_MASTER_COUNT=RUNNING_MASTER_COUNT+1
               echo -e "           STATE: ${CLightGreen}Running${CNone}"
               echo "             PID: $pid"
            fi
         else
            echo "            STATE: Unknown"
            echo "              PID: Unknown"
            RUNNING_MASTER_COUNT=-1
            DOWN_MASTER_COUNT=-1
         fi
         echo "     MASTER_PORT: $MASTER_PORT"
         echo "      DEBUG_PORT: $DEBUG_PORT"
         echo " PROMETHEUS_PORT: $PROMETHEUS_PORT"
         echo -e "       WEBUI_URL: $CUrl$WEBUI_URL$CNone"
         echo "         JMX_URL: $JMX_URL"
         echo "     Working Dir: $MASTER_DIR"
         echo "        LOG_FILE: $LOG_FILE"
         echo ""
         popd > /dev/null 2>&1
      fi
   done

   #
   # Workers
   #
   WORKER_COUNT=0
   RUNNING_WORKER_COUNT=0
   DOWN_WORKER_COUNT=0
   for i in ${MEMBER_PREFIX}*; do
      if [ -d "$i" ]; then
         let WORKER_COUNT=WORKER_COUNT+1
         pushd $i > /dev/null 2>&1
         WORKER=$i
         WORKER_NUM=${WORKER##$MEMBER_PREFIX}
         WORKER_NUM_NO_LEADING_ZERO=$((10#$WORKER_NUM))
         WORKER_DIR=$RUN_DIR/$WORKER
         #if [ "$POD_TYPE" == "local" ]; then
         if [ "$OS_ENV" == "hh" ]; then
            NODE=`getOsNodeName`
         else
            NODE=${NODE_NAME_PREFIX}-$WORKER_NUM
            NODE=`getOsNodeName $NODE`
         fi
         if ( [ "$OS_ENV" == "hg" ] || [ "$OS_ENV" == "gh" ] ) ||
            ( [ "$OS_ENV" == "gg" ] );  then

            # Same port number for guest OS
            WORKER_PORT=$WORKER_START_PORT
            WORKER_WEBUI_PORT=$WORKER_WEBUI_START_PORT
            WORKER_WEBUI_URL="http://${NODE}:${WORKER_WEBUI_PORT}"
            if [ "$DEBUG_ENABLED" == "true" ]; then
               DEBUG_PORT=$DEBUG_START_PORT
            fi
            if [ "$JMX_ENABLED" == "true" ]; then
               JMX_PORT=$JMX_START_PORT
               JMX_URL="service:jmx:rmi:///jndi/rmi://${NODE}:$JMX_PORT/jmxrmi"
            fi
            if [ "$PROMETHEUS_ENABLED" == "true" ]; then
               PROMETHEUS_PORT=$PROMETHEUS_START_PORT
            fi

         else

            # Increment port numbers for host OS
            let WORKER_PORT=WORKER_START_PORT+WORKER_NUM_NO_LEADING_ZERO-1
            let WORKER_WEBUI_PORT=WORKER_WEBUI_START_PORT+WORKER_NUM_NO_LEADING_ZERO-1
            HOSTNAME_FOR_CLIENTS=`getClusterProperty "cluster.hostnameForClients" "$NODE"`
            WORKER_WEBUI_URL="http://${HOSTNAME_FOR_CLIENTS}:${WORKER_WEBUI_PORT}"
            if [ "$DEBUG_ENABLED" == "true" ]; then
               let DEBUG_PORT=DEBUG_START_PORT+WORKER_NUM_NO_LEADING_ZERO-1
            fi
            if [ "$JMX_ENABLED" == "true" ]; then
               let JMX_PORT=JMX_START_PORT+WORKER_NUM_NO_LEADING_ZERO-1
               JMX_URL="service:jmx:rmi:///jndi/rmi://${NODE}:$JMX_PORT/jmxrmi"
            fi
            if [ "$PROMETHEUS_ENABLED" == "true" ]; then
               let PROMETHEUS_PORT=PROMETHEUS_START_PORT+WORKER_NUM_NO_LEADING_ZERO-1
            fi

         fi
         LOG_FILE=$LOG_DIR/${WORKER}.log
         echo "$WORKER_NUM        Worker: $WORKER"
         if ( [ "$POD_TYPE" == "local" ] && [ "$POD" == "local" ] )  ||
            ( [ "$OS_ENV" == "hh" ] && [ "$POD" == "local" ] )  ||
            ( [ "$OS_ENV" == "gg" ] && [ "$OS_POD" == "$POD" ] );  then
            NODE_LOCAL=$NODE
            if [ "$OS_ENV" == "gg" ] && [ "$POD" != "local" ]; then
               REMOTE_SPECIFIED=false
            else
               REMOTE_SPECIFIED=true
            fi
            pid=`getMemberPid $WORKER $WORKSPACE $RWE`
            if [ -z $pid ]; then
               let DOWN_WORKER_COUNT=DOWN_WORKER_COUNT+1
               echo -e "           STATE: ${CLightRed}Down${CNone}"
               echo "             PID: N/A"
            else
               let RUNNING_WORKER_COUNT=RUNNING_WORKER_COUNT+1
               echo -e "           STATE: ${CLightGreen}Running${CNone}"
               echo "             PID: $pid"
            fi
         else
            echo "           STATE: Unknown"
            echo "             PID: Unknown"
            RUNNING_WORKER_COUNT=-1
            DOWN_WORKER_COUNT=-1
         fi
         echo "     WORKER_PORT: $WORKER_PORT"
         echo -e "WORKER_WEBUI_URL: $CUrl$WORKER_WEBUI_URL$CNone"
         echo "      DEBUG_PORT: $DEBUG_PORT"
         echo " PROMETHEUS_PORT: $PROMETHEUS_PORT"
         echo "         JMX_URL: $JMX_URL"
         echo "     Working Dir: $WORKER_DIR"
         echo "        LOG_FILE: $LOG_FILE"
         echo ""
         popd > /dev/null 2>&1
      fi
   done
   popd > /dev/null 2>&1

   # Summary
   echo "         CLUSTER: $CLUSTER"
   echo "    CLUSTER_TYPE: $CLUSTER_TYPE"
   if [ $RUNNING_MASTER_COUNT -lt 0 ]; then
   echo -e " Masters Running: ${CYellow}Unknown${CNone}"
   elif [ $RUNNING_MASTER_COUNT -eq $MASTER_COUNT ]; then
   echo -e " Masters Running: ${CLightGreen}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   else
   echo -e " Masters Running: ${CLightRed}$RUNNING_MASTER_COUNT/$MASTER_COUNT${CNone}"
   fi
   if [ $RUNNING_WORKER_COUNT -lt 0 ]; then
   echo -e " Workers Running: ${CYellow}Unknown{CNone}"
   elif [ $RUNNING_WORKER_COUNT -eq $WORKER_COUNT ]; then
   echo -e " Workers Running: ${CLightGreen}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   else
   echo -e " Workers Running: ${CLightRed}$RUNNING_WORKER_COUNT/$WORKER_COUNT${CNone}"
   fi
   echo "         Version: $SPARK_VERSION"
   echo "  Switch Cluster: $SWITCH_CLUSTER_COMMAND"
   echo "----------------------------------------------------------------"
} # displayClusterLong

POD=`getClusterProperty "pod.name" "local"`

# 
# VM cluster
#
VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
if [ "$VM_ENABLED" == "true" ]; then

   # Display single VM cluster status

   if [ ! -d $CLUSTER_DIR ]; then
      echo "ERROR: The specified cluster does not exist: [$CLUSTER]. Command aborted."
      exit 1
   fi

   VM_MASTER_HOSTS=$(getClusterProperty "vm.master.hosts")
   if [ "$VM_MASTER_HOSTS" == "" ]; then
      echo "----------------------------------------------------------------"
      echo "CLUSTER_DIR: $PADOGRID_WORKSPACE/clusters/$CLUSTER"
      echo "      ERROR: VM local hosts undefined. Set 'vm.local.hosts' in the following cluster.properties file."  
      echo "             $ETC_DIR/cluster.properties"
      echo "             Command aborted."
      echo "----------------------------------------------------------------"
      exit 1
   fi
   VM_HOSTS=$(getClusterProperty "vm.hosts")
   if [ "$VM_HOSTS" == "" ]; then
      echo "----------------------------------------------------------------"
      echo "CLUSTER_DIR: $PADOGRID_WORKSPACE/clusters/$CLUSTER"
      echo "      ERROR: VM hosts undefined. Set 'vm.hosts' in the following cluster.properties file."  
      echo "             $ETC_DIR/cluster.properties"
      echo "             Command aborted."
      echo "----------------------------------------------------------------"
      exit 1
   fi

   # Replace , with space
   VM_MASTER_HOSTS=$(echo "$VM_MASTER_HOSTS" | sed "s/,/ /g")
   VM_HOSTS=$(echo "$VM_HOSTS" | sed "s/,/ /g")
   VM_USER=`getVmUser`
   VM_KEY=`getVmKeyArg`
  
   if [ "$LONG" == "false" ]; then
      # Short display (single)
      displayVmClusterShort
   else
      # Long display (single)
      displayVmClusterLong
   fi
   exit
fi

#
# Local cluster
#
if [ "$ALL" == "true" ]; then

   # Display all clusters

   pushd $CLUSTERS_DIR > /dev/null 2>&1
   CLUSTERS=""
   COUNT=0
   for i in *; do
      if [ -d "$i" ]; then
         let COUNT=COUNT+1
         if [ $COUNT -eq 1 ]; then
            CLUSTERS="$i"
         else
            CLUSTERS="$CLUSTERS $i"
         fi
      fi
   done
   popd > /dev/null 2>&1

   if [ "$CLUSTERS" == "" ]; then
      echo "No clusters found. To create one, execute the 'create_cluster' command."
      exit 0
   fi

   echo "----------------------------------------------------------------"
   echo "Clusters: $CLUSTERS"
   echo "----------------------------------------------------------------"
   echo ""

   THIS_PRODUCT=$PRODUCT
   if [ "$LONG" == "false" ]; then 
      # Short display -all
      for CLUSTER in ${CLUSTERS}; do
         determineClusterProduct $CLUSTER
         if [ "$THIS_PRODUCT" == $PRODUCT ]; then
            displayClusterShort
         else
           if [ "$SHORT" == "true" ]; then
              SHORT_OPT="-short"
           else
              SHORT_OPT=""
           fi
            $PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -product-cluster $CLUSTER -cluster $CLUSTER $SHORT_OPT
         fi
         echo ""
      done
   else
      # Long display -all
      for CLUSTER in ${CLUSTERS}; do
         determineClusterProduct $CLUSTER
         if [ "$THIS_PRODUCT" == $PRODUCT ]; then
            displayClusterLong
         else
            $PADOGRID_HOME/$PRODUCT/bin_sh/$EXECUTABLE -product-cluster $CLUSTER -long -cluster $CLUSTER
         fi
         echo ""
      done
   fi

   echo "----------------------------------------------------------------"
   popd > /dev/null 2>&1
   echo "Clusters: $CLUSTERS"
   echo "----------------------------------------------------------------"

else

   # Display single cluster status

   if [ ! -d $CLUSTER_DIR ]; then
      echo "ERROR: The specified cluster does not exist: [$CLUSTER]. Command aborted."
      exit 1
   fi

   if [ "$LONG" == "false" ]; then
      # Short display (single)
      displayClusterShort
   else
      # Long display (single)
      displayClusterLong
   fi
fi
