#!/bin/bash

# ========================================================================
# Copyright (c) 2013-2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

. ./setenv.sh > /dev/null 2>&1

if [ "$1" == "" ]; then
   echo "" 
   echo "You must specify the client name. Use the -? option to see Usage."
   exit
fi

if [ "$1" == "-?" ]; then
   echo ""
   echo "Usage:"
   echo "   import-certificate "client-name" [-?]"
   echo ""
   echo "      Imports a certifcate from"
   echo "         $SECURITY_DIR/export/client-name.cer"
   echo "      into"
   echo "         $SECURITY_DIR/import/publicKey.keystore."
   echo ""
   echo "   client-name  is the name of the client application used"
   echo "                to create keystore and certificate files."
   echo "                It is also the password."
   echo ""
   echo "   Note that the password is the password used to create "
   echo "   the publicKey.keystore file. If this file doesn't exist"
   echo "   then a new one is created with the password you entered"
   echo "   at the prompt."
   echo ""
   exit
fi 

echo "password is pado123"
keytool -import -alias $1 -file $SECURITY_DIR/export/$1.cer -keystore $SECURITY_DIR/publicKey.keystore
echo "Public keystore: $SECURITY_DIR/publicKey.keystore"
