#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Start Pado Desktop

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Starts Pado Desktop.

EOF
exit
fi

# ---
# IndexMatrix page size. IndexMatrix breaks up the result set into pages. The client
# application receives only a single page that pertains to the current pagenation view.
# This allows the client to scroll the received (or local) page. When the client
# scrolls beyond the local page, IndxeMatrix automatically fetches the page that matches
# the scrolled view and replaces the current page. This enables IndexMatrix to send the
# first page to the client while building the rest of the pages, providing very quick
# responses to the client.
#
# For large result sets, increasing this value can provide better performance at the
# exenpense of the increased delay in receiving the first page. The smaller the value
# the faster the intial page will be received by the client, but the more load will
# be put on IndexMatrix for creating the larger number of smaller pages.
# ---
PADO_PROPERTIES="-Dpado.index.pageSize=10000"

# --- Uncomment the following to enabled JXM
#JMX_PORT=30014
#JMX_PARAMETERS="-Dcom.sun.management.jmxremote.port=${JMX_PORT} -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false"

# --- Uncomment the following to enabled remote debugging
#DEBUG="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=9001"

if [[ ${OS_NAME} == CYGWIN* ]]; then
  CLASSPATH="$(cygpath -wp "$CLASSPATH")"
fi

pushd $APP_DIR > /dev/null 2>&1
"$JAVA" -Xms256m -Xmx1g -client $LAF -Dgemfire.name=PadoDesktop -DcodeBaseURL=$CODEBASE_URL -DpreferenceURL=etc/desktop.properties -Dcom.netcrest.ui.desktop.AboutDialog.title="About Netcrest Pado Desktop..." -Dpado.properties=etc/pado.properties -DgemfirePropertyFile=etc/client.properties $SECURITY_PROPERTIES $JMX_PARAMETERS $DEBUG $PADO_PROPERTIES com.netcrest.ui.desktop.Desktop > $LOG_FILE 2>&1 &
popd > /dev/null 2>&1
