#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2022 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Run the Pado encryptor for encrypting or descrypting text

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Runs the Pado encryptor for encrypting or descrypting text

EOF
exit
fi

GEMFIRE_PROPERTY_FILE="$ETC_DIR/client.properties"
if [[ ${OS_NAME} == CYGWIN* ]]; then
  GEMFIRE_PROPERTY_FILE="$(cygpath -wp "$GEMFIRE_PROPERTY_FILE")"
fi

pushd $APP_DIR > /dev/null 2>&1
"$JAVA" -DgemfirePropertyFile="$GEMFIRE_PROPERTY_FILE" com.netcrest.pado.internal.security.Encryptor $*
popd > /dev/null 2>&1
