#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2024 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-sp -tp -jar -dir -classpath -overwrite -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$JAR_ARG" != "" ]; then
   CLASSPATH="$CLASSPATH:$JAR_ARG"
fi
if [ "$CLASSPATH_ARG" != "" ]; then
   CLASSPATH="$CLASSPATH_ARG/*:$CLASSPATH"
fi
if [[ ${OS_NAME} == CYGWIN* ]]; then
   CLASSPATH="$(cygpath -wp "$CLASSPATH")"
fi
"$JAVA" -Dexecutable.name=$EXECUTABLE com.netcrest.padogrid.tools.WrapperGenerator $@
exit

# For padogrid -? only
cat <<EOF
NAME
   $EXECUTABLE - Generate classes that extend the classes found in the specified package
EOF
