{
 "title": "Dual Members",
 "description": "View two clusters in a single view for comparison",
 "tags": [
  "dual gemfire",
  "member",
  "cluster"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Locator Count",
   "type": "stat",
   "description": "$Cluster: Number of locators",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster\",category=\"LocatorStats\",member_type=\"locator\"} and on() (gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster\",category=\"LocatorStats\",member_type=\"locator\"} >= 0)) or on() gemfire_locators{$ClusterFilterLabel=\"$Cluster\",category=\"LocatorStats\",member_type=\"locator\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Node Count",
   "type": "stat",
   "description": "$Cluster: Number of nodes (peers)",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_nodes{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Total Entry Count",
   "type": "stat",
   "description": "$Cluster: Total number of primary entries in the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_entries{$ClusterFilterLabel=\"$Cluster\",member_type=\"server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Locator Count",
   "type": "stat",
   "description": "$Cluster2: Number of locators",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster2\",category=\"LocatorStats\",member_type=\"locator\"} and on() (gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster2\",category=\"LocatorStats\",member_type=\"locator\"} >= 0)) or on() gemfire_locators{$ClusterFilterLabel=\"$Cluster\",category=\"LocatorStats\",member_type=\"locator\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Node Count",
   "type": "stat",
   "description": "$Cluster2: Number of nodes (peers)",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_nodes{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Total Entry Count",
   "type": "stat",
   "description": "$Cluster2: Total number of primary entries in the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_entries{$ClusterFilterLabel=\"$Cluster2\",member_type=\"server\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Reads per second",
   "type": "stat",
   "description": "$Cluster: Aggregated get() rate across the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ceil(sum(gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}) / sum(gemfire_getTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Writes per second",
   "type": "stat",
   "description": "$Cluster: Aggregated put() rate across the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ceil(sum(gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}) / sum(gemfire_putTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Reads per second",
   "type": "stat",
   "description": "$Cluster2: Aggregated get() rate across the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ceil(sum(gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\", member_type=\"server\"}) / sum(gemfire_getTime{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Writes per second",
   "type": "stat",
   "description": "$Cluster: Aggregated put() rate across the cluster.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ceil(sum(gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\", member_type=\"server\"}) / sum(gemfire_putTime{$ClusterFilterLabel=\"$Cluster2\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Members",
   "type": "table",
   "description": "$Cluster: Member resource statuses",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Members",
   "type": "table",
   "description": "$Cluster2: Member resource statuses",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\", category=\"OffHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster2\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster2\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster2\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster2\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions Overall Operations Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest put(), get(), destroy(), putAll(), and removeAll() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_putsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_destroysCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_putAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_removeAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Partitioned Regions Overall Operations Heatmap",
   "type": "heatmap",
   "description": "$Cluster2: Heatmap of the member with the highest put(), get(), destroy(), putAll(), and removeAll() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}+gemfire_putsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}+gemfire_destroysCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}+gemfire_putAllsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}+gemfire_removeAllsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: put() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest put() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: put() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster2: Heatmap of the member with the highest put() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: get() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest get() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: get() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster2: Heatmap of the member with the highest get() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest number of bytes written to the disk. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "max (gemfire_writtenBytes{job=\"$Cluster\",category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Disk Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster2: Heatmap of the member with the highest number of bytes written to the disk. ",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "targets": [
    {
     "expr": "max (gemfire_writtenBytes{job=\"$Cluster2\",category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: putAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest putAll() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "max(gemfire_putAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: putAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "$Cluster2: Heatmap of the member with the highest putAll() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "max(gemfire_putAllsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: removeAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest remove() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "max(gemfire_removeAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: removeAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "$Cluster2: Heatmap of the member with the highest remove() calls completed.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "max(gemfire_removeAllsCompleted{job=\"$Cluster2\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}