{
 "title": "Dual Heap LRU",
 "tags": [
  "dual gemfire",
  "heap lru",
  "dual heap lru",
  "distribution"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 0 }
  },
  {
   "title": "$Cluster: Heap LRU Regions: Entry Bytes",
   "type": "barchart",
   "description": "$Cluster: The amount of memory currently used by regions configured for eviction.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_entryBytes{$ClusterFilterLabel=\"$Cluster\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Heap LRU Regions: Entry Bytes",
   "type": "barchart",
   "description": "$Cluster2: The amount of memory currently used by regions configured for eviction.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_entryBytes{$ClusterFilterLabel=\"$Cluster2\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Heap LRU Regions: Destroys",
   "type": "barchart",
   "description": "$Cluster: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Heap LRU Regions: Destroys",
   "type": "barchart",
   "description": "$Cluste2r: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster2\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Heap LRU Regions: Entry Bytes",
   "type": "table",
   "description": "$Cluster: The amount of memory currently used by regions configured for eviction.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_entryBytes{$ClusterFilterLabel=\"$Cluster\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Heap LRU Regions: Entry Bytes",
   "type": "table",
   "description": "$Cluster2: The amount of memory currently used by regions configured for eviction.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_entryBytes{$ClusterFilterLabel=\"$Cluster2\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Heap LRU Regions: Destroys",
   "type": "table",
   "description": "$Cluster: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Heap LRU Regions: Destroys",
   "type": "table",
   "description": "$Cluster2: Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=\"$Cluster2\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Heap LRU Regions: Evaluations",
   "type": "table",
   "description": "$Cluster: Number of entries evaluated during LRU operations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Heap LRU Regions: Evaluations",
   "type": "table",
   "description": "$Cluster2: Number of entries evaluated during LRU operations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=\"$Cluster2\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Heap LRU Regions: Evictions",
   "type": "table",
   "description": "$Cluster: Total number of entry evictions triggered by an LRU.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvictions{$ClusterFilterLabel=\"$Cluster\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Heap LRU Regions: Evictions",
   "type": "table",
   "description": "$Cluster2: Total number of entry evictions triggered by an LRU.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvictions{$ClusterFilterLabel=\"$Cluster2\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Heap LRU Regions: Greedy Returns",
   "type": "table",
   "description": "$Cluster: Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=\"$Cluster\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Heap LRU Regions: Greedy Returns",
   "type": "table",
   "description": "$Cluster2: Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=\"$Cluster2\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}