{
 "title": "Dual Functions",
 "tags": [
  "dual gemfire",
  "dual functions",
  "functions",
  "dual compute"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster: $Cluster",
   "type": "text",
   "description": "First cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 0 }
  },
  {
   "title": "Cluster2: $Cluster2",
   "type": "text",
   "description": "Second cluster selected from the pulldown menu",
   "gridPos": { "h": 1, "w": 11, "x": 12, "y": 0 }
  },
  { "title": "Function Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "$Cluster: Function Stats: Average Function Executions Completed Processing Time",
   "type": "timeseries",
   "description": "$Cluster: Average function executions completed processing latency.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}/gemfire_functionExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "{{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats: Average Function Executions Completed Processing Time",
   "type": "timeseries",
   "description": "$Cluster2: Average function executions completed processing latency.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}/gemfire_functionExecutionsCompleted{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "{{instance}} {{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats: Function Executions Completed",
   "type": "table",
   "description": "$Cluster: Number of function executions completed.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats: Function Executions Completed",
   "type": "table",
   "description": "$Cluster2: Number of function executions completed.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompleted{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats: Function Execution Calls",
   "type": "table",
   "description": "$Cluster: Number of function execution calls.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionCalls{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats: Function Execution Calls",
   "type": "table",
   "description": "$Cluster2: Number of function execution calls.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionCalls{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats: Function Executions Completed Processing Time",
   "type": "table",
   "description": "$Cluster: Total time took to complete function executions.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats: Function Executions Completed Processing Time",
   "type": "table",
   "description": "$Cluster2: Total time took to complete function executions.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats: Function Execution Exceptions",
   "type": "table",
   "description": "$Cluster: Number of function execution exceptions.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsExceptions{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats: Function Execution Exceptions",
   "type": "table",
   "description": "$Cluster2: Number of function execution exceptions.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsExceptions{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats: Function Executions Has Result Completed Processing Time",
   "type": "table",
   "description": "$Cluster: Total time took to process function executions with completed results.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsHasResultCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats: Function Executions Has Result Completed Processing Time",
   "type": "table",
   "description": "$Cluster2: Total time took to process function executions with completed results.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsHasResultCompletedProcessingTime{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats: Function Executions Has Result Running",
   "type": "table",
   "description": "$Cluster: Number of function executions with results that are currently running.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsHasResultRunning{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats: Function Executions Has Result Running",
   "type": "table",
   "description": "$Cluster2: Number of function executions with results that are currently running.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsHasResultRunning{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats:  Function Executions Running",
   "type": "table",
   "description": "$Cluster: Number of function executions that are currently running.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsRunning{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats:  Function Executions Running",
   "type": "table",
   "description": "$Cluster2: Number of function executions that are currently running.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionsRunning{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats:  Results Received",
   "type": "table",
   "description": "$Cluster: Number of results received.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_resultsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats:  Results Received",
   "type": "table",
   "description": "$Cluster2: Number of results received.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_resultsReceived{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Function Stats:  Results Sent To Result Collector",
   "type": "table",
   "description": "$Cluster: Number of results sent to result collector.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_resultsSentToResultCollector{$ClusterFilterLabel=\"$Cluster\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Stats:  Results Sent To Result Collector",
   "type": "table",
   "description": "$Cluster2: Number of results sent to result collector.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_resultsSentToResultCollector{$ClusterFilterLabel=\"$Cluster2\", category=\"FunctionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Function Executions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "$Cluster: Function Executions",
   "type": "table",
   "description": "$Cluster: Function stats",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionQueueSize{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionQueueThrottleCount{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionQueueThrottleTime{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreadJobs{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreadStarts{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreads{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster2: Function Executions",
   "type": "table",
   "description": "$Cluster2: Function stats",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_functionExecutionQueueSize{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionQueueThrottleCount{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionQueueThrottleTime{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreadJobs{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreadStarts{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_functionExecutionThreads{$ClusterFilterLabel=\"$Cluster2\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}