{
 "title": "00Main",
 "tags": [
  "hazelcast",
  "main"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Main Dashboard",
   "type": "text",
   "description": "The main dashboard of PadoGrid Hazelcast Dashboards (PHD) that resembles the main dashboard of Hazelcast Management Center (HMC). PHD includes additional metrics that are not available in HMC and vice versa. PHD exposes a finer degree of individual metric details along with federated cluster views making it more suitable for monitoring production systems.",
   "gridPos": { "h": 39, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "## Main\n\n- [Main Dashboard](/d/a310264b-af07-4113-a2ca-e40d86499d3a/00main?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Dual Main Dashboard](/d/c285e20e-3b2a-4108-bc28-69238459027a/00dual-main?var-DataSource=$DataSource&var-Cluster=$Cluster&var-Cluster2=$Cluster2&${__url_time_range})\n- [All Main Dashboard](/d/d3a660bb-5588-491e-849b-6e40b6c0de0e/00main-all?${__url_time_range})\n\n## Cluster\n\n- [Clients](/d/f4f0f36a-5cd4-4144-9660-2ea54b51a02b/clients?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Members](/d/fd8f9de0-3e83-4620-b060-bdbeec1ab8d5/members?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [WAN Replication](/d/b7bc088b-303b-493e-b05e-a3de801c2b00/wan?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Storage\n\n- [Maps](/d/bb1c5da7-87c5-428b-b51b-6aa6026c70f8/maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Map Column Charts](/d/cca4a1cb-94fa-44a3-b0ec-b2bf1c47c780/maps-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Map Colum Tables](/d/de404494-5da4-4734-bf81-931f90aa9d54/maps-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Map Row Charts](/d/f85a965f-c2ef-425a-98e0-ae4c4cdc695f/maps-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Map Row Tables](/d/bb1c5da7-87c5-428b-b51b-6aa6026c70f8/maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Map Query Charts](/d/ba66348a-5414-4633-912a-2556d33ea6fc/map-query-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Map Query Tables](/d/a05e07eb-ee7b-4d1f-ae8d-282d10b88053/map-query-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Replicated Maps](/d/d6cdea86-91be-4bd4-b9c2-1e949f708dd8/replicated-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Replicated Map Column Charts](/d/d6127a2b-8914-44a6-8e5c-37e29625b49c/replicated-maps-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Replicated Map Column Tables](/d/cb55eb96-8f2a-4495-93ec-939e6743847e/replicated-maps-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Replicated Map Row Charts](/d/da6b0ba1-fd16-4ccc-8ed1-e5ea7d51a14b/replicated-maps-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n    - [Replicated Map Row Tables](/d/d6cdea86-91be-4bd4-b9c2-1e949f708dd8/replicated-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Multi Maps](/d/fa09b005-c49f-442d-ba62-d6686cf2b1c4/multi-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Multi Map Column Charts](/d/b723efc3-306f-4f63-b195-2dc75fdef00d/multi-maps-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Multi Map Column Tables](/d/a703c9a8-f95f-4067-8301-a3679a7675d1/multi-maps-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Multi Map Row Charts](/d/e0a563db-e625-436f-90fd-40c7b9774609/multi-maps-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n   - [Multi Map Row Tables](/d/fa09b005-c49f-442d-ba62-d6686cf2b1c4/multi-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Lists](/d/efe7f2af-9568-48c0-bba4-616bccf374e1/lists?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Sets](/d/b30fa0d9-a425-41b6-b7e7-38c369598135/sets?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [PN Counters](/d/c6962d45-d7e9-485d-b7c6-95b8166127ae/pn-counters?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Flake ID Generators](/d/c7a9910c-cce1-4e27-af07-eb3ae873d312/flake-id-generators?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Partition\n\n- [Partitions](/d/ae378aa9-e0f4-42db-9272-0f318e783871/partitions?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Stream Processing\n\n- [Jet](/d/fb7526d0-9186-40d0-bb6f-e180b05f319f/jet?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Compute\n\n- [Executors](/d/b45f0c5f-aaf3-4296-ae6c-dd7a063c4e10/executors?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Messaging\n\n- [Queues](/d/bd37a375-e9c6-4754-954d-a11e796ef6f3/queues?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Reliable Topics](/d/e2dd6d49-64df-4681-97c5-d2b9aabb1a10/reliable-topics?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Topics](/d/d5a06e40-c713-4a03-ad55-c927b18af75f/topics?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## CP Subsystem\n\n- [CP Subsystem](/d/f0a23cf8-ae3f-4904-b0cc-9d42a23a0f2b/cp-subsystem?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n"
   }
  },
  {
   "title": "Cluster Up Time",
   "type": "stat",
   "description": "$Cluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 7, "w": 5, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_clusterUpTime{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory: Free, Map, Other Used (Aggregate)",
   "type": "piechart",
   "description": "$Cluster: Free memory vs. used memory",
   "gridPos": { "h": 7, "w": 5, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Map Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\"})-sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Other Used Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Partition Distribution",
   "type": "stat",
   "description": "$Cluster: Partitions owned by each member",
   "gridPos": { "h": 7, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\"}/com_hazelcast_Metrics_partitionCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap",
   "gridPos": { "h": 12, "w": 10, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate)",
   "type": "timeseries",
   "description": "$Cluster: CPU of the member that has the higest CPU load",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "$Cluster: System resource status",
   "gridPos": { "h": 20, "w": 20, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory/com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}