{
 "title": "Jet Job Details",
 "tags": [
  "hazelcast",
  "jet"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "JobName",
    "label": "Job Name",
    "query": {
     "query": "label_values(com_hazelcast_jet_Metrics_receivedCount,tag1)"
    }
   },
   {
    "name": "JobId",
    "label": "Job",
    "query": {
     "query": "label_values(com_hazelcast_jet_Metrics_receivedCount,tag0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Job Identifications",
   "type": "table",
   "description": "$Cluster: Jet jobs are uniquely identified by the Jet generated job IDs. In addition to Jet IDs, each job can be optionally set a unique job name by the application.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_executionStartTime{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Items Flow: $JobId",
   "type": "table",
   "description": "$Cluster: Max items/bytes read from the sources of the jobs, max items/bytes written to the sinks of the jobs.",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_jet_Metrics_distributedItemsIn{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(com_hazelcast_jet_Metrics_distributedItemsOut{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(com_hazelcast_jet_Metrics_distributedBytesIn{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(com_hazelcast_jet_Metrics_distributedBytesOut{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Received Count: $JobId",
   "type": "table",
   "description": "$Cluster: The number of received items. This number does not include watermarks, snapshot barriers etc. It’s the number of items the Processor.process method will receive.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_receivedCount{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Emitted Count: $JobId",
   "type": "table",
   "description": "$Cluster: The number of received items. This number does not include watermarks, snapshot barriers etc. It’s the number of items the Processor.process method will receive.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_emittedCount{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Items In: $JobId",
   "type": "table",
   "description": "$Cluster: Total number of items received from remote members.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_distributedItemsIn{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Bytes In: $JobId",
   "type": "table",
   "description": "$Cluster: Total number of bytes received from remote members.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_distributedBytesIn{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Items Out: $JobId",
   "type": "table",
   "description": "$Cluster: Total number of items sent to remote members.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_distributedItemsOut{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Items Out: $JobId",
   "type": "table",
   "description": "$Cluster: Total number of bytes sent to remote members.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_distributedBytesOut{$ClusterFilterLabel=\"$Cluster\", tag0=\"\\\"job=$JobId\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}