{
 "title": "Jet",
 "tags": [
  "hazelcast",
  "jet"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Jobs",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_submitted{job=\"$Cluster\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_completedSuccessfully{job=\"$Cluster\"}",
     "legendFormat": "Completed Successfully"
    },
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_completedWithFailure{job=\"$Cluster\"}",
     "legendFormat": "Failed"
    },
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_executionStarted{job=\"$Cluster\"}",
     "legendFormat": "Started"
    }
   ]
  },
  {
   "title": "Jobs: Submitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_submitted{job=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_executionStarted{job=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed Successfully",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_completedSuccessfully{job=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Jobs: Completed with Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "com_hazelcast_jet_Metrics_jobs_completedWithFailure{job=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}