{
 "title": "Map Query Tables",
 "tags": [
  "hazelcast",
  "query",
  "index",
  "map",
  "imap",
  "partitioned map"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "Query Count",
   "type": "table",
   "description": "$Cluster: Number of queries executed on the map (it may be imprecise for queries involving partition predicates (PartitionPredicate) on the off-heap storage)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexed Query Count",
   "type": "table",
   "description": "$Cluster: Total number of indexed local queries performed on the map",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Insert Count",
   "type": "table",
   "description": "$Cluster: Number of insert operations performed on the index",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_insertCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Insert Latency",
   "type": "table",
   "description": "$Cluster: Total latency of insert operations performed on the index",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalInsertLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Update Count",
   "type": "table",
   "description": "$Cluster: Number of update operations performed on the index",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_updateCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Update Latency",
   "type": "table",
   "description": "$Cluster: Total latency of update operations performed on the index",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalUpdateLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Remove Count",
   "type": "table",
   "description": "$Cluster: Number of remove operations performed on the index",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Remove Latency",
   "type": "table",
   "description": "$Cluster: Total latency of remove operations performed on the index",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Count",
   "type": "table",
   "description": "$Cluster: Total number of index hits (the value of this metric may be greater than the map.index.queryCount since a single query may hit the same index more than once)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hitCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Latency",
   "type": "table",
   "description": "$Cluster: Average hit latency for the index on each member",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_averageHitLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Query Count",
   "type": "table",
   "description": "$Cluster: Total number of queries served by the index",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Aveage Hit Selectivity",
   "type": "table",
   "description": "$Cluster: Average selectivity of the hits served by the index on this member (the returned value is in the range from 0.0 to 1.0 - values close to 1.0 indicate a high selectivity meaning the index is efficient; values close to 0.0 indicate a low selectivity meaning the index efficiency is approaching an efficiency of a simple full scan)",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_averageHitSelectivity{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost",
   "type": "table",
   "description": "$Cluster: Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_memoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}