{
 "title": "Map",
 "tags": [
  "hazelcast",
  "data structure",
  "map"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "MapType", "label": "Map Type", "query": "map" },
   {
    "name": "Map",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_entryCount{prefix=\"$MapType\"},tag0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Map: Entries, Memory ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Sum of the number of map entries owned by all members and sum of the memory cost of owned map entries by all members",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Entries"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "$Map: Operations/s ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Sum of the number of local put operations on the map divided by sum of the total latency of local put operations on the map",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalPutLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Puts/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalGetLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Gets/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Removes/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalSetLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Sets/s"
    }
   ]
  },
  {
   "title": "$Map: Dirty Entries ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Sum of the number of updated but not persisted yet entries, dirty entries, that the member owns",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_dirtyEntryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Dirty Entries"
    }
   ]
  },
  {
   "title": "$Map: Backup ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Sum of the number of backup entries held by the member divided by sum of the memory cost of backup entries in this member",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_backupEntryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Backup Entries"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Backup Memory"
    }
   ]
  },
  {
   "title": "$Map: Query ($MapType)",
   "type": "bargauge",
   "description": "$Cluster: Sum of the number of queries executed on the map (it may be imprecise for queries involving partition predicates (PartitionPredicate) on the off-heap storage) and sum of the total number of indexed local queries performed on the map",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Indexed Query Count"
    }
   ]
  },
  {
   "title": "$Map: Map Statistics ($MapType)",
   "type": "table",
   "description": "$Cluster: Individual statistics of the map",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Gets"
    },
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Puts"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Removals"
    },
    {
     "expr": "com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Sets"
    },
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Entry Memory"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Events"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "$Map: Map Throughput Statistics ($MapType)",
   "type": "table",
   "description": "$Cluster: Member local operations divided by member local total latency",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalPutLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Puts"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalGetLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}\n",
     "legendFormat": "Gets"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Removals"
    },
    {
     "expr": "com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalSetLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Sets"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPutLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalGetLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalSetLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    }
   ]
  },
  {
   "title": "$Map: Member Near Cache ($MapType)",
   "type": "table",
   "description": "$Cluster: Near cache statistics of the map",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "com_hazelcast_Metrics_misses{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Misses"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}/(com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}+com_hazelcast_Metrics_misses{job=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Effectiveness"
    },
    {
     "expr": "com_hazelcast_Metrics_expirations{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Evictions"
    },
    {
     "expr": "com_hazelcast_Metrics_evictions{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Evictions"
    },
    {
     "expr": "com_hazelcast_Metrics_invalidationRequests{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Invalidation Requests"
    },
    {
     "expr": "com_hazelcast_Metrics_persistenceCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Persistence Count"
    },
    {
     "expr": "com_hazelcast_Metrics_lastPersistenceKeyCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Persistence Keys"
    },
    {
     "expr": "com_hazelcast_Metrics_lastPersistenceDuration{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Persistence Duration"
    },
    {
     "expr": "com_hazelcast_Metrics_lastPersistenceTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"map.nearcache\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Persistence Time"
    }
   ]
  }
 ]
}