{
 "title": "Maps Columns",
 "tags": [
  "hazelcast",
  "data structure",
  "map",
  "imap",
  "partition map"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Maps: Entries",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Entries",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_backupEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Events",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Hits",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Locks",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_lockedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dirty Entries",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_dirtyEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}