{
 "title": "Multi Map",
 "tags": [
  "hazelcast",
  "data structure",
  "multimap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "myhz,myhz2" },
   {
    "name": "Map",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_entryCount,tag0)"
    }
   },
   { "name": "MapType", "label": "Map Type", "query": "map" }
  ]
 },
 "panels": [
  {
   "title": "$Map: Entries, Memory ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryCount{job=\"$Cluster\",prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Entries"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryMemoryCost{job=\"$Cluster\",prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "$Map: Operations/s ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_putCount{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalPutLatency{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Puts/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_getCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalGetLatency{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Gets/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_removeCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalRemoveLatency{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Removes/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_setCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalSetLatency{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Sets/s"
    }
   ]
  },
  {
   "title": "$Map: Dirty Entries ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_dirtyEntryCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Dirty Entries"
    }
   ]
  },
  {
   "title": "$Map: Backup ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_backupEntryCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Backup Entries"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_backupEntryMemoryCost{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Backup Memory"
    }
   ]
  },
  {
   "title": "$Map: Query ($MapType)",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_queryCount{job=\"$Cluster\",prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_indexedQueryCount{job=\"$Cluster\",prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Indexed Query Count"
    }
   ]
  },
  {
   "title": "$Map: Map Statistics ($MapType)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Gets"
    },
    {
     "expr": "com_hazelcast_Metrics_putCount{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Puts"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Removals"
    },
    {
     "expr": "com_hazelcast_Metrics_setCount{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Sets"
    },
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Entry Memory"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Events"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{job=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "$Map: Map Throughput Statistics ($MapType)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalPutLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Puts"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalGetLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}\n",
     "legendFormat": "Gets"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_totalRemoveLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Removals"
    },
    {
     "expr": "com_hazelcast_Metrics_setCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalSetLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Sets"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPutLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_putCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalGetLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_getCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_removeCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalSetLatency{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_setCount{job=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    }
   ]
  }
 ]
}