{
 "title": "Multi Maps Columns",
 "tags": [
  "hazelcast",
  "data structure",
  "multimap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Multi Maps: Entries",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Entry Memory",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Hits",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "MUlti Maps: Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Put Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Get Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Query Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Remove Count",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Put Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPutLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Set Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalSetLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Get Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalGetLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Remove Latency",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}