{
 "title": "Partitions",
 "tags": [
  "hazelcast",
  "partition"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterList" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Member Partitions",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completedMigrations{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_activePartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_replicaSyncRequestsCounter{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_replicaSyncSemaphore{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_stateStamp{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalCompletedMigrations{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedDestinationCommitTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedMigrationOperationTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedMigrationTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_runningPartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_publicationCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"event\",tag0=\"\\\"service=hz:core:partitionService\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_executedOperationsCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.partition\",tag0=~\".*partitionId=.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Partition Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Partition Threads: Operation",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedOperationCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Batch",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedOperationBatchCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Runnable",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedRunnableCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Partition Specific Runnable",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedPartitionSpecificRunnableCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_errorCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Error",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_errorCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Normal Pending",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_normalPendingCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Priority Pending",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_priorityPendingCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}