{
 "title": "Queues",
 "tags": [
  "hazelcast",
  "data structure",
  "queue"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Queues",
   "type": "table",
   "description": "$Cluster: Queue status",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Items",
   "type": "barchart",
   "description": "$Cluster: Number of owned and backup items in this member",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Age",
   "type": "barchart",
   "description": "$Cluster: Min, max, and average age of the items ",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Operations",
   "type": "barchart",
   "description": "$Cluster: Number of operations",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_total{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Events",
   "type": "timeseries",
   "description": "$Cluster: Number of event operations (duplicate of eventOperationCount)",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}