{
 "title": "Replicated Maps Rows",
 "tags": [
  "hazelcast",
  "data structure",
  "replicated map"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "myhz1,myhz2,wan1,wan2" },
   { "name": "Cluster2", "query": "wan2" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Replicated Maps: Entries",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Entry Memory",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Hits",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Events",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Put Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Get Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Remove Count",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Put Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxPutLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Get Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxGetLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Remove Latency",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxRemoveLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}