{
 "title": "System Resources",
 "tags": [
  "hazelcast",
  "resources",
  "memory",
  "os",
  "jvm",
  "performance",
  "latency",
  "throughput"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Cluster Up Time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_clusterUpTime{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory/com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Aggregates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "Memory: Free, Used (Aggregate)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Partition Distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max(com_hazelcast_Metrics_partitionCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "GC Count: Minor, Major (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"})",
     "legendFormat": "GC Minor Count"
    },
    {
     "expr": "max(jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"})",
     "legendFormat": "GC Major Count"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Used Heap (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Used Heap"
    }
   ]
  },
  {
   "title": "Used Native (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Max Physical Memory (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_freePhysical{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Physical Memory"
    },
    {
     "expr": "max(com_hazelcast_Metrics_totalPhysicalMemorySize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Total Physical Memory"
    }
   ]
  },
  {
   "title": "Thread Count (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_threadCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Active"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_peakThreadCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Peak"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_daemonThreadCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Daemon"
    }
   ]
  },
  {
   "title": "Committed Memory (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_committedHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Committed Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_committedNative{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Committed Native"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_committedVirtualMemorySize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Committed Virtual"
    }
   ]
  },
  {
   "title": "Memory Maps (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Primary Maps"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Backup Maps"
    }
   ]
  },
  {
   "title": "Total Swap Space (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_freeSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_totalSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "Max File Descriptors (Aggregate)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_openFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Open FD"
    },
    {
     "expr": "max(com_hazelcast_Metrics_maxFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Max FD"
    }
   ]
  },
  { "title": "Per Member", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Free Memory (Per Member)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freeMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Partition Distribution (Per Member)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Count: Minor, Major (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "{{instance}} Minor"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "{{instance}} Major"
    }
   ]
  },
  {
   "title": "System CPU Load (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Used"
    },
    {
     "expr": "com_hazelcast_Metrics_freeHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  },
  {
   "title": "Used Heap (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Native (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Physical Memory (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freePhysical{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPhysicalMemorySize{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": " {{instance}} Total"
    }
   ]
  },
  {
   "title": "Thread Count (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_threadCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Active"
    },
    {
     "expr": "com_hazelcast_Metrics_peakThreadCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Peak"
    },
    {
     "expr": "com_hazelcast_Metrics_daemonThreadCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Daemon"
    }
   ]
  },
  {
   "title": "Swap Space (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freeSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Free"
    },
    {
     "expr": "com_hazelcast_Metrics_totalSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Total"
    }
   ]
  },
  {
   "title": "File Descriptors (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_openFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Open"
    },
    {
     "expr": "com_hazelcast_Metrics_maxFileDescriptorCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}} Max"
    }
   ]
  }
 ]
}