{
 "title": "WAN",
 "tags": [
  "hazelcast",
  "wan"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "Cluster2", "query": "hazelcast" },
   {
    "name": "Wan",
    "label": "WAN",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster\"},tag1)"
    }
   },
   {
    "name": "WanPublisherId",
    "label": "Publisher",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster\", tag1=~\"\\\"replication=$Wan\\\"\"},tag0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "WAN Replication",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**WAN Standard:** *Standard WAN metrics included in Hazelcast.* **WAN Discovery Plugin:** *WAN plugin by Sorint.lab (reduces WAN endpoint discovery latency by 1000x)*"
   }
  },
  { "title": "WAN Standard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Members",
   "type": "table",
   "description": "$Cluster: WAN replication outbound queue status",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_queueFillPercent{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPublishLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPublishedEventCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayLastStart{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayLastEnd{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayTotalCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayTotalMillis{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Update Events",
   "type": "table",
   "description": "$Cluster: Number of entry update events",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_updateCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Remove Events",
   "type": "table",
   "description": "$Cluster: Number of entry remove events",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Sync Events",
   "type": "table",
   "description": "$Cluster: Number of entry sync events",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_syncCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dropped Entry Events",
   "type": "table",
   "description": "$Cluster: Number of dropped entry events",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_droppedCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN Discovery Plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAN Discovery: Live Endpoints",
     "type": "table",
     "description": "$Cluster: Number of live endpoints performing WAN replication",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{$ClusterFilterLabel=\"$Cluster\",type=\"DiscoveryService\"}",
       "legendFormat": "Live"
      }
     ]
    },
    {
     "title": "WAN Discovery: Dead Endpoints",
     "type": "table",
     "description": "$Cluster: Number of dead target endpoints that are not participating in WAN replication. As these endpoints become reachable, they are automatically moved to the live endpoint list.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{$ClusterFilterLabel=\"$Cluster\",type=\"DiscoveryService\"}",
       "legendFormat": "Dead"
      }
     ]
    },
    {
     "title": "WAN Discovery: All Endpoints",
     "type": "table",
     "description": "$Cluster: Total number of target endpoints configured for WAN replication",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{$ClusterFilterLabel=\"$Cluster\",type=\"DiscoveryService\"}",
       "legendFormat": "All"
      }
     ]
    }
   ]
  }
 ]
}