global:
  scrape_interval:     5s
  external_labels:
    monitor: 'gemfire'

scrape_configs:
  - job_name: 'locator-mygemfire'
    file_sd_configs:
      - files:
        - locator-mygemfire-targets.yml
  - job_name: 'mygemfire'
    file_sd_configs:
      - files:
        - mygemfire-targets.yml

  - job_name: 'locator-mygemfire2'
    file_sd_configs:
      - files:
        - locator-mygemfire2-targets.yml
  - job_name: 'mygemfire2'
    file_sd_configs:
      - files:
        - mygemfire2-targets.yml
