#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh > /dev/null

EXECUTABLE="`basename $0`"
SECRET_FILE=overlay-base/cm-adapter-serving-certs.yaml

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
    $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Builds the Hazelcast CRC environment.

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Builds the Hazelcast CRC environment by downloading the latest Hazelcast template.

EOF
fi

oc new-project $APP_NAME
