#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$1" == "-?" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Start padogrid pod

SYNOPSIS
   $EXECUTABLE [storage_class] [-?]

DESCRIPTION
   Launches a PadoGrid pod with the name 'padogrid'. Padogrid keeps workspaces in the '/opt/padogrid/workspaces'
   directory. You can optionally mount that directory to a persistent volume as follows.

   CRC - For CRC, the storage_class value must be 'local_storage'. If unspecified, then the persistent volume claim
         is not made.

   OCP - For OCP, you can specify any available storage class. If not specified then the default storage
        class is assigned.

   Execute the following command to list the available storage classes.

      oc get storageclass

OPTIONS
   storage_class
             The specified storage class is used as the Storage Class for the 'paodgrid-pvc' Persistent
             Volume Claim. If you are connected to CRC, then you must specify 'local-storage'. The 'local-storeage'
             persistent volumes must also be created beforehand as described in the 'README-crc.md' file.
             
             If this option is not specified, then the default storage class is assigned. For CRC, the
             default storage classs is undefined, and therefore, the persistent volume claim is not made
             and the container file system is used instead. For this to work, you must add user to 
             anyuid SCC as described in the 'README-crc.md' file.

SEE ALSO
   padogrid/padogrid.yaml, padogrid/padogrid-no-pvc.yaml

EOF
exit
fi

echo -e "Project: ${CLightGreen}${APP_NAME}${CNone}"

CURRENT_PROJECT=$(oc project -q)
if [ "$CURRENT_PROJECT" != "$APP_NAME" ]; then
   oc project $APP_NAME
fi

DEFAULT_STORAGE_CLASS_NAME=$(oc get storageclass | grep default | awk '{print $1}')
STORAGE_CLASS_NAME="$1"
if [ "$STORAGE_CLASS_NAME" == "" ]; then
   STORAGE_CLASS_NAME=$DEFAULT_STORAGE_CLASS_NAME
fi

HAZELCAST_SERVICE="$(oc get svc | grep -i ClusterIP | grep 5701 | awk '{ print $1 }')"

if [ "$HAZELCAST_SERVICE" == "" ]; then
  HAZELCAST_SERVICE="$PROJECT_NAME-hazelcast-enterprise"
fi

if [ "$STORAGE_CLASS_NAME" == "" ]; then
  oc process -p HAZELCAST_SERVICE=$HAZELCAST_SERVICE -f $APP_DIR/padogrid/padogrid-no-pvc.yaml -o yaml | oc create -f -
else
  oc process -p HAZELCAST_SERVICE=$HAZELCAST_SERVICE -f $APP_DIR/padogrid/padogrid.yaml -o yaml -p=STORAGE_CLASS_NAME=$STORAGE_CLASS_NAME | oc create -f -
fi
