#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE [-oss | -rhel] [-?]

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Starts the Hazelcast cluster configured by the 'build_app' script. If no options are specified then
   it automatically determines the environment based on the workspace setup. If IMDG_LICENSE_KEY is defined
   then it run docker.io Hazelcast Enterprise. To turn RHEL, specify the '-rhel' option. Note that if
   IMDG_LICENSE_KEY is not defined then it runs Hazelcast OSS regardless of any options specified.

OPTIONS
   -oss
             If specified then starts Hazelcast OSS. 

   -rhel
             If specified then launches the image downloaded from Hazelcast Enterprise Red Hat. To use this option,
             you must first create an OpenShift secret for image pull. Please see the accompanied READE.md
             for details. If IMDG_LICENSE_KEY is not defined then this option is ignored and the '-oss' option
             is used instead.

DEFAULT:
   ./$EXECUTABLE

SEE ALSO
   https://github.com/hazelcast/hazelcast-code-samples/tree/master/hazelcast-integration/openshift/hazelcast-cluster

EOF
exit
fi

echo -e "Project: ${CLightGreen}${APP_NAME}${CNone}"

CURRENT_PROJECT=$(oc project -q)
if [ "$CURRENT_PROJECT" != "$APP_NAME" ]; then
   oc project $APP_NAME
fi

pushd $APP_DIR/hazelcast > /dev/null

IS_ENTERPRISE="false"
if [ "$OSS" == "true" ] || [ "$IMDG_LICENSE_KEY" == "" ]; then
  HAZELCAST_YAML="hazelcast.yaml"
elif [ "$RHEL" == "true" ]; then
  IS_ENTERPRISE="true"
  HAZELCAST_YAML="hazelcast-enterprise-rhel.yaml"
else
  IS_ENTERPRISE="true"
  HAZELCAST_YAML="hazelcast-enterprise.yaml"
fi

# Create cluster role
echo "Applying RBAC..."
oc apply -f rbac.yaml

echo ""
echo -e "Hazelcast configuration: ${CLightGreen}hazelcast/${HAZELCAST_YAML}${CNone}"
echo ""
if [ "$IS_ENTERPRISE" == "true" ]; then
   if [ "$RHEL" == "true" ]; then
      echo -e "Starting ${CLightGreen}Hazelcast Enterprise RHEL${CNone}..."
   else
      echo -e "Starting ${CLightGreen}Hazelcast Enterprise${CNone}..."
   fi
   oc create secret generic hz-enterprise-license --from-literal=key=$IMDG_LICENSE_KEY
   oc new-app -f $HAZELCAST_YAML -p NAMESPACE=$(oc project -q) -p ENTERPRISE_LICENSE_KEY=$IMDG_LICENSE_KEY -p HAZELCAST_REPLICAS=$MEMBER_COUNT
else
   echo -e "Starting ${CLightGreen}Hazelcast OSS${CNone}..."
   oc create secret generic hz-enterprise-license --from-literal=key=$IMDG_LICENSE_KEY
   oc new-app -f hazelcast.yaml -p NAMESPACE=$(oc project -q)
fi

# Create the load balancer service
echo "Creating services..."
oc apply -f service-lb.yaml
oc apply -f service-lb-pods.yaml

# Expose the Hazelcast and Management Center service.
echo "Exposing services (routes)..."
oc expose svc/hazelcast-service-lb
let LAST_MEMBER_NUM=MEMBER_COUNT-1
for i in $(seq 0 $LAST_MEMBER_NUM); do
   oc expose svc/hazelcast-service-$i
done
if [ "$IMDG_LICENSE_KEY" != "" ] && [ "$OSS" == "false" ]; then
   oc expose svc/management-center-service
fi
echo ""
echo "One (1) service for headless cluster IP and $MEMBER_COUNT services for pods exposed."
echo "In addition to these services, to expose NodePort services, execute the following:"
echo "   oc apply -f ../hazelcast/service-nodeport.yaml"
echo "   oc apply -f ../hazelcast/service-nodeport-pods.yaml"
echo "   oc expose svc/hazelcast-service-nodeport"
for i in $(seq 0 $LAST_MEMBER_NUM); do
   echo "   oc expose svc/hazelcast-service-nodeport-$i"
done
echo ""
echo "Services expose external IPs so that external applications can connect to the Hazelcast cluster by"
echo "configuring Smart Client. If Smart Client does not work, then your OpenShift cluster has been"
echo "configured to block external IPs from being created. If you must use Smart Client then please"
echo "consult your OpenShift administrator to lift this restriction. If Smart Client is not an option,"
echo "then you can use Dummy Client instead."
echo ""
echo "You can also use the PadoGrid container to connect to the Hazelcast cluster. The PadoGrid container"
echo "uses the Kuberntees DNS service to connect to the Hazelcast cluster as Smart Client."
echo ""
echo "Please see ../README.md for instructions on how to configure and run Hazelcast clients."
echo ""
popd > /dev/null
