#!/usr/bin/env bash
SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

NAME
   $EXECUTABLE - Delete all resources

SYNOPSIS
   $EXECUTABLE [-?]

DESCRIPTION
   Deletes all Hazelccast resources.

EOF
exit
fi

# Delete Hazelcast
if [ "$OSS" == "true" ]; then
   echo "Deleting OSS resources..."
else
   echo "Deleting Enterprise resources..."
fi

# To delete all resource objects:
pushd $APP_DIR/hazelcast > /dev/null

oc delete route hazelcast-service-lb --namespace=$APP_NAME
oc delete -f service-lb.yaml --namespace=$APP_NAME
oc delete -f service-pods.yaml --namespace=$APP_NAME
oc delete all,configmap,pvc,serviceaccount,rolebinding --selector app=hazelcast -l template=hazelcast-openshift-template --namespace=$APP_NAME
oc delete route,svc --all --namespace=$APP_NAME
oc delete -f rbac.yaml

popd > /dev/null
