#!/usr/bin/env bash 

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-product -k8s -cluster -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

PRODUCT_OPTIONS=$(echo "$K8S_PRODUCT_LIST" | sed 's/ /|/g')
PRODUCTS_SUPPORTED=$(echo "$K8S_PRODUCT_LIST" | sed 's/ /, /g')
THIS_PRODUCT="$(basename $(dirname $SCRIPT_DIR))"
K8S_OPTIONS="$(echo $(getK8sOptions $THIS_PRODUCT) | sed 's/ /|/g')"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Create a Kubernetes environment in the current padogrid workspace

SYNOPSIS
   $EXECUTABLE [-product $PRODUCT_OPTIONS]
              [-k8s $K8S_OPTIONS]
              -cluster cluster_name
              [-?]

DESCRIPTION
   Creates a Kubernetes environment that includes Geode deployment files for
   one of the following cloud platforms:
 
   minikube  Minikube on your laptop or PC

   To use the created environment, you must have access to one of the platforms
   with all the required software installed and a valid account. Each environment
   comes with a document describing the prerequisites and detailed instructions.

OPTIONS
   -product $PRODUCT_OPTIONS
             Kubernetes cluster product name. Supported products are $PRODUCTS_SUPPORTED.

   -k8s minikube
             Minikube on your local machine.

   -cluster cluster_name
             Required Kubernetes cluster name. This name is used to create a cluster in
             the cloud platform if it does not exist.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -product $THIS_PRODUCT -k8s $DEFAULT_K8S -cluster cluster_name

FILES
   $PADOGRID_WORKSPACE/k8s
             The current workspace Kubernetes directory.

EOF
fi
   exit
fi

#
# Run the target k8s command if the product is different.
#
if [ "$PRODUCT_ARG" != "" ]; then
   if [ "$(containsWord "$K8S_PRODUCT_LIST" "$PRODUCT_ARG")" == "false" ]; then
      >&2 echo -e "${CLightRed}ERROR:${CNone} Specified product is not supported: [$PRODUCT_ARG]. Command aborted."
      exit 1
   fi
   if [ "$THIS_PRODUCT" != "$PRODUCT_ARG" ]; then
      if [ "$PRODUCT_ARG" == "jet" ]; then
         PRODUCT_ARG="hazelcast"
      fi
      $PADOGRID_HOME/$PRODUCT_ARG/bin_sh/$EXECUTABLE "$@"
      exit
   fi
fi

echo "$EXECUTABLE not supported for $THIS_PRODUCT in this PadoGrid release. Use '-product' to specify another product."
