#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-cluster -num -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Stop the specified locator in the specified cluster

SYNOPSIS
   $EXECUTABLE [-cluster cluster_name] [-num locator_number] [-?]


DESCRIPTION
   Stops the specified SnappyData locator.

   For VM clusters, the locator number reflects the host in the order it is
   defined by the cluster property, 'vm.locator.hosts', in the 'etc/cluster.properties'
   file. (Run 'show_cluster -long' to see the VM locator numbers that map to hosts.)

   -cluster cluster_name
             Cluster name.

   -num locator_number
             Locator number 1-5
EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -cluster $CLUSTER -num $MEMBER_NUM

FILES
   $CLUSTER_DIR/etc/cluster.properties
             The current cluster configuration file.

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "*locator*" $EXECUTABLE
   exit
fi

# Get workspace name
WORKSPACE=${PADOGRID_WORKSPACE##*/}

#
# VM cluster
#
VM_ENABLED=`getClusterProperty "vm.enabled" "false"`
if [ "$REMOTE_SPECIFIED" == "false" ]; then
   if [ "$VM_ENABLED" == "true" ]; then
      VM_LOCATOR_HOSTS=`getClusterProperty "vm.locator.hosts"`
      if [ "$VM_LOCATOR_HOSTS" == "" ]; then
         echo "ERROR: VM locator hosts undefined. Set 'vm.locator.hosts' in the following cluster.properties file."  
         echo "       $ETC_DIR/cluster.properties"
         echo "       Command aborted."
         exit 1
      fi
      # Replace , with space
      __VM_HOSTS=$(echo "$VM_LOCATOR_HOSTS" | sed "s/,/ /g")
      DEFAULT_USER=$(whoami)
      VM_USER=`getClusterProperty "vm.user" "$DEFAULT_USER"`
      VM_KEY=`getClusterProperty "vm.privateKeyFile"`
      if [ "$VM_KEY" != "" ]; then 
         VM_KEY="-i $VM_KEY"
      fi

      # Determine the host
      __LOCATOR_NUMBER=0
      __FOUND="false"
      
      for VM_HOST in $__VM_HOSTS; do
         let __LOCATOR_NUMBER=__MEMBER_NUMBER+1
         if [ $__LOCATOR_NUMBER -eq $MEMBER_NUM_NO_LEADING_ZERO ]; then
            __FOUND="true"
            ssh -q -n $VM_KEY $VM_USER@$VM_HOST -o stricthostkeychecking=no "$COMMAND_PREFIX $VM_PADOGRID_HOME/$PRODUCT/bin_sh/stop_locator -cluster $CLUSTER -remote $VM_HOST -workspace $VM_PADOGRID_WORKSPACE -num 1"
            break;
         fi
      done
      FIRST_NUMBER=1
      LAST_NUMBER=$__LOCATOR_NUMBER
      if [ "$__FOUND" == "false" ]; then
         echo "ERROR: Invalid locator number. Valid range is [$FIRST_NUMBER, $LAST_NUMBER]. Command aborted." 
      fi
      exit
   fi
fi

#
# Local cluster
#

POD=`getClusterProperty "pod.name" "local"`
NODE_NAME_PRIMARY=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
NODE_NAME_PREFIX=$NODE_NAME_PRIMARY

if  [ ! -d $CLUSTER_DIR ]; then
   echo "----------------------------------------------------------------"
   echo "Cluster: $CLUSTER"
   echo " Status: This cluster has not been created. Please run the create_cluster command to"
   echo "         to create the cluster before running this command."
   echo "----------------------------------------------------------------"
   exit 1
fi

if [ "$MEMBER_NUM_SPECIFIED" == "false" ]; then
   echo "ERROR: Locator number not specified. Run 'stop_locator -?' to see usage. Command aborted."
   exit 1
fi


if [ "$POD" != "local" ]; then
   PRIMARY_NODE_NAME=`getPodProperty "node.name.primary" "$DEFAULT_NODE_NAME_PRIMARY"`
   NODE_LOCAL="${PRIMARY_NODE_NAME}.local"
   if [ "$REMOTE_SPECIFIED" == "false" ]; then
      ssh -q -n $SSH_USER@$NODE_LOCAL -o stricthostkeychecking=no "$COMMAND_PREFIX $REMOTE_BASE_DIR/$PRODUCT/bin_sh/$EXECUTABLE -cluster $CLUSTER -remote $NODE_LOCAL -workspace $PADOGRID_WORKSPACE $*;"
      exit
   fi
   REMOTE_SPECIFIED="false"
fi

LOCATOR_NUMBER=$MEMBER_NUM
LOCATOR=`getLocatorName $LOCATOR_NUMBER`
LOCATOR_DIR=$RUN_DIR/$LOCATOR
if [[ ${OS_NAME} == CYGWIN* ]]; then
   LOCATOR_DIR="$(cygpath -wp "$LOCATOR_DIR")"
fi

PID=`getLocatorPid $LOCATOR $WORKSPACE`
if [ -z "${PID}" ]; then
   echo "----------------------------------------------------------------"
   echo " WORKSPACE: $PADOGRID_WORKSPACE"
   echo "   Cluster: $CLUSTER"
   if [ "$VM_ENABLED" == "true" ]; then
   echo "Deployment: VM"
   else
   echo "       Pod: $POD"
   fi
   echo "   Locator: $LOCATOR"
   echo "    Status: Locator is already stopped [Locator: $LOCATOR]. Command aborted."
   echo "----------------------------------------------------------------"
   exit 0
else
   snappy locator stop -dir=$LOCATOR_DIR
   echo "----------------------------------------------------------------"
   echo "  WORKSPACE: $PADOGRID_WORKSPACE"
   echo "    Cluster: $CLUSTER"
   if [ "$VM_ENABLED" == "true" ]; then
   echo " Deployment: VM"
   else
   echo "        Pod: $POD"
   fi
   echo "        Pod: $POD"
   echo "    Locator: $LOCATOR"
   echo "        PID: $PID"
   echo "     Status: Stopped"
   echo "Working Dir: $LOCATOR_DIR"
   echo "----------------------------------------------------------------"
fi
