#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

BASE_DIR="$(dirname "$SCRIPT_DIR")"

EXECUTABLE="`basename $0`"

__options()
{
   echo "-?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Display missing disk stores

SYNOPSIS
   ./$EXECUTABLE [-?]

DESRIPTION
   Displays missing disk stores.

DEFAULT:
   ./$EXECUTABLE

EOF
exit
fi

if [ "$TIMESTAMP" == "" ]; then
   TIMESTAMP=`date +%y%m%d-%H%M%S`
fi

# Trap Ctrl-C
LAST_TIMESTAMP_TRAP=0
trap 'cleanExit "$EXECUTABLE" "$TIMESTAMP" "false"' INT

FILTER1="stale data"
FILTER2="missing-disk-store"

TMP_FILE="/tmp/padogrid-$EXECUTABLE-$TIMESTAMP.log"
pushd $LOG_DIR > /dev/null 2>&1
grep . $LOCATOR_FILES | sed -n -e "/$FILTER1/,/$FILTER2/p" | sed -e '/\[$/d' -e '/\]$/d' -e '/My persistent id/d' > $TMP_FILE
grep . $SERVER_FILES | sed -n -e "/$FILTER1/,/$FILTER2/p" >> $TMP_FILE

echo ""
echo "Missing Disk Stores"
echo "-------------------"
line_count=0
log_file=""
while IFS= read -r line; do
   prev_log_file="$log_file"
   let line_count=line_count+1
   log_file=$(echo $line | sed 's/:.*$//')
   if [ "$log_file" != "$prev_log_file" ]; then
      echo "$log_file"
   fi
   if [[ "$line" == *"$FILTER1"* ]]; then
      timestamp=$(echo $line | sed -e "s/$log_file://" -e 's/^.*info //' -e "s/$CLUSTER.*$//"  -e 's/info.*//i')
      region=$(echo $line | grep Region | sed -e 's/^.* Region //' -e 's/has potentially stale data.*$//')
      buckets=$(echo $line | grep Buckets | sed -e 's/^.*Buckets //' -e 's/\].*$//')
      echo "$TTee $timestamp"
   else
      case $line_count in
      2)
         diskstore_id=$(echo $line | sed 's/.*DiskStore ID: //')
         ;;
      3)
         name=$(echo $line | sed 's/.*Name: //')
         echo "$TBar   $TTee $name"
         if [ "$region" != "" ]; then
            echo "$TBar   $TBar   $TTee  region: $region"
         fi
         echo "$TBar   $TBar   $TTee      id: $diskstore_id"
         if [ "$buckets" != "" ]; then
            echo "$TBar   $TBar   $TTee buckets: $buckets"
         fi
         ;;
      4)
         location=$(echo $line | sed 's/.*Location: //')
         address=$(echo $location | sed -e 's/:.*$//' -e 's/\///g')
         echo "$TBar   $TBar   $TLel    addr: $address"
         ;;
      *)
         if [ $line_count -gt 5 ]; then
            offline_disk_store_id=$(echo $line | grep 'DiskStore ID:' | sed 's/.*DiskStore ID: //')
            name=$(echo $line | grep 'Name:' | sed 's/.*Name: //')
            offline_location=$(echo $line | grep 'Location:' | sed 's/.*Location: //')
            offline_address=$(echo $offline_location | sed -e 's/:.*$//' -e 's/\///g')
            buckets=$(echo $line | grep 'Buckets:' | sed -e 's/^.*Buckets: //')
            end_line=$(echo $line | grep "$FILTER2")
            if [ "$end_line" != "" ]; then
               line_count=0
            elif [ "$offline_disk_store_id" != "" ]; then
               echo -e "$TBar   $TTee ${CError}offline${CNone}"
               echo "$TBar   $TBar   $TTee      id: $offline_disk_store_id"
            elif [ "$name" != "" ]; then
               echo "$TBar   $TBar   $TTee    name: $name"
            elif [ "$offline_address" != "" ]; then
               echo "$TBar   $TBar   $TTee    addr: $offline_address"
            elif [ "$buckets" != "" ]; then
               echo "$TBar   $TBar   $TTee buckets: $buckets"
            fi
         fi
         ;;
      esac
   fi
done < "$TMP_FILE"
unset IFS
popd > /dev/null 2>&1

echo -e "Now: ${CBrownOrange}$(date '+%Y/%m/%d %H:%M:%S %Z')${CNone}"
echo ""

cleanExit "$EXECUTABLE" "$TIMESTAMP" "true"
