{
 "title": "00Dual Main",
 "tags": [
  "dual hazelcast",
  "dual main"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dual Main Dashboard",
   "type": "text",
   "description": "The main dashboard of PadoGrid Hazelcast Dashboards (PHD) that resembles the main dashboard of Hazelcast Management Center (HMC). PHD includes additional metrics that are not available in HMC and vice versa. PHD exposes a finer degree of individual metric details along with federated cluster views making it more suitable for monitoring production systems.",
   "gridPos": { "h": 42, "w": 4, "x": 0, "y": 0 },
   "options": {
    "content": "## Main\n\n- [Main Dashboard](/d/a310264b-af07-4113-a2ca-e40d86499d3a/00main?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Dual Main Dashboard](/d/c285e20e-3b2a-4108-bc28-69238459027a/00dual-main?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [All Main Dashboard](/d/d3a660bb-5588-491e-849b-6e40b6c0de0e/00main-all?${__url_time_range})\n\n## Cluster\n\n- [Dual Clients](/d/ccddc68e-cf1e-4896-aa6b-e794f5e51691/dual-clients?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Members](/d/fb143ccd-29eb-4418-9705-fd3dfa789df1/dual-members?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual WAN Replication](/d/db14568e-0a85-41b7-bf63-5b4f8af7e7b3/dual-wan?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Storage\n\n- [Dual Maps](/d/e995b5f9-e8e6-4d5e-939d-0d30a178d7cd/dual-maps?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Map Column Charts](/d/d9e1d6fa-67e7-4940-8910-ccd06c353b39/dual-maps-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Map Colum Tables](/d/f6b5b417-cdd7-4c32-aad4-6074a78ef260/dual-maps-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Map Row Charts](/d/a5f78c11-24cb-4ab5-b9fc-3216df2801ca/dual-maps-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Map Row Tables](/d/e9d8dd03-7fcd-49ba-9c95-9000f1d59b73/dual-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Map Query Charts](/d/b64f2bb7-e5fb-44a7-a324-ba0ab877e7a9/dual-map-query?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Map Query Tables](/d/d9ce38e6-a110-47b6-968f-9dba5b993645/dual-map-query-tables?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Replicated Maps](/d/f864dbf7-2af1-4037-965c-bf8e86f51fb9/dual-replicated-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Dual Replicated Map Column Charts](/d/d8b65d59-bcc8-4631-8a3c-965ddcf7c699/dual-replicated-maps-columns-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Dual Replicated Map Column Tables](/d/cc529285-71e7-4f33-ae1d-77a9c1612548/dual-replicated-maps-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Dual Replicated Map Row Charts](/d/e21abd9c-29fc-4e84-b20c-277d8be72fab/dual-replicated-maps-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n    - [Dual Replicated Map Row Tables](/d/f864dbf7-2af1-4037-965c-bf8e86f51fb9/dual-replicated-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Multi Maps](/d/d8995d82-19cb-4e79-802e-d93342224ef2/dual-multi-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Multi Map Column Charts](/d/e52a5f5a-486f-440d-a3e4-4d482c64a3cc/dual-multi-maps-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Multi Map Column Tables](/d/a703c9a8-f95f-4067-8301-a3679a7675d1/multi-maps-columns?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Multi Map Row Charts](/d/e52a5f5a-486f-440d-a3e4-4d482c64a3cc/dual-multi-maps-rows-charts?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n   - [Dual Multi Map Row Tables](/d/d8995d82-19cb-4e79-802e-d93342224ef2/dual-multi-maps-rows?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Lists](/d/d874784d-e623-4014-baed-a72df304c53b/dual-list?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Sets](/d/b2350070-8f13-4930-8d4b-ac4efd30baa6/dual-sets?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual PN Counters](/d/a49dafe7-fc51-4205-84be-548938b3058d/dual-pn-counter?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Flake ID Generators](/d/a01f86b6-bf98-4318-8d6d-e845cfcf81a8/dual-flake-id-generators?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Dual Partition\n\n- [Dual Partitions](/d/c885e0e0-8c0d-4018-bd21-6d9adf5871f9/dual-partitions?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Stream Processing\n\n- [Dual Jet](/d/cd524a57-aea5-4ec6-b421-973f65f2c167/dual-jet?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Compute\n\n- [Dual Executors](/d/b01d2d5b-5bf2-4bca-adb5-ec3d9a87a393/dual-executors?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## Messaging\n\n- [Dual Queues](/d/ced332c9-c270-4d1b-aaef-afbfe4de47a8/dual-queues?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Reliable Topics](/d/b83c015b-defe-4aa6-92a4-825df356e3b4/dual-reliable-topics?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n- [Dual Topics](/d/f8de4eee-b224-44dd-a30c-0a5ed4c1d903/dual-topics?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})\n\n## CP Subsystem\n\n- [Dual CP Subsystem](/d/c6426a21-20fc-4e61-8b8f-46fbcd5d10d0/dual-cp-subsystem?var-DataSource=$DataSource&var-Cluster=$Cluster&var-DataSource2=$DataSource2&var-Cluster2=$Cluster2&${__url_time_range})"
   }
  },
  {
   "title": "Cluster Up Time ($Cluster)",
   "type": "stat",
   "description": "$Cluster: Cluster up time determined by the oldest member",
   "gridPos": { "h": 7, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_clusterUpTime{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory: Free, Used (Aggregate) ($Cluster)",
   "type": "piechart",
   "description": "$Cluster: Free memory vs. used memory. For sustained performance, used memory should be below 80%.",
   "gridPos": { "h": 7, "w": 4, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Map Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\"})-sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Other Used Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeMemory{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Partition Distribution ($Cluster)",
   "type": "stat",
   "description": "$Cluster: Partitions owned by each member",
   "gridPos": { "h": 7, "w": 4, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\"}/com_hazelcast_Metrics_partitionCount{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster Up Time ($Cluster2)",
   "type": "stat",
   "description": "$Cluster2: Cluster up time determined by the oldest member",
   "gridPos": { "h": 7, "w": 2, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_clusterUpTime{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory: Free, Used (Aggregate) ($Cluster2)",
   "type": "piechart",
   "description": "$Cluster2: Free memory vs. used memory",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Map Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\"})-sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Other Used Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeMemory{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Partition Distribution ($Cluster2)",
   "type": "stat",
   "description": "$Cluster2: Partitions owned by each member",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster2\"}/com_hazelcast_Metrics_partitionCount{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap",
   "gridPos": { "h": 12, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: CPU of the member that has the higest CPU load",
   "gridPos": { "h": 12, "w": 5, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max (Aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Free, used, and max heap. For sustained performance, used heap should be below 80% of max heap.",
   "gridPos": { "h": 12, "w": 5, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Max System CPU Load (Aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: CPU of the member that has the max CPU load",
   "gridPos": { "h": 12, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Members ($Cluster)",
   "type": "table",
   "description": "$Cluster: System resource status",
   "gridPos": { "h": 23, "w": 10, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory/com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: System resource status",
   "gridPos": { "h": 23, "w": 10, "x": 14, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory/com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{$ClusterFilterLabel=\"$Cluster2\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster2\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster2\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster2\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=\"$Cluster2\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}