{
 "title": "Dual CP Subsystem",
 "tags": [
  "hazelcast",
  "cp",
  "cp subsystem"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterList" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "label": "Cluster 2", "query": "hazelcast" }
  ]
 },
 "panels": [
  {
   "title": "CP Subsystem: Executors ($Cluster)",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedTasks{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Completed Tasks"
    },
    {
     "expr": "com_hazelcast_Metrics_maximumPoolSize{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Max Pool Size"
    },
    {
     "expr": "com_hazelcast_Metrics_poolSize{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "com_hazelcast_Metrics_queueSize{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Queue Size"
    },
    {
     "expr": "com_hazelcast_Metrics_remainingQueueCapacity{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Queue Capacity"
    }
   ]
  },
  {
   "title": "CP Subsystem: Executors ($Cluster2)",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedTasks{$ClusterFilterLabel=\"$Cluster2\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Completed Tasks"
    },
    {
     "expr": "com_hazelcast_Metrics_maximumPoolSize{$ClusterFilterLabel=\"$Cluster2\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Max Pool Size"
    },
    {
     "expr": "com_hazelcast_Metrics_poolSize{$ClusterFilterLabel=\"$Cluster2\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Pool Size"
    },
    {
     "expr": "com_hazelcast_Metrics_queueSize{$ClusterFilterLabel=\"$Cluster2\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Queue Size"
    },
    {
     "expr": "com_hazelcast_Metrics_remainingQueueCapacity{$ClusterFilterLabel=\"$Cluster2\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"}",
     "legendFormat": "Queue Capacity"
    }
   ]
  },
  {
   "title": "Completed Tasks ($Cluster)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_completedTasks{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"})",
     "legendFormat": "Completed Tasks"
    }
   ]
  },
  {
   "title": "Completed Tasks ($Cluster2)",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_completedTasks{$ClusterFilterLabel=\"$Cluster2\",prefix=\"executor.internal\", tag0=\"\\\"name=hz:cpSubsystemManagement\\\"\"})",
     "legendFormat": "Completed Tasks"
    }
   ]
  }
 ]
}