{
 "title": "Dual Map Query",
 "tags": [
  "dual hazelcast",
  "map",
  "imap",
  "partitioned map",
  "query"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterList" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "label": "Cluster 2", "query": "hazelcast" }
  ]
 },
 "panels": [
  {
   "title": "Map Query Count (aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "mw/customers and nw/orders queries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Map Query Count (aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "mw/customers and nw/orders queries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Map Indexed Query Count (aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "mw/customers and nw/orders queries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Map Indexed Query Count (aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "mw/customers and nw/orders queries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_indexedQueryCount{$ClusterFilterLabel=\"$Cluster2\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}