{
 "title": "Dual Partitions",
 "tags": [
  "partition",
  "dual hazelcast"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Member Partitions ($Cluster)",
   "type": "table",
   "description": "$Cluster: Partition status across all members",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completedMigrations{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_activePartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_replicaSyncRequestsCounter{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_replicaSyncSemaphore{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_stateStamp{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalCompletedMigrations{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedDestinationCommitTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedMigrationOperationTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedMigrationTime{$ClusterFilterLabel=\"$Cluster\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_runningPartitionCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_publicationCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"event\",tag0=\"\\\"service=hz:core:partitionService\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_executedOperationsCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.partition\",tag0=~\".*partitionId=.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Member Partitions ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Partition status across all members",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completedMigrations{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_activePartitionCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_replicaSyncRequestsCounter{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_replicaSyncSemaphore{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_stateStamp{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalCompletedMigrations{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedDestinationCommitTime{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedMigrationOperationTime{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalElapsedMigrationTime{$ClusterFilterLabel=\"$Cluster2\", prefix=\"partitions\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_runningPartitionCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_publicationCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"event\",tag0=\"\\\"service=hz:core:partitionService\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_executedOperationsCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.partition\",tag0=~\".*partitionId=.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Partition Threads", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Partition Threads: Error Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of failed tasks on this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_errorCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Normal Pending Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of normal pending operations (tasks)",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_normalPendingCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Error Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of failed tasks on this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_errorCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Normal Pending Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of normal pending operations (tasks)",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_normalPendingCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Priority Pending Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of priority pending operations (tasks)",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_priorityPendingCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Total Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of tasks (Operation + PartitionSpecificRunnable + Runnable + TaskBatch) completed on this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedTotalCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Priority Pending Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of priority pending operations (tasks)",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_priorityPendingCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Total Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of tasks (Operation + PartitionSpecificRunnable + Runnable + TaskBatch) completed on this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedTotalCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Operation Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of completed operations by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedOperationCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Batch Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of completed TaskBatch (a batch of tasks) by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedOperationBatchCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Operation Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of completed operations by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedOperationCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Batch Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster: Number of completed TaskBatch (a batch of tasks) by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedOperationBatchCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Runnable Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total number of runnables executed by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedRunnableCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Partition Specific Runnable Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of PartitionSpecificRunnable tasks executed by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedPartitionSpecificRunnableCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Runnable Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of runnables executed by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedRunnableCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Partition Specific Runnable Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of PartitionSpecificRunnable tasks executed by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedPartitionSpecificRunnableCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Packet Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of packets that executed by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedPacketCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Threads: Completed Packet Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of packets that executed by this operation thread",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_completedPacketCount{$ClusterFilterLabel=\"$Cluster2\", prefix=\"operation.thread\",tag0=~\".*partition-operation.thread.*\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}