{
 "title": "Dual Queues",
 "tags": [
  "data structure",
  "queue",
  "dual hazelcast"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Queues ($Cluster)",
   "type": "table",
   "description": "$Cluster: Queue status",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Queue status",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Items ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Number of owned and backup items in this member",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Items ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Number of owned and backup items in this member",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Age ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Min, max, and average age of the items ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Age ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Min, max, and average age of the items ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Operations ($Cluster)",
   "type": "barchart",
   "description": "$Cluster: Number of operations",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_total{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Operations ($Cluster2)",
   "type": "barchart",
   "description": "$Cluster2: Number of operations",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_total{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues: Events (Aggregate) ($Cluster)",
   "type": "timeseries",
   "description": "$Cluster: Number of event operations (duplicate of eventOperationCount)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\"})",
     "legendFormat": "Total Events"
    }
   ]
  },
  {
   "title": "Queues: Events (Aggregate) ($Cluster2)",
   "type": "timeseries",
   "description": "$Cluster2: Number of event operations (duplicate of eventOperationCount)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster2\",prefix=\"queue\"})",
     "legendFormat": "Total Events"
    }
   ]
  }
 ]
}