{
 "title": "Dual Topics",
 "tags": [
  "data structure",
  "topic",
  "dual hazelcast"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterList" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "label": "Cluster 2", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Topics: Published Messages ($Cluster)",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPublishes{$ClusterFilterLabel=\"$Cluster\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics: Published Messages ($Cluster2)",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPublishes{$ClusterFilterLabel=\"$Cluster2\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics: Received Messages ($Cluster)",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalReceivedMessages{$ClusterFilterLabel=\"$Cluster\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics: Received Messages ($Cluster2)",
   "type": "table",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalReceivedMessages{$ClusterFilterLabel=\"$Cluster2\",prefix=\"topic\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}