{
 "title": "Dual Replicated Maps Rows",
 "tags": [
  "dual hazelcast",
  "data structure",
  "replicated map"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Replicated Maps: Entries ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of entries owned on this member",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Entries ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of entries owned on this member",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Entry Memory ($Cluster)",
   "type": "table",
   "description": "$Cluster: Memory cost of owned entries on this member",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Entry Memory ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Memory cost of owned entries on this member",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Hits ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of hits (reads) of the locally owned entries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Hits ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of hits (reads) of the locally owned entries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Events ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of entries owned on this member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Events ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of entries owned on this member",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Other Operations",
   "type": "table",
   "description": "$Cluster: Total number of other operations performed on this member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Other Operations ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of other operations performed on this member",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Total Operations",
   "type": "table",
   "description": "Total number of operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_total{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Total Operations ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total number of operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_total{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Put Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of put operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Put Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of put operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Get Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of get operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Get Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of get operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Remove Count ($Cluster)",
   "type": "table",
   "description": "$Cluster: Number of remove operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Remove Count ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Number of remove operations on this member",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Put Latency ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total latency of put operations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxPutLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Put Latency ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total latency of put operations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxPutLatency{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Get Latency ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total latency of get operations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxGetLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Get Latency ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total latency of get operations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxGetLatency{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Remove Latency ($Cluster)",
   "type": "table",
   "description": "$Cluster: Total latency of remove operations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxRemoveLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Remove Latency ($Cluster2)",
   "type": "table",
   "description": "$Cluster2: Total latency of remove operations",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxRemoveLatency{$ClusterFilterLabel=\"$Cluster2\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}