{
 "title": "CQ",
 "tags": [
  "gemfire",
  "cq",
  "query"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Active CQ Count (Aggregate)",
   "type": "stat",
   "description": "$Cluster: Total number of active CQs across all servers.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_numCqsActive{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Average CQ Execution Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took to complete a CQ execution.",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_cqQueryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}/gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "{{instance}} Avg CQ Execution Time"
    }
   ]
  },
  {
   "title": "Clients with CQs (Aggregate)",
   "type": "stat",
   "description": "$Cluster: Total number of clients with CQs across all servers.",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_numClientsWithCqs{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CQ Service",
   "type": "table",
   "description": "$Cluster: CQ service stats.",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cqQueryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}/gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqQueryExecutionInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqQueryExecutionTime{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numClientsWithCqs{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqEventsFiltered{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsActive{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsClosed{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsCreated{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsOnClient{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numCqsStopped{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_numUniqueCqQuery{$ClusterFilterLabel=\"$Cluster\", category=\"CqServiceStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}