{
 "title": "Disk Regions Columns Charts",
 "tags": [
  "gemfire",
  "storage",
  "disk region"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Disk Regions: Entries Only On Disk",
   "type": "barchart",
   "description": "$Cluster: Current number of entries whose value is on the disk and is not in memory. This is true of overflowed entries. It is also true of recovered entries that have not yet been faulted in.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entriesOnlyOnDisk{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Bytes Only On Disk",
   "type": "barchart",
   "description": "$Cluster: The current number of bytes on disk and not in memory. It includes overflowed entries and recovered entries that have not yet been faulted in.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_bytesOnlyOnDisk{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Entries In VM",
   "type": "barchart",
   "description": "$Cluster: Current number of entries whose value resides in the member. The value may also have been written to the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entriesInVM{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Reads",
   "type": "barchart",
   "description": "$Cluster: Total number of region entries that have been read from the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_reads{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Read Time",
   "type": "barchart",
   "description": "$Cluster: Total amount of time spent reading from the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_readTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Read Bytes",
   "type": "barchart",
   "description": "$Cluster: Total number of bytes that have been read from the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_readBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Writes",
   "type": "barchart",
   "description": "$Cluster: Total number of region entries that have been written to disk. A write is done every time an entry is created on disk or every time its value is modified on the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_writes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Write Time",
   "type": "barchart",
   "description": "$Cluster: Total amount of time spent writing to the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_writeTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Write Bytes",
   "type": "barchart",
   "description": "$Cluster: Total number of bytes that have been written to the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_writtenBytes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Writes In Progress",
   "type": "barchart",
   "description": "$Cluster: Total number of entries that are currently in progress of written to the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_writesInProgress{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Removes",
   "type": "barchart",
   "description": "$Cluster: Total number of region entries that have been removed from the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_removes{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Remove Time",
   "type": "barchart",
   "description": "$Cluster: Total amount of time spent removing from the disk.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_removeTime{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Local Initializations",
   "type": "barchart",
   "description": "$Cluster: Number of local initializations.",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_localInitializations{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Regions: Remote Initializations",
   "type": "barchart",
   "description": "$Cluster: Number of remote initializations.",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_remoteInitializations{$ClusterFilterLabel=\"$Cluster\",category=\"DiskRegionStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}