{
 "title": "Members",
 "tags": [
  "gemfire",
  "cluster",
  "member"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Locator Count",
   "type": "stat",
   "description": "$Cluster: Number of locators",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count((gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster\",category=\"LocatorStats\",member_type=\"locator\"} and on() (gemfire_locators{$ClusterFilterLabel=\"locator-$Cluster\",category=\"LocatorStats\",member_type=\"locator\"} >= 0)) or on() gemfire_locators{$ClusterFilterLabel=\"$Cluster\",category=\"LocatorStats\",member_type=\"locator\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Count",
   "type": "stat",
   "description": "$Cluster: Number of nodes (peers)",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(gemfire_nodes{$ClusterFilterLabel=\"$Cluster\",category=\"DistributionStats\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entries (Primary & Backup)",
   "type": "stat",
   "description": "$Cluster: Total number of entries in all regions including primary and backup",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Reads per second",
   "type": "stat",
   "description": "$Cluster: Aggregated get() rate across the cluster.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"} / (gemfire_getTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Writes per second",
   "type": "stat",
   "description": "$Cluster: Aggregated put() rate across the cluster.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": " ceil(sum(gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}) / sum(gemfire_putTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "$Cluster: Member resource statuses",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=\"$Cluster\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=\"$Cluster\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ParNew\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"ConcurrentMarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS Scavenge\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"PS MarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=\"$Cluster\", exported_instance=\"G1 Old Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Partitioned Regions Overall Operations Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest put(), get(), destroy(), putAll(), and removeAll() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_putsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_destroysCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_putAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}+gemfire_removeAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: put() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest put() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Disk Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest number of bytes written to the disk. ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max (gemfire_writtenBytes{job=\"$Cluster\",category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: get() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest get() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: putAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest putAll() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(gemfire_putAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: removeAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "$Cluster: Heatmap of the member with the highest remove() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max(gemfire_removeAllsCompleted{job=\"$Cluster\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}