{
 "title": "Partitioned Region",
 "tags": [
  "gemfire",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "MapType", "label": "Map Type", "query": "region" },
   {
    "name": "Map",
    "label": "Region",
    "query": {
     "query": "label_values(gemfire_dataStoreEntryCount{category=\"PartitionedRegionStats\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "$Map: Entries, Memory ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Number of region entries across all membersmembers",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Entries"
    },
    {
     "expr": "max(gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "$Map: put() Average Latency ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Average put() latency across all members. The latency is calculated using the total time spent adding or replacing an entry in this cache as a result of a local operation. This includes synchronizing on the map, invoking cache callbacks, sending messages to other caches, and waiting for responses (if required).",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(gemfire_putTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})/sum(gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "$Map: putAll() Average Latency ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Average putAll() latency across all members. The latency is calculated using the total time spent adding or replacing an entry in this cache as a result of a local operation. This includes synchronizing on the map, invoking cache callbacks, sending messages to other caches, and waiting for responses (if required).",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(gemfire_putAllTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})/sum(gemfire_putAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "$Map: Query Average Latency ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Average query latency across all members. The latency is calculated using the total time spent executing some query and thtetotal number of times some query has been executed.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(queryExecutionTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})/sum(queryExecutions{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "$Map: get() Average Latency ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Average put() latency across all members. The latency is calculated using the total time spent doing get operations from this cache (including netsearch and netload) and the total number of times a successful get has been done on this cache.",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(gemfire_getTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})/sum(gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "$Map: Update Average Latency ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Average update latency across all members. The latency is calculated using the total time spent performing an update and the total number of updates originating remotely that have been applied to this cache.",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(gemfire_updateTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})/sum(gemfire_udpatesCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "$Map: destroy() Average Latency ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Average destroy() latency across all members. The latency is calculated using the total number of times a cache object entry has been destroyed in this cache and the total time spent performing destroy operations.",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(gemfire_destroyTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})/sum(gemfire_destroysCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "$Map: removeAll() Average Latency ($MapType)",
   "type": "timeseries",
   "description": "$Cluster: Average removeAll() latency across all members. The latency is calculated using the total number of times a cache object entry has been destroyed in this cache and the total time spent performing destroy operations.",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "sum(gemfire_removeAllTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})/sum(gemfire_removeAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Latency"
    }
   ]
  },
  {
   "title": "$Map: Region Stats ($MapType)",
   "type": "bargauge",
   "description": "$Cluster: Sum of the number of queries executed on the region.",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Puts"
    },
    {
     "expr": "sum(gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Gets"
    },
    {
     "expr": "sum(gemfire_destroysCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "Destroys"
    },
    {
     "expr": "sum(gemfire_putAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "PutAlls"
    },
    {
     "expr": "sum(gemfire_removeAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"})",
     "legendFormat": "RemoveAlls"
    }
   ]
  },
  {
   "title": "$Map: Region Statistics ($MapType)",
   "type": "table",
   "description": "$Cluster: Individual statistics of the map",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_dataStoreEntryCount{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroysCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_removeAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_dataStoreBytesInUse{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Map: Region Throughput and Average Latency ($MapType)",
   "type": "table",
   "description": "$Cluster: Individual throughput statistics of the region",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_putTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}*1000000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_getTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}*1000000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroysCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_destroyTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}*1000000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_putAllTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}*1000000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_removeAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_removeAllTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}*1000000000",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_getsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_putsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_destroysCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putAllTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_putAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_removeAllTime{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}/gemfire_removeAllsCompleted{$ClusterFilterLabel=\"$Cluster\",category=\"PartitionedRegionStats\",exported_instance=\"$Map\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}