{
 "title": "WAN",
 "tags": [
  "gemfire",
  "cluster",
  "wan"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "GatewaySender",
    "label": "Gateway Sender",
    "query": {
     "query": "label_values(gemfire_eventsQueued{category=\"GatewaySenderStatistics\", $ClusterFilterLabel=\"$Cluster\"},exported_instance)"
    }
   },
   {
    "name": "GatewayReceiver",
    "label": "Gateway Receiver",
    "query": {
     "query": "label_values(gemfire_eventsReceived{category=\"GatewayReceiverStatistics\", $ClusterFilterLabel=\"$Cluster\"},exported_instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Gateway Senders", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Gatway Senders: Queues",
   "type": "timeseries",
   "description": "$Cluster: Gateway sender queue event stats",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "gemfire_eventQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Queue Size"
    },
    {
     "expr": "gemfire_eventsExceedingAlertThreshold{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Exceeding Alert Threshold"
    },
    {
     "expr": "gemfire_secondaryEventQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Secondary Queue Size"
    }
   ]
  },
  {
   "title": "Gatway Senders: Average Event Queue Time",
   "type": "timeseries",
   "description": "$Cluster: Average time an event reside in the queue.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_eventQueueTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}/gemfire_eventsDistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "$Cluster: Gatway Senders: Average Batch Distribution Time",
   "type": "timeseries",
   "description": "$Cluster: Average time spent distribution a batch of events.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_batchDistributionTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}/gemfire_batchesDistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Gatway Senders: Queue Events",
   "type": "timeseries",
   "description": "$Cluster: Total number of gateway sender queue events",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Queued"
    },
    {
     "expr": "gemfire_eventsFiltered{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Filtered"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Received"
    },
    {
     "expr": "gemfire_notQueuedEvent{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Not Queued"
    }
   ]
  },
  {
   "title": "Gatway Senders: Unprocessed Events",
   "type": "timeseries",
   "description": "$Cluster: Total number of gateway sender unprocessed events",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_unprocessedEventsAddedBySecondary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Added By Secondary"
    },
    {
     "expr": "gemfire_unprocessedEventsRemovedByPrimary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Removed By Primary"
    },
    {
     "expr": "gemfire_unprocessedEventsRemovedByTimeout{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Removed By Timeout"
    },
    {
     "expr": "gemfire_unprocessedTokensAddedByPrimary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Tokens Added By Primary"
    },
    {
     "expr": "gemfire_unprocessedTokensRemovedBySecondary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Tokens Removed By Secondary"
    },
    {
     "expr": "gemfire_unprocessedTokensRemovedByTimeout{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "{{instance}} Tokens Removed By Timeout"
    }
   ]
  },
  {
   "title": "Gateway Senders: Events",
   "type": "table",
   "description": "$Cluster: Gateway sender events",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_eventQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventQueueTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDroppedDueToPrimarySenderNotRunning{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsExceedingAlertThreshold{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsFiltered{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalanceTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_notQueuedEvent{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_secondaryEventQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Senders: Complete Stats",
   "type": "table",
   "description": "$Cluster: All gateway sender stats",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_batchDistributionTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesDistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesRedistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesResized{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchesWithIncompleteTransactions{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_conflationIndexesSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsCreated{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsDistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsQueued{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaExceptionsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_enqueueFullValueFailedEntryDestroyed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventQueueTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsConflatedFromBatches{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsDroppedDueToPrimarySenderNotRunning{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsExceedingAlertThreshold{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsFiltered{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsNotQueuedConflated{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsProcessedByPQRM{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsQueued{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValueEventsCreated{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValueEventsCreatedWithDeltaAvailable{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValueEventsDistributed{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalanceTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesCompleted{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadBalancesInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_notQueuedEvent{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_secondaryEventQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_synchronizationEventsEnqueued{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_synchronizationEventsProvided{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tempQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventMapSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventsAddedBySecondary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventsRemovedByPrimary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedEventsRemovedByTimeout{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokenMapSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokensAddedByPrimary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokensRemovedBySecondary{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unprocessedTokensRemovedByTimeout{$ClusterFilterLabel=\"$Cluster\", category=\"GatewaySenderStatistics\", exported_instance=\"$GatewaySender\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gateway Receivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Gatway Receivers: Events",
   "type": "timeseries",
   "description": "$Cluster: Gateway receiver event stats",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Events Received"
    },
    {
     "expr": "gemfire_createRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Create Requests"
    },
    {
     "expr": "gemfire_updateRequest{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Update Requests"
    },
    {
     "expr": "gemfire_destroyRequest{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Destroy Requests"
    },
    {
     "expr": "gemfire_deltaEventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Delta Events Received"
    }
   ]
  },
  {
   "title": "Gatway Receivers: Message Size",
   "type": "timeseries",
   "description": "$Cluster: Gateway receiver region operation events",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "gemfire_messageBytesBeingReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Message Bytes Being Received"
    },
    {
     "expr": "gemfire_receivedBytes{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Received Bytes"
    },
    {
     "expr": "gemfire_sentBytes{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Sent Bytes"
    }
   ]
  },
  {
   "title": "Gatway Receivers: Average Batch Process Time",
   "type": "timeseries",
   "description": "$Cluster: Gateway batch process latency",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_processBatchTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}/gemfire_processBatchResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Average Batch Process Time"
    }
   ]
  },
  {
   "title": "Gatway Receivers: Load Per Connection",
   "type": "timeseries",
   "description": "$Cluster: Gateway batch process latency",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Load Per Connection"
    }
   ]
  },
  {
   "title": "Gatway Receivers: Clients",
   "type": "timeseries",
   "description": "$Cluster: Current client connections",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 85 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "{{instance}} Average Batch Process Time"
    }
   ]
  },
  {
   "title": "$Cluster: Gateway Receivers: Events",
   "type": "table",
   "description": "$Cluster: Gateway receiver events",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 96 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_createRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRequest{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateRequest{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_exceptions{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_failedConnectionAttempts{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway Receivers: Complete Stats",
   "type": "table",
   "description": "$Cluster: All gateway receiver stats",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_abandonedReadRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_abandonedWriteRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_acceptThreadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_acceptsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_batchSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clearRegionRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clearRegionResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientReadyResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_clientRequestsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_closeConnectionRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionLoad{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreadStarts{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionThreads{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_connectionsTimedOut{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_containsKeyRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_containsKeyResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_createRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClientConnections{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentClients{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_currentQueueConnections{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_deltaEventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRegionRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRegionResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRequest{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_destroyResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_duplicateBatchesReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_earlyAcks{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_eventsRetried{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_exceptions{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_failedConnectionAttempts{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_fullValuesRequested{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getAllResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_getResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_invalidateRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_invalidateResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerConnection{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_loadPerQueue{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_messageBytesBeingReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_messagesBeingReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_outOfOrderGatewayBatchIds{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_outoforderBatchesReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processBatchRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processBatchResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processBatchTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClearRegionTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processClientReadyTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processCloseConnectionTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processContainsKeyTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processDestroyRegionTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processDestroyTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processGetAllTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processGetTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processInvalidateTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processPutAllTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processPutTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processQueryTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processRemoveAllTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processSizeTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_processUpdateClientNotificationTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putAllRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putAllResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_putResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queryRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queryResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueInitializationsInProgress{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_queueLoad{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClearRegionRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readClientReadyRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readCloseConnectionRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readContainsKeyRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readDestroyRegionRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readDestroyRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readGetAllRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readGetRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readInvalidateRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readProcessBatchRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readPutAllRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readPutRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readQueryRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readRemoveAllRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readSizeRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_readUpdateClientNotificationRequestTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_receivedBytes{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_removeAllRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_removeAllResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sentBytes{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sizeRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_sizeResponses{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_threadQueueSize{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_unknownOperationsReceived{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateClientNotificationRequests{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_updateRequest{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClearRegionResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeClientReadyResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeContainsKeyResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeDestroyRegionResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeDestroyResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeGetAllResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeGetResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeInvalidateResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeProcessBatchResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writePutAllResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writePutResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeQueryResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeRemoveAllResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_writeSizeResponseTime{$ClusterFilterLabel=\"$Cluster\", category=\"GatewayReceiverStatistics\", exported_instance=\"$GatewayReceiver\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}