#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

# Results directory
RESULTS_DIR="$APP_DIR/results"

# Perf properties file
PERF_PROPERTIES_FILE=$APP_DIR/etc/group.properties

# LOG_FILE (See etc/log4j.properties)
if [[ ${OS_NAME} == CYGWIN* ]]; then
   RESULTS_DIR="$(cygpath -wp "$RESULTS_DIR")"
   PERF_PROPERTIES_FILE="$(cygpath -wp "$PERF_PROPERTIES_FILE")"
   LOG_FILE=$LOG_DIR\\$EXECUTABLE.log
   CLASSPATH="$(cygpath -wp "$CLASSPATH")"
else
   LOG_FILE=$LOG_DIR/$EXECUTABLE.log
fi
export LOG_FILE

# Paho logging
PAHO_LOG_CONFIG_FILE="$APP_ETC_DIR/paho-logging-$EXECUTABLE.properties"
JAVA_OPTS="$JAVA_OPTS -Djava.util.logging.config.file=$PAHO_LOG_CONFIG_FILE"

# log4j log file path
JAVA_OPTS="$JAVA_OPTS -Dorg.mqtt.addon.logfile=$LOG_FILE"

# Application executable name. Useful for displaying usage.
JAVA_OPTS="$JAVA_OPTS -Dexecutable.name=$EXECUTABLE"

# Application specifics
#
JAVA_OPTS="$JAVA_OPTS -Dperf.properties.file=$PERF_PROPERTIES_FILE"
JAVA_OPTS="$JAVA_OPTS -Dresults.dir=$RESULTS_DIR"
JAVA_OPTS="$JAVA_OPTS -Dcluster.name=perf_test-$EXECUTABLE"

"$JAVA" $JAVA_OPTS org.mqtt.addon.test.perf.GroupTest $*
