{
 "title": "GemFire NonCategory Tables",
 "tags": [
  "all",
  "gemfire",
  "noncategory",
  "generated"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "cache",
   "type": "table",
   "description": "$Cluster: cache",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_cache_entries{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cache_gets_seconds_count{$ClusterFilterLabel=\"$Cluster\",result=\"hit\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cache_gets_seconds_count{$ClusterFilterLabel=\"$Cluster\",result=\"miss\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cache_gets_seconds_max{$ClusterFilterLabel=\"$Cluster\",result=\"hit\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cache_gets_seconds_max{$ClusterFilterLabel=\"$Cluster\",result=\"miss\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cache_gets_seconds_sum{$ClusterFilterLabel=\"$Cluster\",result=\"hit\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_cache_gets_seconds_sum{$ClusterFilterLabel=\"$Cluster\",result=\"miss\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "function",
   "type": "table",
   "description": "$Cluster: function",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_function_executions_seconds_count{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_function_executions_seconds_max{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_function_executions_seconds_sum{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "gateway",
   "type": "table",
   "description": "$Cluster: gateway",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_gateway_receiver_events_operations_total{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "jvm",
   "type": "table",
   "description": "$Cluster: jvm",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_jvm_buffer_count_buffers{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_buffer_memory_used_bytes{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_buffer_total_capacity_bytes{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_concurrent_phase_time_seconds_count{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_concurrent_phase_time_seconds_max{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_concurrent_phase_time_seconds_sum{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_live_data_size_bytes{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_max_data_size_bytes{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_memory_allocated_bytes_total{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_memory_promoted_bytes_total{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_pause_seconds_count{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_pause_seconds_max{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_gc_pause_seconds_sum{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_memory_committed_bytes{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_memory_max_bytes{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_memory_used_bytes{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_threads_daemon_threads{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_threads_live_threads{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_threads_peak_threads{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_threads_started_threads_total{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_jvm_threads_states_threads{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "process",
   "type": "table",
   "description": "$Cluster: process",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_process_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_process_files_max_files{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_process_files_open_files{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_process_start_time_seconds{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_process_uptime_seconds{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "system",
   "type": "table",
   "description": "$Cluster: system",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_count{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_system_load_average_1m{$ClusterFilterLabel=\"$Cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}