{
 "title": "00Main All",
 "tags": [
  "all hazelcast",
  "main"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "All Main Dashboard",
   "type": "text",
   "description": "The main dashboard of PadoGrid Hazelcast Dashboards (PHD) that resembles the main dashboard of Hazelcast Management Center (HMC). PHD includes additional metrics that are not available in HMC and vice versa. PHD exposes a finer degree of individual metric details along with federated cluster views making it more suitable for monitoring production systems.",
   "gridPos": { "h": 43, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "## Main\n\n- [Main Dashboard](/d/a310264b-af07-4113-a2ca-e40d86499d3a/00main?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n- [Dual Main Dashboard](/d/c285e20e-3b2a-4108-bc28-69238459027a/00dual-main?var-DataSource=$DataSource&var-Cluster=$Cluster&var-Cluster2=$Cluster2&${__url_time_range})\n- [All Main Dashboard](/d/d3a660bb-5588-491e-849b-6e40b6c0de0e/00main-all?${__url_time_range})\n\n## Cluster\n\n- [All Clients](/d/ac304374-64b6-41a0-ad04-eae04c12c105/all-client?var-DataSource=$DataSource&${__url_time_range})\n- [All Members](/d/b818f2fb-141e-4ac3-9e30-307a26b1312a/all-members?var-DataSource=$DataSource&${__url_time_range})\n- [All WAN Replication](/d/b912ed29-e3e1-4a1b-9761-cc0a29dfa7fb/all-wan-replication?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Storage\n\n- [All Maps](/d/be805b83-64cf-401c-9560-aa2cf3d9147f/all-maps-rows?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Total Charts](/d/afbefad6-61d2-4a54-92b0-f4b0abd599c9/all-maps-columns-total-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Total Tables](/d/aab8efb6-c41b-466c-a3e9-c75fe098df31/all-maps-columns-total?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Charts](/d/f568fbb8-94e3-4dee-8690-0791223e1ac5/all-maps-rows-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Tables](/d/be805b83-64cf-401c-9560-aa2cf3d9147f/all-maps-rows?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Total Charts](/d/ca36a316-7dc6-4ef8-821f-738e153bd094/all-maps-rows-total-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Total Tables](/d/d118dda2-e987-43ac-ae32-74dade452528/all-maps-rows-total?var-DataSource=$DataSource&${__url_time_range})\n   - [Query Charts](/d/da723716-997f-483b-8759-8b4cdaf8ecad/all-map-query-charts?var-DataSource=$DataSource&{__url_time_range})\n   - [Query Tables](/d/b3767432-9d15-4255-a06d-34e1415dfc57/all-map-query-tables?var-DataSource=$DataSource&${__url_time_range})\n- [All Replicated Maps](/d/e4e81d2d-2f25-474c-80f4-3dfa889fe228/all-replicated-maps-rows?var-DataSource=$DataSource&${__url_time_range})\n    - [Column Charts](/d/e3e2da36-9cae-4afb-aaee-b19730886b2e/all-replicated-maps-columns-charts?var-DataSource=$DataSource&${__url_time_range})\n    - [Column Tables](/d/cd23a014-0cb9-4936-bb45-d75c5558607e/all-replicated-maps-columns?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Charts](/d/b788a0f0-9ecb-4605-82fc-c7a0447b6bb8/all-replicated-maps-rows-charts?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Tables](/d/e4e81d2d-2f25-474c-80f4-3dfa889fe228/all-replicated-maps-rows?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Max Charts](/d/b656390c-d073-4b56-88c8-74c8d05e4d5a/all-replicated-maps-rows-max-charts?var-DataSource=$DataSource&${__url_time_range})\n    - [Row Max Tables](/d/ab0bfe87-f866-4a9e-9c04-7576d23e9b2a/all-replicated-maps-rows-max?var-DataSource=$DataSource&${__url_time_range})\n- [All Multi Maps](/d/e4301ff2-b18f-44d0-97fe-4d17666e8fe8/all-multi-maps-rows?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Charts](/d/c6a2d158-bc99-49ac-b077-b054332db49b/all-multi-maps-columns-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Column Tables](/d/fb06c996-0b19-4549-9911-a32d985f02fc/all-multi-maps-columns?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Charts](/d/e18e183f-6538-4a1a-ba70-4708b5f208bd/all-multi-maps-rows-charts?var-DataSource=$DataSource&${__url_time_range})\n   - [Row Tables](/d/e4301ff2-b18f-44d0-97fe-4d17666e8fe8/all-multi-maps-rows?var-DataSource=$DataSource&${__url_time_range})\n- [All Lists](/d/d2442706-8b0a-4b3b-b2f3-f0b4261c2c76/all-lists?var-DataSource=$DataSource&${__url_time_range})\n- [All Sets](/d/e579f09b-98c2-4e3f-bd7b-845914699841/all-sets?var-DataSource=$DataSource&${__url_time_range})\n- [All PN Counters](/d/c21858fe-b1a3-4723-964f-8a9c985e0540/all-pn-counters?var-DataSource=$DataSource&${__url_time_range})\n- [All Flake ID Generators](/d/d5d1a0d3-9a5d-425d-b244-8ea36042a847/all-flake-id-generators?var-DataSource=$DataSource&${__url_time_range})\n\n## Partition\n\n- [All Partitions](/d/ed5d0096-86b2-458b-a01c-4e4ee67c10b7/all-partitions?var-DataSource=$DataSource&${__url_time_range})\n\n## Stream\n\n- [All Jet](/d/b74ad0ce-d2a5-41fe-9e33-d6cc8b04b802/all-jet?var-DataSource=$DataSource&${__url_time_range})\n\n## Compute\n\n- [All Executors](/d/f4d1df17-f9c2-4ee2-81fa-3cf61c84d7c4/all-executors?var-DataSource=$DataSource&var-Cluster=$Cluster&${__url_time_range})\n\n## Messaging\n\n- [All Queues](/d/b18f51bd-a0c7-40ec-856e-28597b65b96a/all-queues?var-DataSource=$DataSource&${__url_time_range})\n- [All Reliable Topics](/d/e14d2fdf-7bdd-4a33-8104-22e2bd3198fc/all-reliable-topics?var-DataSource=$DataSource&&${__url_time_range})\n- [All Topics](/d/e419a25d-1979-4d88-9254-4ab8a3246833/all-topics?var-DataSource=$DataSource&${__url_time_range})\n\n## CP Subsystem\n\n- [All CP Subsystem](/d/d0247897-d2d2-4799-8040-f68a43858ca6/all-cp-subsystem?var-DataSource=$DataSource&${__url_time_range})\n\n"
   }
  },
  {
   "title": "Cluster Up Time",
   "type": "stat",
   "description": "Cluster up time determined by the oldest member",
   "gridPos": { "h": 7, "w": 4, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_clusterUpTime{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Map Memory",
   "type": "bargauge",
   "description": "Sum of memory used by maps of all members per cluster",
   "gridPos": { "h": 7, "w": 4, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=~\"($ClusterList)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Free Memory",
   "type": "bargauge",
   "description": "Sum of free memory of all members per cluster",
   "gridPos": { "h": 7, "w": 4, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_freeHeap{$ClusterFilterLabel=~\"($ClusterList)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used Memory",
   "type": "bargauge",
   "description": "Sum of used memory of all members per cluster",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=~\"($ClusterList)\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partition Distribution",
   "type": "stat",
   "description": "Partitions owned by each member",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_localPartitionCount{$ClusterFilterLabel=~\"$ClusterList\"}/com_hazelcast_Metrics_partitionCount{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Max",
   "type": "timeseries",
   "description": "Used vs. Max heap of each member. For sustained performance, keep used heap below 80% of max heap",
   "gridPos": { "h": 12, "w": 11, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "Used {{$ClusterFilterLabel}} {{instance}}"
    },
    {
     "expr": "com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "Max {{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "Max System CPU Load",
   "type": "timeseries",
   "description": "CPU load of each member across all clusters",
   "gridPos": { "h": 12, "w": 10, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "CPU {{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "System resource status of each member across all clusters",
   "gridPos": { "h": 24, "w": 21, "x": 3, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory/com_hazelcast_Metrics_totalMemory{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=~\"$ClusterList\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=~\"$ClusterList\",gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{$ClusterFilterLabel=~\"$ClusterList\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{$ClusterFilterLabel=~\"$ClusterList\",gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}