{
 "title": "All WAN Replication",
 "tags": [
  "all hazelcast",
  "clients"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } },
   { "name": "ClusterList", "label": "Clusters", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  {
   "title": "WAN Replication",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "**WAN Standard:** *Standard WAN metrics included in Hazelcast.* **WAN Discovery Plugin:** *WAN plugin by Sorint.lab (reduces WAN endpoint discovery latency by 1000x)*"
   }
  },
  { "title": "WAN Standard", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Members",
   "type": "table",
   "description": "WAN replication outbound queue status",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_queueFillPercent{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPublishLatency{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPublishedEventCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayLastStart{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayLastEnd{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayTotalCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayTotalMillis{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Update Events",
   "type": "table",
   "description": "Number of entry update events",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_updateCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Remove Events",
   "type": "table",
   "description": "Number of entry remove events",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Sync Events",
   "type": "table",
   "description": "Number of entry sync events",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_syncCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Dropped Events",
   "type": "table",
   "description": "Number of dropped entry events",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_droppedCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WAN Discovery Plugin",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 },
   "collapsed": true,
   "panels": [
    {
     "title": "WAN Discovery: Live Endpoints",
     "type": "table",
     "description": "Number of live endpoints performing WAN replication",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{$ClusterFilterLabel=~\"$ClusterList\",type=\"DiscoveryService\"}",
       "legendFormat": "Live"
      }
     ]
    },
    {
     "title": "WAN Discovery: Dead Endpoints",
     "type": "table",
     "description": "Number of dead target endpoints that are not participating in WAN replication. As these endpoints become reachable, they are automatically moved to the live endpoint list.",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{$ClusterFilterLabel=~\"$ClusterList\",type=\"DiscoveryService\"}",
       "legendFormat": "Live"
      }
     ]
    },
    {
     "title": "WAN Discovery: All Endpoints",
     "type": "table",
     "description": "Total number of target endpoints configured for WAN replication",
     "gridPos": { "h": 5, "w": 24, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{$ClusterFilterLabel=~\"$ClusterList\",type=\"DiscoveryService\"}",
       "legendFormat": "Live"
      }
     ]
    }
   ]
  }
 ]
}