{
 "title": "All Maps Rows Total",
 "tags": [
  "data structure",
  "map",
  "imap",
  "partitioned map",
  "all hazelcast"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "ClusterList", "label": "Clusters", "query": { "query": "label_values(job)" } },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } },
   { "name": "Filters" },
   { "name": "Cluster3", "label": "Cluster 3", "query": "wan1" },
   { "name": "Cluster4", "label": "Cluster 4", "query": "wan2" }
  ]
 },
 "panels": [
  {
   "title": "Maps: Entries",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backups",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_backupEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: HIts",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Events",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Backup Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dirty Entries",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_dirtyEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Locked Entries",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_lockedEntryCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Expirations",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_expirationCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Evictions",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_evictionCount{$ClusterFilterLabel=~\"($ClusterList)\",prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}