{
 "title": "All Replicated Maps Columns",
 "tags": [
  "data structure",
  "replicated map",
  "all hazelcast"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "ClusterList", "label": "Clusters", "query": { "query": "label_values(job)" } },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "All Replicated Maps Columns",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "*This dashboard displays federated views of all members of clusters.*"
   }
  },
  {
   "title": "Replicated Maps: Entries",
   "type": "table",
   "description": "Number of entries owned on this member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Entry Memory",
   "type": "table",
   "description": "Memory cost of owned entries on this member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Hits",
   "type": "table",
   "description": "Number of hits (reads) of the locally owned entries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Events",
   "type": "table",
   "description": "Number of events received on this member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Other Operations",
   "type": "table",
   "description": "Total number of other operations performed on this member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Total Operations",
   "type": "table",
   "description": "Total number of operations on this member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_total{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Put Count",
   "type": "table",
   "description": "Number of put operations on this member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Get Count",
   "type": "table",
   "description": "Number of get operations on this member",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Remove Count",
   "type": "table",
   "description": "Number of remove operations on this member",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Put Latency",
   "type": "table",
   "description": "Total latency of put operations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxPutLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Get Latency",
   "type": "table",
   "description": "Total latency of get operations",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxGetLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps: Max Remove Latency",
   "type": "table",
   "description": "Total latency of remove operations",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxRemoveLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}