{
 "title": "All Executors",
 "tags": [
  "all hazelcast",
  "executor"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   { "name": "ClusterList", "label": "Clusters", "query": { "query": "label_values(job)" } },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "label": "Cluster", "query": { "query": "label_values(job)" } },
   { "name": "Cluster2", "label": "Cluster2", "query": { "query": "label_values(job)" } },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Executors",
   "type": "table",
   "description": "Overall executor status",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_creationTime{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalExecutionTime{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalStartLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_started{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_remainingQueueCapacity{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_poolSize{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_queueSize{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_pending{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maximumPoolSize{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completedTasks{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completed{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_cancelled{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors: Execution Count",
   "type": "barchart",
   "description": "Number of started, completed, and cancelled operations on the executor service across all clusters",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_started{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completed{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_cancelled{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors: Max Queue Size",
   "type": "timeseries",
   "description": "$Cluster: Number of pending tasks of the member that has the maximum value in all clusters",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_queueSize{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor.internal\"})",
     "legendFormat": "Max Queue Size (Single Member)"
    }
   ]
  },
  {
   "title": "Executors: Max Total Execution Count",
   "type": "timeseries",
   "description": "Total number of started, completed, and cancelled operations of the member that has the maximum value",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_started{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"})",
     "legendFormat": "{{instance}} Total Started"
    },
    {
     "expr": "max(com_hazelcast_Metrics_completed{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"})",
     "legendFormat": "{{instance}} Total Completed"
    },
    {
     "expr": "max(com_hazelcast_Metrics_cancelled{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"})",
     "legendFormat": "{{instance}} Total Cancelled"
    }
   ]
  },
  {
   "title": "Executors: Average Execution Latency",
   "type": "timeseries",
   "description": "$Cluster: Total execution time of the finished operations divided by sum of completed and cancelled operations",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalExecutionTime{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}/(com_hazelcast_Metrics_completed{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"}+com_hazelcast_Metrics_cancelled{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"executor\"})",
     "legendFormat": "{{job}} {{instance}}"
    }
   ]
  }
 ]
}