{
 "title": "All Map Query Charts",
 "tags": [
  "data structure",
  "map",
  "query",
  "all hazelcast",
  "index"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterList", "label": "Clusters", "query": "hazelcast" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "query": "hazelcast" }
  ]
 },
 "panels": [
  {
   "title": "Map Query Count",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map\"}",
     "legendFormat": "{{job}} {{instance}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Map Query Count (aggregate)",
   "type": "timeseries",
   "description": "mw/customers and nw/orders queries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "{{job}} {{instance}} {{tag0}}"
    }
   ]
  },
  {
   "title": "Indexes: Insert Count",
   "type": "barchart",
   "description": "Number of insert operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_insertCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Insert Latency",
   "type": "barchart",
   "description": "Total latency of insert operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalInsertLatency{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Update Count",
   "type": "barchart",
   "description": "Number of update operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_updateCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Update Latency",
   "type": "barchart",
   "description": "Total latency of update operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalUpdateLatency{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Remove Count",
   "type": "barchart",
   "description": "Number of remove operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Total Remove Latency",
   "type": "barchart",
   "description": "Total latency of remove operations performed on the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Average Hit Count",
   "type": "barchart",
   "description": "Total number of index hits (the value of this metric may be greater than the map.index.queryCount since a single query may hit the same index more than once)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hitCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Query Count",
   "type": "barchart",
   "description": "Total number of queries served by the index",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Aveage Hit Selectivity",
   "type": "barchart",
   "description": "Average selectivity of the hits served by the index on this member (the returned value is in the range from 0.0 to 1.0 - values close to 1.0 indicate a high selectivity meaning the index is efficient; values close to 0.0 indicate a low selectivity meaning the index efficiency is approaching an efficiency of a simple full scan)",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_averageHitSelectivity{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Indexes: Memory Cost",
   "type": "barchart",
   "description": "Local memory cost of the index (for on-heap indexes in OBJECT or BINARY formats, the returned value is just a best-effort approximation and doesn’t indicate a precise on-heap memory usage of the index)",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 74 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_memoryCost{$ClusterFilterLabel=~\"$ClusterList\", prefix=\"map.index\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}