{
 "title": "All Multi Maps Columns Charts",
 "tags": [
  "data structure",
  "all hazelcast",
  "multimap"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterList", "label": "Clusters", "query": "hazelcast" },
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "hazelcast" },
   { "name": "Cluster2", "query": "hazelcast" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "All Replicated Maps Columns",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "*This dashboard displays federated views of all members of clusters.*"
   }
  },
  {
   "title": "Multi Maps: Entries",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Entry Memory",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Hits",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Events",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Put Count",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Set Count",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_setCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Get Count",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Query Count",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Remove Count",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Max Put Latency",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPutLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Set Latency",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalSetLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Get Latency",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalGetLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Remove Latency",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatency{$ClusterFilterLabel=~\"$ClusterList\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}