{
 "title": "All Count LRU",
 "tags": [
  "gemfire",
  "distribution",
  "eviction",
  "lru",
  "count lru",
  "all count lru"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Count LRU Regions: LRU Destroys",
   "type": "barchart",
   "description": "Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count LRU Regions: LRU Destroys",
   "type": "barchart",
   "description": "Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_entryCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": " Count LRU Regions: Entries Allowed",
   "type": "table",
   "description": "Number of entries allowed in this region.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entriesAllowed{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count LRU Regions: Entry Count",
   "type": "table",
   "description": "Number of entries in each region.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_entryCount{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count LRU Regions: LRU Destroys",
   "type": "table",
   "description": "Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count LRU Regions: LRU Evaluations",
   "type": "table",
   "description": "Number of entries evaluated during LRU operations",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count LRU Regions: LRU Evictions",
   "type": "table",
   "description": "Number of total entry evictions triggered by an LRU.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count LRU Regions: LRU Greedy Returns",
   "type": "table",
   "description": "Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=~\"$ClusterList\", category=\"LRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}