{
 "title": "All Heap LRU",
 "tags": [
  "distribution",
  "eviction",
  "heap lru",
  "lru",
  "all gemfire"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Heap LRU Regions: Entry Bytes",
   "type": "barchart",
   "description": "The amount of memory currently used by regions configured for eviction.",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_entryBytes{$ClusterFilterLabel=~\"$ClusterList\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap LRU Regions: Destroys",
   "type": "barchart",
   "description": "Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=~\"$ClusterList\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap LRU Regions: Entry Bytes",
   "type": "table",
   "description": "The amount of memory currently used by regions configured for eviction.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gemfire_entryBytes{$ClusterFilterLabel=~\"$ClusterList\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap LRU Regions: Destroys",
   "type": "table",
   "description": "Number of entry destroys triggered by an LRU.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruDestroys{$ClusterFilterLabel=~\"$ClusterList\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap LRU Regions: Evaluations",
   "type": "table",
   "description": "Number of entries evaluated during LRU operations",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvaluations{$ClusterFilterLabel=~\"$ClusterList\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap LRU Regions: Evictions",
   "type": "table",
   "description": "Total number of entry evictions triggered by an LRU.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruEvictions{$ClusterFilterLabel=~\"$ClusterList\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap LRU Regions: Greedy Returns",
   "type": "table",
   "description": "Number of non-LRU entries evicted during LRU operations.",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_lruGreedyReturns{$ClusterFilterLabel=~\"$ClusterList\", category=\"HeapLRUStatistics\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}