{
 "title": "All Partitioned Regions Query Charts",
 "tags": [
  "all gemfire",
  "query",
  "storage",
  "partitioned region"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Query Executions",
   "type": "barchart",
   "description": "Number of queries executed on the region across all selected clusters",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Region Query Count (aggregate)",
   "type": "timeseries",
   "description": "Total number of queries executed performed on all regions across all selected clusters",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_queryExecutions{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\",member_type=\"server\"})",
     "legendFormat": "Query Count"
    },
    {
     "expr": "sum(gemfire_queryRequests{$ClusterFilterLabel=~\"$ClusterList\",category=\"CacheServerStats\",member_type=\"server\"})",
     "legendFormat": "Query Requests"
    },
    {
     "expr": "sum(gemfire_queryResponses{$ClusterFilterLabel=~\"$ClusterList\",category=\"CacheServerStats\",member_type=\"server\"})",
     "legendFormat": "Query Responses"
    },
    {
     "expr": "sum(gemfire_partitionedRegionQueryRetries{$ClusterFilterLabel=~\"$ClusterList\",category=\"CachePerfStats\",member_type=\"server\"})",
     "legendFormat": "Query Retries"
    },
    {
     "expr": "sum(gemfire_compiledQueryCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"CacheClientNotifierStatistics\",member_type=\"server\"})",
     "legendFormat": "Compiled Query Count"
    },
    {
     "expr": "sum(gemfire_compiledQueryUsedCount{$ClusterFilterLabel=~\"$ClusterList\",category=\"CacheClientNotifierStatistics\",member_type=\"server\"})",
     "legendFormat": "Compiled Query Used Count"
    }
   ]
  },
  {
   "title": "CQ Query (aggregate)",
   "type": "timeseries",
   "description": "Sum of CQ query execution stats across all selected clusters",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(gemfire_cqQueryExecutionsCompleted{$ClusterFilterLabel=~\"$ClusterList\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Executions Completed"
    },
    {
     "expr": "sum(gemfire_cqQueryExecutionInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"CqServiceStats\"})",
     "legendFormat": "CQ Execution In Progress"
    },
    {
     "expr": "sum(gemfire_numUniqueCqQuery{$ClusterFilterLabel=~\"$ClusterList\",category=\"CqServiceStats\"})",
     "legendFormat": "Unique Query Count"
    }
   ]
  }
 ]
}