{
 "title": "All TCP",
 "tags": [
  "gemfire",
  "distribution",
  "distributed lock",
  "lock"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "TCP: Messages Sent/Received Ratio",
   "type": "timeseries",
   "description": "Average ratio of number of messages sent and received per member.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "gemfire_tcpMessagesSent{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}/gemfire_tcpMessagesReceived{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "TCP: Average Socket Write Time",
   "type": "timeseries",
   "description": "$Cluster: Average time took to write on socket per member.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}/gemfire_syncSocketWrites{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "TCP: Average Socker Lock Time",
   "type": "timeseries",
   "description": "Average time to lock socket per member.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_socketLockTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}/gemfire_socketLocks{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "TCP: Average Sync Socket Write Time",
   "type": "timeseries",
   "description": "Average time to synchronously write on socket per member.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}/gemfire_syncSocketWrites{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "{{$ClusterFilterLabel}} {{instance}}"
    }
   ]
  },
  {
   "title": "TCP: Connection, Channel, Messages",
   "type": "table",
   "description": "TCP messaging stats",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_tcpAcquireConnectionPending{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsActivated{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsDeactivated{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsRegistered{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpChannelsUnregistered{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpConnectionGracefulCloses{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpConnectionUnexpectedCloses{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpDispatchRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpDispatchRequestTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckRequestsSent{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckResponsesReceived{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpFinalCheckResponsesSent{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpMessagesReceived{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_tcpMessagesSent{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TCP: Async/Sync Socket",
   "type": "table",
   "description": "Async and sync socket stats",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_asyncSocketWriteBytes{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWriteRetries{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWriteTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWrites{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_asyncSocketWritesInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLockTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLocks{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_socketLocksInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWriteBytes{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWriteTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWrites{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_syncSocketWritesInProgress{$ClusterFilterLabel=~\"$ClusterList\",category=\"DistributionStats\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}