{
 "title": "All Members",
 "tags": [
  "all gemfire",
  "member",
  "cluster"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "DataSource", "label": "Source", "query": "prometheus" },
   {
    "name": "Cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   { "name": "DataSource2", "label": "Source2", "query": "prometheus" },
   {
    "name": "Cluster2",
    "label": "Cluster2",
    "query": {
     "query": "label_values(gemfire_nodes{member_type=\"server\"},$ClusterFilterLabel)"
    }
   },
   {
    "name": "ClusterList",
    "label": "Clusters",
    "query": {
     "query": "label_values($ClusterFilterLabel)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Locators: Count",
   "type": "stat",
   "description": "Number of running locators",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_locators{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"locator\"} + 1",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members: Count",
   "type": "stat",
   "description": "Number of running data nodes in the cluster excluding locators",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_nodes{$ClusterFilterLabel=~\"($ClusterList)\", member_type=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entries (Primary & Backup)",
   "type": "stat",
   "description": "Total number of entries in all regions including primary and backup.",
   "gridPos": { "h": 5, "w": 6, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_entries{$ClusterFilterLabel=~\"$ClusterList\",member_type=\"server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reads per second",
   "type": "stat",
   "description": "Aggregated get() rate across the cluster.",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gemfire_getsCompleted{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\", member_type=\"server\"}/(gemfire_getTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Cluster: Writes per second",
   "type": "stat",
   "description": "$Cluster: Aggregated put() rate across the cluster.",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "gemfire_putsCompleted{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\", member_type=\"server\"} / (gemfire_putTime{$ClusterFilterLabel=~\"$ClusterList\",category=\"PartitionedRegionStats\", member_type=\"server\"}/1000000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Members",
   "type": "table",
   "description": "Member resource statuses",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "gemfire_system_cpu_usage{$ClusterFilterLabel=~\"$ClusterList\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\", category=\"OffHeapMemoryStats\"}/gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMStats\",exported_instance=\"vmStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\", category=\"OffHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_usedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_committedMemory{$ClusterFilterLabel=~\"$ClusterList\",category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_maxMemory{$ClusterFilterLabel=~\"$ClusterList\", category=\"VMMemoryUsageStats\",exported_instance=\"vmNonHeapMemoryStats\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Pauses\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\",exported_instance=\"ZGC Cycles\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\", exported_instance=\"ParNew\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\", exported_instance=\"ConcurrentMarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\", exported_instance=\"PS Scavenge\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collectionTime{$ClusterFilterLabel=~\"$ClusterList\", exported_instance=\"PS MarkSweep\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$ClusterList\", exported_instance=\"G1 Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "gemfire_collections{$ClusterFilterLabel=~\"$ClusterList\", exported_instance=\"G1 Old Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Partitioned Regions Overall Operations Heatmap",
   "type": "heatmap",
   "description": "Heatmap of the member with the highest put(), get(), destroy(), putAll(), and removeAll() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}+gemfire_putsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}+gemfire_destroysCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}+gemfire_putAllsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}+gemfire_removeAllsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "put() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "Heatmap of the member with the highest put() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "Disk Regions Heatmap",
   "type": "heatmap",
   "description": "Heatmap of the member with the highest number of bytes written to the disk. ",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "max (gemfire_writtenBytes{job=~\"$ClusterList\",category=\"DiskRegionStatistics\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "get() Partitioned Regions Heatmap",
   "type": "heatmap",
   "description": "Heatmap of the member with the highest get() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "max(gemfire_getsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "putAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "Heatmap of the member with the highest putAll() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "max(gemfire_putAllsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  },
  {
   "title": "removeAll() Partitioned Region Heatmap",
   "type": "heatmap",
   "description": "Heatmap of the member with the highest remove() calls completed.",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
   "targets": [
    {
     "expr": "max(gemfire_removeAllsCompleted{job=~\"$ClusterList\",category=\"PartitionedRegionStats\"}) by (exported_instance)",
     "legendFormat": "{{exported_instance}}"
    }
   ]
  }
 ]
}