global:
  scrape_interval:     5s
  external_labels:
    monitor: 'hazelcast'

scrape_configs:
  - job_name: 'myhz'
    scrape_interval: 2s
    static_configs:
      - targets: [localhost:8291, localhost:8292, localhost:8293, localhost:8294, localhost:8295, localhost:8296, localhost:8297, localhost:8298, localhost:8299]
  - job_name: 'myhz2'
    scrape_interval: 2s
    static_configs:
        - targets: [localhost:8391, localhost:8392, localhost:8393, localhost:8394, localhost:8395, localhost:8396, localhost:8397, localhost:8398, localhost:8399]
