global:
  scrape_interval:     5s
  external_labels:
    monitor: 'hazelcast'

scrape_configs:
  - job_name: 'hazelcast'
    static_configs:
      - targets: [localhost:8291, localhost:8292, localhost:8293, localhost:8294, localhost:8295, localhost:8296, localhost:8297, localhost:8298, localhost:8299, localhost:8300]
