#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2022 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF
NAME
   $EXECUTABLE - Build the cluster environment for the workspace

SYNOPSIS
   $EXECUTABLE [-clean] [-?]

DESCRIPTION
   Builds the cluster environment for the workspace. It downloads the Spring Data
   for GemFire dependencies and places them in the following workspace lib directory.

   $PADOGRID_WORKSPACE/lib

OPTIONS
   -clean
             Cleans up the build files after the build completes.

ENVIRONMENT VARIABLES
   SPRING_BOOTSTRAP_ENABLED
             To bootstrap Geode/GemFire with the Spring Container you must set
             SPRING_BOOTSTRAP_ENABLED to "true" in the 'setenv.sh' file.

NOTES
   You can configure Geode/GemFire members in the 'etc/application-context.xml' file.

DEFAULT
   ./$EXECUTABLE
EOF
   exit
fi

pushd $CLUSTER_DIR > /dev/null
mvn install
popd > /dev/null

cp $APP_DIR/lib/* $PADOGRID_WORKSPACE/lib/
# Remove the build files if the -clean option is specified.
if [ "$CLEAN" == "true" ]; then
   rm -rf $APP_DIR/lib
fi

#
# Display build information
#
cat <<EOF

Workspace: $PADOGRID_WORKSPACE

Downloaded the required library files into the following directory.

   $PADOGRID_WORKSPACE/lib

CLASSPATH includes the above directory for all apps and clusters running under
this workspace.

Environment Variables (setenv.sh):
EOF

echo -e "   ${CBrownOrange}SPRING_BOOTSTRAP_ENABLED=\"$SPRING_BOOTSTRAP_ENABLED\"${CNone}"
echo ""

if [ "$SPRING_BOOTSTRAP_ENABLED" != "true" ]; then
   echo "To bootstrap this cluster with the Spring Container, make sure to"
   echo "set SPRING_BOOTSTRAP_ENABLED=\"true\" in the 'setenv.sh' file."
   echo ""
fi
