apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: padogrid-persistent-template
  app: ${APP_NAME}
  role: hazelcast
metadata:
  annotations:
    description: PadoGrid persistent volume and claim.
  name: padogrid-persistent

objects:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APP_NAME}-pvc
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
    storageClassName: ${STORAGE_CLASS_NAME}

- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${APP_NAME}
    labels:
      app: padogrid
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: padogrid
        role: jupyterlab
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: padogrid
          role: jupyterlab
      spec:
        securityContext:
          runAsUser: 1001
          runAsGroup: 1001
          fsGroup: 1001
        containers:
        - image: docker.io/padogrid/padogrid:latest
          name: padogrid
          ports:
          - name: jupyterlab
            containerPort: 8888
          volumeMounts:
          - mountPath: /opt/padogrid/workspaces
            name: ${APP_NAME}-data
          env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: HAZELCAST_SERVICE
            value: ${HAZELCAST_SERVICE}
          - name: HAZELCAST_CLUSTER_NAME
            value: ${HAZELCAST_CLUSTER_NAME}
          - name: PADOGRID_HTTPS_ENABLED
            value: ${PADOGRID_HTTPS_ENABLED}
        volumes:
        - name: ${APP_NAME}-data
          persistentVolumeClaim:
            claimName: ${APP_NAME}-pvc

- apiVersion: v1
  kind: Service
  metadata:
    name: ${PADOGRID_SERVICE_NAME}
  spec:
    type: ClusterIP
    clusterIP: None
    selector:
      app: padogrid
      role: jupyterlab
    ports:
    - protocol: TCP
      port: 8888

parameters:
- description: The application name
  displayName: Application Name
  name: APP_NAME
  required: true
  value: padogrid
- description: Volume space available for data, e.g., 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 4Gi
- description: Storage class name
  displayName: Sotrage Class Name
  name: STORAGE_CLASS_NAME
  required: false
- description: Hazelcast service
  displayName: Hazelcast service
  name: HAZELCAST_SERVICE
  required: false
  value: hazelcast
- description: Hazelcast cluster name
  displayName: Hazelcast cluster name
  name: HAZELCAST_CLUSTER_NAME
  required: false
  value: dev
- description: JupyterLab self-signed certificate
  displayName: PadoGrid HTTPS
  name: PADOGRID_HTTPS_ENABLED
  required: false
  value: "false"
- description: PadoGrid service
  displayName: PadoGrid service
  name: PADOGRID_SERVICE_NAME
  required: false
  value: padogrid-service
