#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-cluster -num -clustergroup -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Add the specified member to the CP members list in the specified padogrid cluster

SYNOPSIS
   $EXECUTABLE [-cluster cluster_name] [-num member_number]
               [-clustergroup cluster_group_name] [-?]

DESCRIPTION
   Adds the specified member to the CP members list. If the member number
   is not specified then the next available member is added.

OPTIONS
   -cluster cluster_name
             Cluster name.

   -num member_number
             Member number 1-$LAST_MEMBER_NUM.

   -clustergroup cluster_group_name
             Cluster group name. Default: dev

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -cluster $CLUSTER -clustergroup dev

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "cp_*" $EXECUTABLE
   exit
fi

if [ "$CLUSTER_GROUP" == "" ]; then
   CLUSTER_GROUP="dev"
fi
if [ "$GROUP_PW" != "" ]; then
   __DATA="${CLUSTER_GROUP}&${GROUP_PW}"
else
   __DATA=$CLUSTER_GROUP
fi

MEMBER_START_PORT=`getClusterProperty "tcp.startPort" $DEFAULT_MEMBER_START_PORT`
let MEMBER_PORT=MEMBER_START_PORT+MEMBER_NUM-1
HOST_NAME=localhost

BASE_URL=http://$HOST_NAME:$MEMBER_PORT

if [ "`which jq`" != "" ]; then
   curl -s -X POST --data \"$__DATA\" $BASE_URL/hazelcast/rest/cp-subsystem/members | jq
else
   curl -s -X POST --data \"$__DATA\" $BASE_URL/hazelcast/rest/cp-subsystem/members
fi
