#!/usr/bin/env bash

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

__options()
{
   echo "-cluster -cpgroup -?"
}

if [ "$OPTIONS" == "true" ]; then
   __options
   exit
fi

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Forcibly destroy the specified CP group in the specified cluster

SYNOPSIS
   $EXECUTABLE [-cluster cluster_name] [-?] -cpgroup cp_group_name

DESCRIPTION
   Forcibly destroys the specified CP group.

OPTIONS
   -cluster cluster_name
             Cluster name.

   -cpgroup cp_group_name
             CP group name. Required.

EOF
if [ "$MAN_SPECIFIED" == "false" ]; then
cat <<EOF
DEFAULT
   $EXECUTABLE -cluster $CLUSTER -cpgroup cp_group_name

EOF
fi
cat <<EOF
SEE ALSO
EOF
   printSeeAlsoList "cp_*" $EXECUTABLE
   exit
fi

if [ "$CP_GROUP" == "" ]; then
   echo "ERROR: CP group name not specified. Command aborted."
   exit 1
fi

if [ "$CLUSTER_GROUP" == "" ]; then
   CLUSTER_GROUP="dev"
fi
if [ "$GROUP_PW" != "" ]; then
   __DATA="${CLUSTER_GROUP}&${GROUP_PW}"
else
   __DATA=$CLUSTER_GROUP
fi

MEMBER_START_PORT=`getClusterProperty "tcp.startPort" $DEFAULT_MEMBER_START_PORT`
let MEMBER_PORT=MEMBER_START_PORT+MEMBER_NUM-1
HOST_NAME=localhost

BASE_URL=http://$HOST_NAME:$MEMBER_PORT

if [ "`which jq`" != "" ]; then
   curl -s -X POST --data "$__DATA" $BASE_URL/hazelcast/rest/cp-subsystem/groups/${CP_GROUP}/remove | jq
else
   curl -s -X POST --data "$__DATA" $BASE_URL/hazelcast/rest/cp-subsystem/groups/${CP_GROUP}/remove | jq
fi
