apiVersion: v1
kind: Service
metadata:
  name: padogrid-jupyter
  labels:
    app: padogrid
    role: hazelcast
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    name: padogrid
  ports:
  - protocol: TCP
    port: 8888
